### ISSUE TITLE
Values for "hour" when setting clock time are off by 1 (2–13 vs 1–12)

### ISSUE THREAD

**Issue by beausmith** [votingworks/vxsuite#1018]
https://user-images.githubusercontent.com/28444/137791296-2579a4ac-9cca-498e-a377-172f1e258387.mp4

**Comment by eventualbuddha** [comment]
Caused by https://github.com/votingworks/vxsuite/pull/828/files#diff-cc8b2cdd3cd906bf61fd6db7eb66b33d5011e57099c2a511fe0902d25c6ec52aR177.
