### ISSUE TITLE
Investigate support for phonetic symbols/diacritics in our current screenreader

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1136]
This is intended as a short research spike to investigate the feasibility of a feature under our current system.

Question: Is adding phonetic symbols/diacritics to the text enough to get correct pronunciation out of our current screenreader? Can it handle/interpret those symbols?

**Comment by jonahkagan** [comment]
Research results: https://docs.google.com/document/d/1VR_xX7dwNEedAhAyoUiFm98RbnOegxhSwJVaD2K6ZhE/edit#

**Comment by mcchilders** [comment]
@benadida did you open a card for actually doing this work yet? Don't want to duplicate.

**Comment by benadida** [comment]
> @benadida did you open a card for actually doing this work yet? Don't want to duplicate.

I don't think I did.
