### ISSUE TITLE
Add no scanner attached screen to precinct-scanner

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1165]

**Comment by benadida** [comment]
what's the reasoning for this one @carolinemodic ? Some faulty connection to scanner?

**Comment by carolinemodic** [comment]
I just thought it would make sense in the same way we have a "no printer attached" or "no card reader attached" screens when those components are not plugged in properly to have the same thing for the scanner.

**Comment by benadida** [comment]
already done as part of m13.
