### ISSUE TITLE
precinct scanner tablet still heating up with no card reader detected (and even without)

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1168]

**Comment by eventualbuddha** [comment]
Maybe @adghayes investigate.

**Comment by jonahkagan** [comment]
I also noticed that the scan service aggressively polls for plustek scanners (there's just a `while` loop with no delay or anything). That's the most aggressive polling I've seen anywhere in the system so far.

**Comment by benadida** [comment]
cannot repro.
