### ISSUE TITLE
Investigate adopting CDF semantics/structure

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1238]
**Task:** Investigate whether adopting part/all of the semantics/structure of the election CDFs would be worthwhile, given that they already contain all the attributes/relationships that are needed to accommodate basically any contest, nationwide. Timeboxed, preferably.

**Goal:** Should we adopt any pieces of the CDF semantics/structure internally? If so, which parts? If not, why not?
Bonus points: start mapping our current data structure to the CDFs, so that we have a head start on translation.

I'll paste this from the notes on the results reporting CDF, which reflects the primary value I think we'd get out of adopting it:

 _The JSON and XML schemas associated with this specification are derived from a UML model that defines the types, structure, and interrelationships of geopolitical geography across the U.S. This model was designed to accommodate multiple types of contests and their many variations, and to provide the capability to report on these contests from higher aggregate levels down to very fine levels of detail, including:_

_Reporting by precinct, splits of precincts, voting centers, and other geographic localities;_
_Reporting by various ballot type, e.g., absentee, election day, early voting; and_
_Reporting by by finer levels of detail such as device type and specific devices, batch, and dropbox._ 

CDFs are here (the election reporting and CVR CDFs are the immediately relevant ones):
https://www.nist.gov/itl/voting/interoperability

Things to keep in mind:
- We know we have to be able to intake data/export data in these formats for 2.0 cert, so we will have to map/translate these fields to our existing ones regardless. The reasoning behind investigating whether it makes sense to adopt some/all of these internally is that our current representation is very MS-driven, and doesn't contain everything we'll need to work nationally (either data or relationships between data), whereas the CDF already does - and it was crafted to handle edge cases without requiring a ton of cruft (see the "other" options on almost every field). So, making sure we at least 1) represent the same data and 2) have the same relationships/hierarchies between that data in our system allows us to take advantage of all that work and "future-proof" our system before it goes into cert.
- The potential downside of doing all this now is that there's a chance we won't need/want most of this for a long time, until we have more clients, if ever. However, if we're going to certify our system, it would be a bummer to have to recert before we could serve a client that does need some or all of these things.
- There are a number of 2.0 certification requirements that reflect "things all the major voting systems can do" that we don't have yet and will have to add, that the CDFs *do already.* So there are some freebies there (in terms of not having to figure out the best way to model/represent that data in relationship to everything else, not in terms of implementation.)
- We have to provide extensive documentation for 2.0 cert, explaining all the relationships between data elements in our schema, all their attributes, etc. If we adopt even a subset of the CDF, that documentation is all done for us.

Certification requirements that might overlap with the election results reporting CDF (which also serves as the election def CDF, since that data is a subset of the reporting data):
- 1.1.1-B Serve Multiple or splict precincts and election districts/1.1.4-C - Precinct splits
- 1.1.1-C Multiple identifiers
- 1.1.4-F - Partisan open primary ballot
- 1.1.4-K - Straight party voting (IN)
- 1.1.4-M - Ranked choice voting contest, Casting (CA)
- 1.1.4-P - Presidential delegate contest, casting (2024)

Certification requirements that might overlap with the CVR CDF:
- 1.1.5-D Record write-in information (need 
- 1.1.5-E Record election and contest information
- 1.1.5-F Record ballot selection override information
- 1.1.5-G Record audit information

**Comment by eventualbuddha** [comment]
This looks like the closest thing I could find to a schema for CDF: https://github.com/usnistgov/ElectionResultsReporting/blob/version2/NIST_V2_election_results_reporting.xsd. Is that right, or am I missing something? There's also a JSON schema that seems maybe out of date as it was not updated the last time the xsd one was.

**Comment by benadida** [comment]
closing this, we've done some investigation. I think best if we treat the format as an import format.
