### ISSUE TITLE
CVR: Record ballot selection override information

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1241]
Per VVSG 2.0 1.1.5-F, **Record ballot selection override information:**
The voting system, if recording voter selections differently than as marked due to election or contest rules in effect, must record information in the CVR that includes:

- identification of the original ballot selections made by the voter
- identification of the changed voter selections (e.g. how it was counted)
- identification of the reasons for the changes (e.g. what counting rule was violated)

**Discussion:** When marking a ballot by hand, a voter may vote in contests in which the voter is not allowed to make contest selections. For example, a voter may elect to vote straight-party, but then make contest selections in contests which differ from the political party contest choices. Election or contest rules may cause a scanner to invalidate the contest markings or require other actions.

Other examples include overvotes on hand-marked ballots (no votes actually count), votes for un-registered write-in candidates in races where write-ins must be registered to be valid (no votes count), or votes for contests from both parties on an open-party-primary ballot that contains ballot info for both parties (no votes count).

**Comment by adghayes** [comment]
Closed by #3283.
