### ISSUE TITLE
Basic logging on all components VxSuite

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1244]
Tasks:

Tasks for General System for Logging:
- [x] #1120 
- [x] https://github.com/votingworks/vxsuite-complete-system/issues/110
- [x] #1097 
- [x] #1095 
- [x] #1096
- [x] #1097 
- [x] https://github.com/votingworks/vxsuite-complete-system/issues/111
- [x] #1259 
- [x] #1260 
- [x] #1261 
- [x] #1262 
- [x] #1263 
- [x] #1264 
- [x] https://github.com/votingworks/vxsuite/issues/2204 
- [x] https://github.com/votingworks/vxsuite/issues/2205

Tasks for log implementation:
- [x] #1121 
- [x] #1203 
- [x] #1204 
- [x] #1205 
- [x] #1206 
- [x] #1145 
- [x] #1172 
- [x] #1173 
- [x] #1174 
- [x] #1175 
- [x] #1250 
- [x] #1251 
- [x] #1252 
- [x] #1253 
- [x] #1248 
- [x] #1249 
- [x] #1254 
- [x] #1255 
- [x] #1256 
- [x] #1257 

Review for v4 submission, remaining tasks:

- [x] https://github.com/votingworks/vxsuite/issues/5006
- [x] https://github.com/votingworks/vxsuite/issues/5333
- [x] https://github.com/votingworks/vxsuite/issues/5334
- [ ] https://github.com/votingworks/vxsuite/issues/5335
- [x] https://github.com/votingworks/vxsuite/issues/5336
- [ ] https://github.com/votingworks/vxsuite/issues/5337
- [x] https://github.com/votingworks/vxsuite/issues/5338
- [x] https://github.com/votingworks/vxsuite/issues/5339
- [x] https://github.com/votingworks/vxsuite/issues/5340
- [x] https://github.com/votingworks/vxsuite/issues/5341
- [x] https://github.com/votingworks/vxsuite/issues/5342

**Comment by carolinemodic** [comment]
Spreadsheet tracking logs: https://docs.google.com/spreadsheets/d/1a27bQZYn35NRq9p_lyTkd7eQ8i8FyOuGsvz1EbuCOUE/edit#gid=0

**Comment by carolinemodic** [comment]
Current Spreadsheet: https://docs.google.com/spreadsheets/d/1iZIjlF3ccL0_YukwoTTqfK_-nVsMmbJT_E-GdORPZ-s/edit?gid=0#gid=0

**Comment by carolinemodic** [comment]
Added tasks representing the remaining work left

**Comment by arsalansufi** [comment]
Closing as this work is essentially done!
