### ISSUE TITLE
Confirm date when changing

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1245]
Per Drew:

>  When doing a lot of installations and configs in series, I've found my most error-prone step is actually setting the date. It's very easy to type 2021-08-04 in lieu of 2021-04-08. I've found a couple machines in QA where I made this mistake. Ultimately it's a QA issue, but I wonder if some sort of confirmation message would dummy-proof it a bit.

And then:

> Echoing the whole date, but in long-form or partial long-form, mainly the month name (i.e. Wednesday, April 8th, 2021) might help

That, plus a confirmation would likely prevent most errors.

**Comment by eventualbuddha** [comment]
@benadida FWIW, this was the CLI date-setting feature, not the ones in the GUI, which is why it was in vxsuite-complete-system.

**Comment by benadida** [comment]
gotcha... I think let's leave it here for now, but good to know what the issue means. We won't lose track of it now that it's in vxsuite :)

**Comment by eventualbuddha** [comment]
Be sure to include timezone info.
