### ISSUE TITLE
VxQR with complete results

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1268]
## Summary

We need a way to update VxQR results sites with complete results, including absentee, affidavit/provisional, etc.

## Requirements

Product spec coming.

**Comment by beausmith** [comment]
Question: For "official results" is there only one large QR code or multiple?

Thinking about how to differentiate the unofficial/official QR Codes…
- Perhaps unofficial are displayed on the screen, and official are printed on the report?

**Comment by mcchilders** [comment]
Feedback from M13a: "VxQR site - currently says does not include “absentee ballots” - desire to also call out 'affidavit ballots.' Reminder to evaluate copy when we include results from VxAdmin/VxCentralScan on the website."

**Comment by mattroe** [comment]
closing in favor of the roadmap issue https://github.com/votingworks/vxsuite-roadmap/issues/12
