### ISSUE TITLE
Review and Improve Precinct Scanner flows

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1302]
VxScan flows were put together and iterated fairly quickly, without a holistic design review. Let's do the holistic design review including feedback from the field:

* voters don't wait for scanning: can we prompt them in some way to wait?
* CVR export missed by some poll workers: is there a more linear way, wizard-like way to close the polls?
* open polls should have a screen to confirm the polls are open and to remove the card.
* "follow the green button" would be great if it worked the whole way through (a bit like the previous point)

**Comment by beausmith** [comment]
# Proposal for prompting voter to wait for success/fail screen.
After the voter inserts their ballot, the screen displays a series of 3 steps to be completed:
1. Scanning Ballot
2. Reviewing Votes
3. Success

When running, each step shows a progress indicator. When complete a checkmark is shown.

If there is an issue with the ballot, switch to display the error screen.

**Comment by benadida** [comment]
A couple of thoughts, none showstopper just suggestions:

- maybe "scanning sheet" so it gives a sense that it's the physical act of scanning.
- "reviewing votes" gives me almost a sense that it's reviewing to tell me which selections are "correct". Maybe "reading choices"?

**Comment by beausmith** [comment]
This UI is for the voter, they know what a "ballot" is but I'm not certain they will understand what a "sheet" is. Are you trying to solve for when there are multiple ballot sheets per voter?

**Comment by beausmith** [comment]
I agree that "Reviewing Votes" might not be quite right, but "Reading Choices" doesn't quite seem right either. Thinking on this…

**Comment by jonahkagan** [comment]
Maybe something like "Checking for votes"

**Comment by beausmith** [comment]
That's better. How about just "checking votes" to keep it shorter?

- Scanning Ballot
- Checking Votes
- Success

**Comment by beausmith** [comment]
Resolved by #1357 #1359
