### ISSUE TITLE
VxAdmin: improved all-precincts tally report design

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1306]
An ideal all-precincts tally report is a grid that shows individual precinct tallies in rows or columns so you can see all the numbers on one sheet.

**Comment by adghayes** [comment]
Closing this unless we still have a clear need. I can see a use case in Mississippi, but not in single-precinct New Hampshire or in very large jurisdictions with lots of precincts. The ballot count reports allow you to see a grid of precincts for counts, but not results.
