### ISSUE TITLE
VxMark: automatically open/close polls on VxMark when printing Open/Close Polls report from VxScan

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1311]
## Background

VxMark and VxScan have independent polls-open/close states, as expected from non-networked machines.

VxScan's polls-open / polls-close report is printed on VxMark, by way of the poll worker card. The flow currently is:
- poll worker opens polls on VxScan, writes to card
- poll worker takes card to VxMark, prints report
- poll worker hopefully remembers to tap "open polls" on the VxMark, too.

Our customers have also experienced confusion when first opening polls on VxMark and opening polls on VxScan second. We should encourage users to open polls on VxScan first before printing tally/opening polls on VxMark.

## Expected Flow

If a poll worker card inserted into VxMark has no tally report written to it:
- Poll worker inserts card in VxMark
- Poll worker taps open / close polls
- Modal presented to guide the user to open/close polls on VxScan first. 

Modal content:
- "Open polls on VxScan before opening VxMark"
- Primary button 1 (grey): "Open/Close polls now"
- Primary button 2 (green): "Cancel" (to close modal)

If a poll worker card inserted into VxMark has a tally report written to it (the common happy path behavior):
- Poll worker opens/close polls on VxScan, writes tally to card
- Poll worker takes card to VxMark
- When inserted, poll worker is prompted to print tally report and open/close polls
- After the poll worker confirms the action on-screen, the tally report should be printed and polls are closed/opened on VxMark

## Tasks
- [ ] Add modal to prompt user to open/close polls on VxScan when pollworker card does _not_ have tally report written to it
- [ ] Automatically open/close polls when pollworker card has tally report written to it

**Comment by taravancil** [comment]
Pausing this in favor of getting `nh-demo` into main. The first task is completed by https://github.com/votingworks/vxsuite/pull/2139/, will mark that as done once it's merged into main.
