### ISSUE TITLE
Export and import CDF CVRs

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#1333]
## Summary

This is an umbrella task for implementing VVSG 2.0 Requirement 4.1-C (Exchange of cast vote records (CVRs)).

### VVSG 2.0 Requirement
**4.1-C: Exchange of cast vote records (CVRs)**
The voting system’s audit, casting, tabulation, and vote-capture functions dealing with CVRs must have the capability of importing or exporting CVRs according to CDF specification(s).
**Discussion:** Devices that export or import CVRs typically include voter-facing and batch-fed scanners, election management systems, and other devices used for adjudication or auditing. This requirement indicates that these devices have the capability to import or export CVRs in the respective CDF(s). More information can be found in: [NIST SP 1500-103 Cast Vote Records Common Data Format Specification](https://github.com/usnistgov/CastVoteRecords).

### VXSuite requirements
- The scanners must export CVRs in CDF
- Election manager must import scanner CVRs in CDF
- Election manager must export cumulative CVRs in CDF

## Non-Requirements
- Open question: are we allowed to add extensions to the CDF? 

## Tasks
- [ ] #1340
- [ ] #1341
- [ ] #1342

**Comment by eventualbuddha** [comment]
> Election manager must import scanner CVRs in CDF
Do we have to import CVRs in CDF from other non-VX systems?

**Comment by adghayes** [comment]
Closed by #3283.
