### ISSUE TITLE
Add VVSG required data to CVR exports 

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#1334]
## Summary

This is an umbrella task for implementing VVSG 2.0 Requirement 1.1.5 (Recording Voter Choices). Depends on #1333.

## Requirements
**Bold** requirements are ones we don't currently meet.

- 1.1.5-A: Casting and recording - The voting system must support casting a ballot, recording each vote precisely as indicated by the voter subject to the rules of the election jurisdiction, and creating a cast vote record that can be tabulated and audited.
- 1.1.5-B: Ballot orientation - The voting system, when using pre-printed ballots, must either:
  - 1.1.5-B.1: correctly mark pre-printed ballots regardless whether they are loaded upside down, right side up, forward, or reversed
  - 1.1.5-B.2: detect and reject pre-printed ballots that are oriented incorrectly
- 1.1.5-C: Record contest selection information - The voting system must record contest selection information in the CVR that includes:
  - 1.1.5-C.1: all contest selections made by the voter for all supported vote variations
  - 1.1.5-C.2: positions on the ballot associated with each contest selection made by the voter when multiple selections are permitted, if applicable
  - Discussion: For item 2, some contests such as for RCV may place candidate choices on the same line of the ballot, therefore the positions of the candidates may need to be recorded.
- 1.1.5-D: Record write-in information - The voting system must record write-in information in the CVR that includes:
  - 1.1.5-D.1: identification of write-in selections made by the voter
  - 1.1.5-D.2: the text of the write-in, when using a BMD or other device that marks the ballot for the voter
  - **1.1.5-D.3: an image or other indication of the voter’s write-in markings**
  - **1.1.5-D.4: the total number of write-ins in the CVR**
- 1.1.5-E: Record election and contest information - The voting system must record additional contest information in the CVR that includes:
  - 1.1.5-E.1: identification of all contests in which a voter has made a contest selection
  - **1.1.5-E.2: identification of all overvoted and undervoted contests**
  - **1.1.5-E.3: the number of write-ins recorded for the contest**
  - **1.1.5-E.4: identification of the party for partisan ballots or partisan contests**
  - Discussion: For identification of the party, a ballot in a partisan primary election may in some cases contain contests for different parties. Thus, an indication as to partisanship of the contests is required.
- 1.1.5-F: Record ballot selection override information - The voting system, if recording voter selections differently than as marked due to election or contest rules in effect, must record information in the CVR that includes:
  - **1.1.5-F.1: identification of the original ballot selections made by the voter**
  - **1.1.5-F.2: identification of the changed voter selections**
  - **1.1.5-F.3: identification of the reasons for the changes**
  - Discussion: When marking a ballot by hand, a voter may vote in contests in which the voter is not allowed to make contest selections. For example, a voter may elect to vote straight-party, but then make contest selections in contests which differ from the political party contest choices. Election or contest rules may cause a scanner to invalidate the contest markings or require other actions.
- 1.1.5-G: Record audit information - The voting system must be capable of recording audit-related information in the CVR or collection of CVRs as they are created, that includes:
  - 1.1.5-G.1: identification of the specific creating device such as a serial number
  - 1.1.5-G.2: identification of the geographical location of the device
  - 1.1.5-G.3: identification of the ballot style corresponding to the CVR
  - 1.1.5-G.4: identification of the corresponding voted ballot
  - **1.1.5-G.5: for multi-sheet ballots, identification of the individual sheet corresponding to the CVR, along with the identification of the ballot style**
  - 1.1.5-G.6: identification of the batch containing the corresponding voted ballot, when applicable
  - **1.1.5-G.7: sequence of the corresponding voted ballot in the batch, when applicable**
  - Discussion: Item 2 can be any identification scheme that is preferential in the jurisdiction, e.g., polling place name, address, geographical coordinates, etc. Item 4 can be satisfied by printing a unique ID on the ballot as it is scanned and including that ID in the corresponding CVR. Item 5 ensures that every sheet of a multi-sheet ballot contains the sheet number as well as the ballot style ID. This way, a ballot style ID could be defined to include all sheets, or each sheet could be defined with a unique ballot style. Items 6 and 7 are necessary when ballot batching is in effect.
- **1.1.5-H: Store and link corresponding image - The voting system must be capable of storing an image of a paper ballot and linking this image to the specific associated CVR.**
  - Discussion	The image could be linked to the CVR by, for example, creating a filename for the image that is the same as the identifier from item 4 in Requirement - 1.1.5-G – Record audit information.

## Non-Requirements
N/A

## Tasks
- [x] #1242 
- [x] #1240 
- [ ] #1335
- [ ] #1336
- [x] #1241 
- [ ] #1337
- [ ] #1338
- [x] #1339

**Comment by adghayes** [comment]
Closed by #3283.
