### ISSUE TITLE
CVR: for multi-sheet ballots, identification of the individual sheet corresponding to the CVR

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#1337]
VVSG 1.1.5-G.5

> The voting system must record additional contest information in the CVR that includes: for multi-sheet ballots, identification of the individual sheet corresponding to the CVR, along with the identification of the ballot style

**Comment by adghayes** [comment]
We have this marked in the matrix as completed because we do already do this, but leaving this up because we'll probably change the way we do this when we move to CDF and I want to track its completion.

**Comment by adghayes** [comment]
Closed by #3283.
