### ISSUE TITLE
Rethink and redesign Importing CVRs flow

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1362]
In https://github.com/votingworks/vxsuite/issues/1344 we added automatic deduping of ballots to election-manager. This prompted some wider-scope discussions about the flows and design of importing CVRs. 

One edge case explicitly NOT addressed in the ticket above is how to handle the scenario where a user exports 100 ballots from the batch scanner. Then deletes a batch of lets say 10 ballots, and scans 5 new ballots, and imports that file to election-manager. Should the 10 ballots deleted in the second file be deleted from election-manager? Today they are not but they probably should be. Likely we should only ever have 1 CVR file "active" per machine ID, but its unclear how the design of this should be done. 

Two design ideas from @beausmith relating to the import path. 
Should we do away with the import modal and instead split the "tally" tab into two pages, one for tally reports, and one for managing CVR files. On the CVR management page you would see in 1 consolidated table any imported files alongside any files on the current USB drive that the user has yet to import. There the user could import and include/exclude different files at will. 

Should we automatically prompt the user to import files as soon as a USB drive is inserted with new CVR files? Pop open a modal automatically saying something like "50 new CVR records found would you like to import?". Then the user could click to expand more information if they want but by default just see the top level piece of data: all the new CVR records across all files on the usb drive. 

How to handle the test vs. live mode situation is an issue to keep in mind in any of these options.

**Comment by benadida** [comment]
we're going to get new feedback from new split flow, closing.
