### ISSUE TITLE
update product naming in product

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1363]
- [x] Election Manager becomes VxAdmin
- [x] Ballot Scanner becomes VxCentralScan
- [x] VxMark stays VxMark, and notably no longer says "VxMark + VxPrint", just says VxMark. If there's no attached printer (so the underlying mode is VxMark only), then it might say "VxMark with standalone printer."
- [x] Precinct scanner is VxScan
- [x] bas remains VxEncode
- [x] bmd in print-only mode remains VxPrint.

**Comment by carolinemodic** [comment]
FYI @jonahkagan I tried to use the new names when setting up the logging stuff but predicted the wrong names for the central/precinct scanner: https://github.com/votingworks/vxsuite/blob/main/libs/logging/src/log_source.ts

**Comment by carolinemodic** [comment]
Oh you already saw that haha nevermind
