### ISSUE TITLE
investigate a MOK flow for the surface go's enhanced security

### ISSUE THREAD

**Issue by umbernhard** [votingworks/vxsuite#1378]
We can't install our own keys on the Surface Gos because Microsoft, so we will have to use a Machine Owner Key (MOK) along with Debian's `shim` in order to run our packaged bootloader/cmdline/kernel binary with Secure Boot enabled.

**Comment by umbernhard** [comment]
This page describes the modifications we'll need to make to the enhanced security changes: https://wiki.debian.org/SecureBoot

**Comment by benadida** [comment]
Should we close this one?

**Comment by umbernhard** [comment]
Yeah. For posterity: it's hard (impossible?) to boot a unified kernel image with an MoK, which severely limits the effectiveness of our other ESI tools like dm-verity.
