### ISSUE TITLE
scan and centralscan: don't allow user to clear election data until they export the backup with full image scans

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1384]
There is a button in the admin screen of VxCentralScan (frontends/bds in vxsuite) labelled "Export Backup..." that exports a zip package containing full image exports of all the ballots scanned, the cvr file, etc. We want to make sure that users do this before they clear all of the election data on the machine. Feel free to work with Beau on the design / user flows, but also take ownership of how you think this should work. A few possibilities: 
- Disable the "Delete election data" button with a sentence over it as to why until the backup is exported
- When you click "Delete election data" have a modal pop up that says you must first export backup (and maybe let you do that from the modal?) 

We will also want to do the same thing in VxScan (the precinct scanner found in frontends/scan in vxsuite). In VxScan we should update the language on the "Unconfigure" button to match VxCentralScan "Delete Election Data from VxScan…". 

In order to do this we will need to somehow track what scans have been exported, you will need to do this in the backend of the scanning service in services/scan in vxsuite. This backend is used by both the VxScan and VxCentralScan frontends.

Nice to Have: 
In VxCentralScan we haven't updated "Export Backup" to use the same nicer, export to usb modal flow that the regular "Export" button has, and that either Export option has in VxScan. VxScan also saved the backup automatically into a folder called scanner-backups we should use the same logic/naming in both places (and perhaps include the machine id in the filename?). This work to clean up the UI of VxCentralScan here can be split out as a separate task.

Point of contact on UI Design / Flows : Beau
Point of contact for engineering help, particularly module-scan : Brian
Point of contact for eng help with the save file to usb modals : Caroline

**Comment by mattroe** [comment]
@benadida this should be for VxScan too not just VxCentralScan

**Comment by carolinemodic** [comment]
I have confirmed that the export still works as expected, other then one slight issue I'm seeing with the automatic export in VxScan (doing a custom save works fine still), will look into that.

**Comment by carolinemodic** [comment]
Oh VxScan is working I just didn't realize it was getting saved to a folder in scanner-backups on the usb drive. 
We should actually update VxCentralScan to save to the same location that VxScan is. But perhaps both should have the machine ID in the filename.
