### ISSUE TITLE
add ability to reboot off USB at least for surface go in kiosk-browser

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1401]
Using appropriate authentication (likely superadmin), provide the ability to reboot a machine (VxAdmin, VxCentralScan, VxScan, VxMark) from USB, without having to push any F9/F10 keys or other special key-combination. This will then allow for software upgrades from the USB stick.

This is particularly necessary from the Surface Go 2, but should be the same implementation for all components.

I've successfully tested doing this with `efibootmgr`, but here's what's necessary:

* Plug in USB stick and USB keyboard, and THEN boot completely into Linux.
* `efibootmgr` should list “Linpus Lite”. If it doesn’t, reboot with USB stick plugged in.
* Set the boot order to include first “Linpus Lite”, then “EFI USB Device”, then `0000` which should correspond to hard-drive linux. Yes, you need to put both "Linpus Lite" and then "Linux USB." Only one will not work. This usually looks like

```
sudo efibootmgr -o 0001,2001,0000
```

Then reboot. You should be booting off USB now, on every boot until you remove the USB stick, or until you reset boot order with `efibootmgr`.

What this might look like as an actual flow:

* go to superadmin screen, tap "reboot from USB for upgrade"
* if `efibootmgr` can see "Linpus Lite", then set the boot order and reboot.
* if not, then prompt to insert USB stick, and reboot. On reboot, go right back to superadmin screen and tap "reboot" again. Set boot order, and reboot.

**Comment by carolinemodic** [comment]
I was able to repro the behavior Ben describes in the ticket on the lenovo ideapad flex. I could not on the hp elitebook but ... I guess we aren't using that anymore anyway.
