### ISSUE TITLE
display machine brand & possibly footer on machine-locked screen

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1406]
Hard to tell VxAdmin and VxCentralScan laptops apart on the machine lock screen otherwise.

**Comment by beausmith** [comment]
@arsalansufi - Here is my guidance…

## VxAdmin

Please update the title on the locked screen of VxAdmin from "Machine Locked" to "VxAdmin is Locked". Here is what the screen currently looks like:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/28444/160920795-bf9b792a-92d2-44a7-9034-aba883f23b29.png">

## VxCentralScan

Please update the VxCentralScan (or `bsd` for ballot scanning device 🙃) lock screen to mirror the VxAdmin screen above by adding the same footer, and updating the title to be "VxCentralScan is Locked". Here is what the screen currently looks like:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/28444/160921474-58c8962b-ca7f-462e-97ff-b8056f715b7b.png">

**Comment by arsalansufi** [comment]
In terms of adding the footer to VxCentralScan's lock screen, the code for its lock screen already includes a footer:

https://github.com/votingworks/vxsuite/blob/755ac9427fad41d51098ece2ebaa9d87104c84fa/frontends/bsd/src/screens/machine_locked_screen.tsx#L28-L33

The footer just renders nothing when no election definition is provided:

https://github.com/votingworks/vxsuite/blob/755ac9427fad41d51098ece2ebaa9d87104c84fa/libs/ui/src/election_info_bar.tsx#L28-L30

So once an election is properly loaded, the footer should display (unless I'm missing something).
