### ISSUE TITLE
vxadmin: printing test deck prints too many ballots and some malformed ones in some cases

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1416]
## Description
Test deck printing may be broken, possibly in multi-precinct elections (so didn't show up in demo election test)

It appears that multiple print jobs are being sent, not just one for the single precinct. Maybe the logic that prints all the test decks is being mistakenly activated for single precinct. But in any case it's always printing the selected precinct that was requested, multiple times.

## Repro
* Use 2021-06-08 Warren County election definition
* print a single precinct test deck
* printing goes on and on, and eventually prints a malformed ballot (front and back are same)

**Comment by carolinemodic** [comment]
@benadida Was this happening every time for you? I've tested this with the election you mentioned and can't repro, I haven't tried a fully locked down machine yet but when I run through the production builds in vxsuite-complete-system & kiosk-browser in my VM it doesn't repro in either Debian or Ubuntu 20.

**Comment by benadida** [comment]
repro'ed this with 2021-06-08 Ms county 75 (Warren), try printing test deck for single precincts: Auditorium prints the test deck twice. Plumbers/Pipefitters prints test deck twice and then a malformed ballot.
