### ISSUE TITLE
VxMark: Hardware diagnostic report

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#1417]
## High-Level Requirement

BMD should have ability to print a hardware diagnostic report that lists:
* power status (plugged in and battery status)
* printer status (plugged in and toner + paper levels where possible)
* accessible controller & audio status (as per latest active diagnostic test run)

## Details

* On the admin screen, offer a "Hardware Diagnostic Report" button.
* Display, on screen, power status, printer status, and latest result from accessible controller & audio active diagnostic test, including when this was run.
* Offer a "print" button which, when tapped, prints the report including the data that is displayed on screen, plus machine ID, what it is configured for (election hash and name), and current time.

**Comment by adghayes** [comment]
I'm just going to close this because we don't care about VxMark's diagnostic report, as it is not a part of the certified system.
