### ISSUE TITLE
Scan: refactor how we determine blank ballots

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1421]
## Description
A blank ballot scanned by VxScan appears to flash an "unknown reason" for adjudication and then immediately is accepted.

## Repro
1. Set up an election with `BlankBallot` adjudication
2. Scan a blank ballot
3. Watch the screen flicker for a second and then the ballot be accepted without adjudication

## Expected behavior
Blank ballots with proper config should show up as blank ballots requiring adjudication, not be accepted as is.

## Tasks
- [ ] #1638

**Comment by carolinemodic** [comment]
Prior filing of this issue: https://github.com/votingworks/vxsuite/issues/1099

**Comment by carolinemodic** [comment]
Temporary fix of this issue for m13a: https://github.com/votingworks/vxsuite/pull/1424 
We should determine all of this server-side and simplify the client-side logic in both BSD and Precinct-Scanner for m13B

**Comment by mattroe** [comment]
@benadida is this still an important tech improvement to make after implementing https://github.com/votingworks/vxsuite/issues/1638?

**Comment by benadida** [comment]
> @benadida is this still an important tech improvement to make after implementing #2102?

Yes, we're not done with this refactor.

**Comment by adghayes** [comment]
This is complete, and blank ballot determination is done on the backend (#3407).
