### ISSUE TITLE
Make booting from USB to install new software as simple as possible

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1431]
Use clonezilla scripts or some other process to automate as much as booting from USB and installing a new updated software image as simple as possible. In order to update software in the field someone will plug in a USB and then click a boot to boot from USB, so we need a way for after this happens things just get updated on the machine with as few clicks as possible so a non-technical person can execute this process.

**Comment by benadida** [comment]
this is part of #1502
