### ISSUE TITLE
vxscan: further streamlining of polls open & close

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1433]
- #1477

**Comment by beausmith** [comment]
**Requirement:** VxScan does not operate unless a USB drive is mounted.

## VxScan Open Polls Flow
1. Insert Poll Worker card when polls are closed.
2. Screen:
    - title "Do you want to open the polls?"
    - primary button: "Open Polls"
    - button: "Other Options" - clicking shows default poll worker screen which also contains an "Open Polls" button.
3. User clicks "Open Polls".
4. Screen shows indeterminate progress indicator with text: "Opening the polls…" while the Open Polls report is being saved to the poll worker card. This screen should have a minimum display of a 1–2 seconds.
5. Screen:
    - title: "Polls are open."
    - paragraph: "Print the Open Polls Report by inserting card into VxMark."
6. User removes card and screen shows Insert Ballot screen.

## VxScan Close Polls Flow
1. Insert Poll Worker card when polls are open.
2. Screen:
    - title "Do you want to close the polls?"
    - primary button: "Close Polls"
    - button: "Other Options" - clicking shows default poll worker screen which also contains an "Close Polls" button.
3. User clicks "Close Polls".
4. Screen shows indeterminate progress indicator with text: "Closing the polls and exporting results to USB drive…" while the Close Polls report is being saved to the poll worker card and the results are being exported to the card. This screen should have a minimum display of a ~3 seconds.
5. Screen shows:
    - title: "Polls are closed."
    - paragraph: "Results have been exported to the USB drive."
    - paragraph: "Print the Close Polls Report by inserting card into VxMark."
6. User removes card and screen shows Polls Closed screen.

**Comment by beausmith** [comment]
Related: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269852606799

**Comment by mcchilders** [comment]
Requires that #1477 is done first

**Comment by beausmith** [comment]
Flowchart…

![Uploading 00818BFD-71DC-415D-B78D-0650BB3668C2.jpeg…]()

**Comment by beausmith** [comment]
Flowchart: 

![A8022D74-D417-427F-BB3B-9865793ABEF4](https://user-images.githubusercontent.com/28444/157111046-9aa9940c-a08b-4b49-bf4a-44ee79546c31.jpeg)
