### ISSUE TITLE
Enhanced System Integrity on VxMark, VxAdmin, VxCentralScan with automated script and instructions

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1434]

**Comment by umbernhard** [comment]
This gist contains instructions for the locking down the machine with the requisite changes. https://gist.github.com/umbernhard/c2dc439a59564e3506a7132a9f56ac68

**Comment by mcchilders** [comment]
(The GitHub automatic closing of the issue if the related PR is merged and "closes this issue" is checked is real broken, so I'm closing this :)
