### ISSUE TITLE
add TOTP & signature setup scripts to default setup script

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1437]
https://github.com/votingworks/vxsuite-complete-system/blob/main/setup-scripts/setup-signify.sh

and

https://github.com/votingworks/vxsuite-complete-system/blob/main/setup-scripts/setup-tpm2-totp.sh

should be part of the main setup script.

**Comment by umbernhard** [comment]
This will be address when votingworks/vxsuite-complete-system#130 gets merged.

**Comment by mcchilders** [comment]
(The GitHub automatic closing of the issue if the related PR is merged and "closes this issue" is checked is real broken, so I'm closing this :)
