### ISSUE TITLE
Review how we configure all components

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1438]
It's inconsistent in actions and in words:
- admin card with election config
- USB stick with ballot package

**Comment by beausmith** [comment]
Context: from @ginvdr 

> Now that we have multiple components being "programmed" via the "ballot package," I don't think that's the most intuitive name. If I were "exporting a ballot package" I would think I'm exporting ballot files that can be sent to a printer.  Ideas:
> 
> - Election Package
> - Election Program
> - Precinct Setup
> - Hardware Program
> - Precinct Configuration (I like this as we currently say Precinct Scanner is Not Configured - Insert USB Drive with configuration but configured feels like a big word)
> 
> In VxCentralScan we call it the "Election Configuration"

**Comment by eventualbuddha** [comment]
Some future work on the scanning system may remove the need of a ballot package altogether. What would we want the flow to look like then?

**Comment by benadida** [comment]
We're converging on using cards for everything. Closing this.
