### ISSUE TITLE
Debug printing from Debian on HP Color Laserjet Pro M454dn/dw and ideally Brother printer

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1451]
## Description
On debian I discovered the printer driver we were using before no longer worked for the HP 404 printer. When I manually added the printer to my printers in linux it automatically used the "generic postscript driver" which did work when I replaced the ppd file for that. I'm guessing the same issue might happen with our other printers so we should test and fix those as well. 

## Repro
On debian run kiosk browser with the printer in question connected, try to print something, see if it works. 
NOTE: If you haven't already run `sudo apt install cups-bsd` first to make sure lpr is installed.

**Comment by benadida** [comment]
worked great on M404dn, but am out of toner on M454dn so can't be certain... but I do think it's working cause I see the printer detected and print job started. I'll get toner and confirm :)

**Comment by benadida** [comment]
working on m454dn with the generic postscript driver. @carolinemodic will follow up with the appropriate small patch.

**Comment by benadida** [comment]
solved in https://github.com/votingworks/vxsuite-complete-system/pull/141
