### ISSUE TITLE
Add totp code to all components

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1452]
## Summary
Right now the totp code only exists on VxScan we should add it VxMark, VxAdmin and VxCentralScan (priority is in that order)

**Comment by carolinemodic** [comment]
Where we are currently fetching this code in VxScan: https://github.com/votingworks/vxsuite/blob/ce7f4e1eb32f0098d57ad83c7e79655faa05869d/frontends/precinct-scanner/src/screens/poll_worker_screen.tsx#L203 
And displaying it: https://github.com/votingworks/vxsuite/blob/ce7f4e1eb32f0098d57ad83c7e79655faa05869d/frontends/precinct-scanner/src/screens/poll_worker_screen.tsx#L445 

Should go on the pollworker screen for VxMark.

**Comment by benadida** [comment]
closing this as we're going to move to a different feature.
