### ISSUE TITLE
Improve Audio track to make it clearer to the user how to print their ballot on the review screen

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1465]
Make it more obvious that the user needs to press the right button to print their ballot when they are on the review screen in bmd, which is located in vxsuite in frontends/bmd 

Source: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269878622849

**Comment by beausmith** [comment]
This is not a bug. I tested the audio and it does instruct the user to press the right arrow to print their ballot. 

Currently the [review screen speaks](https://github.com/votingworks/vxsuite/blob/main/frontends/bmd/src/pages/review_page.tsx#L407-L412):

> To review your votes, advance through the ballot contests using the up and down buttons. To change your vote in any contest, use the select button to navigate to that contest. When you are finished making your ballot selections and ready to print your ballot, use the right button to print your ballot.

The problem that two users ran into is that if they pressed the up/down arrows to review their votes — and optionally changed their votes and came back to the review screen — then they were unsure what to do. 

There are two ways they can print their ballot:
1. If they hit the right key their ballot will be printed.
2. If they press the up/down key, they will eventually cycle to the "I’m Ready to Print My Ballot"  button. If they press the select key on this button, their ballot will print.

Options:
- Do nothing. **◀️ My vote**
- Update each contest to contain instructions on how to print ballot.
- Update the copy around the "I’m Ready to Print My Ballot"  button to add more context.
- Add something that can be tabbed to after the last contest which will restate how to print their ballot.

**Comment by carolinemodic** [comment]
@beausmith Sounds like just added an extra instruction on the "I'm ready to print my ballot" button to "press select to print" could help clarify? But also fine with closing this and doing nothing for the time being. 

 I could also see an argument to just reorder the instructions to say to press right to print the ballot before giving the up/down instructions so they know that (since thats the most common thing they will care about) right away.

**Comment by benadida** [comment]
we'll hold off on any action here until we have proper testing by vision-impaired voters.
