### ISSUE TITLE
VxAdmin: Make programming admin cards easier

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1466]
Initial Feedback: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269484826299

Remove the "Enable overwrite protection" step in VxAdmin when programming admin cards and just automatically do that when you are programming an admin card. 

We could just do it automatically or add an extra step to the modal "This card has been previously programmed as an admin card, are you sure you want to rewrite it?" 

As a first step, for this ticket, let's do the simple thing:
- when programming an admin card, automatically override write protection
- don't change any of the buttons, so that if someone really wants to, they can override write protection on an admin card and make it a poll worker card, but let's not make that the default.

**Comment by beausmith** [comment]
Also related the Cards flow that I documented in: https://docs.google.com/document/d/1jBoQqIE7IEr3G_zGfAkl0gDD2kammjIDzpOf7K7StsI/edit#heading=h.5ivg5sue8rxi

**Comment by carolinemodic** [comment]
Context: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269484826299
