### ISSUE TITLE
Make "Remove Election" Button in VxMark clearer and red

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1467]
The button to remove the election configuration in VxMark just says "Remove" and isn't the "warning" red button type. It should definitely be red and have a clearer message on it like "Unconfigure Machine" which is the copy used in VxScan. 

Screenshot of what it current looks like. This is on the admin screen in VxMark (frontends/bmd) 
<img width="568" alt="Screen Shot 2022-03-03 at 9 39 33 AM" src="https://user-images.githubusercontent.com/14897017/156620884-fb84c0fa-c94f-40fe-8606-83abc2accaee.png">

source: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269852606799

**Comment by beausmith** [comment]
Related: https://github.com/votingworks/vxsuite/issues/1433#issuecomment-1058527464

**Comment by taravancil** [comment]
I noticed there is as similar "Election definition is loaded. [Remove]" interface in VxEncode. I expect we'll want to do the same thing there so I created a ticket for that and made a PR #1526. @beausmith @carolinemodic let me know if we don't want to do that, and I'll close the PR.

**Comment by beausmith** [comment]
@taravancil - You can change VxEncode, but note that this product has been long neglected as we are not actively offering it to customers.
