### ISSUE TITLE
VxAdmin: add sample ballots to the exported ballot package

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1472]
In VxAdmin there is an "Export Ballot Package" button that is on the ballots tab that exports a ZIP package with ballot proofs and is used to configure the scanning machines. Election officials also want this package to contain sample ballots to send to their printers so they don't have to individually save each ballot (which you can do when viewing a ballot). In the future we think we won't need this package to configure the scanning machines but will still need a way for election officials to export the ballot info they need. For now we can just add sample ballots to this ballot package. Note that we will need to test that this does not break the configuration of VxCentralScan and VxScan (which share the same codepath for this) 

Context: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269574435949

**Comment by mattroe** [comment]
Closing in favor of https://github.com/votingworks/vxsuite/issues/2146 that should address this feedback
