### ISSUE TITLE
Unconfig VxScan before ejecting usb causes loop

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1475]
VxScan cannot be unconfigured without first ejecting USB or else you get into a loop where it auto-loads the ballot package. 

In practice, this should not be a problem as the process we are instructing is to take a backup export before the machine is reconfigured (which prompts the user to export the USB drive after taking a backup). Need to add the backup procedure / reconfiguration to our documentation

A quick fix here is to eject the USB in software on unconfigure.

**Comment by beausmith** [comment]
https://votingworks.slack.com/archives/CJU9MSC6S/p1646269893634189
