### ISSUE TITLE
VxScan: VxScan should not operate without a USB drive detected.

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1477]
If there is no USB Drive detected, VxScan should display a full screen blocking modal with this content

Title: No USB Drive Detected
Paragraph: Insert USB drive into the USB hub.

https://votingworks.slack.com/archives/CJU9MSC6S/p1646334551818259

**Comment by carolinemodic** [comment]
Note: we will need to make this play nicely with the fact that the usb will be automatically ejected after results are exported at the end of the election. We will want that to still show "Polls Closed" and not "You must insert a USB" but should block opening the polls again on having a usb. See discussion in: https://votingworks.slack.com/archives/CEL6D3GAD/p1647372739869439

**Comment by beausmith** [comment]
Note: We are removing the "Eject USB" command from the process of poll worker closing the polls. Thus the above comment is no longer an issue, and the feature can be implemented as described in the body of the ticket.
