### ISSUE TITLE
Non-voter msgs read by screen reader

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1478]
We've noted a couple instances of the screen reader reading everything on the screen, even when that may not be appropriate for a voter. Examples:

- If there is a system message shown onscreen (something not plugged in) the screen reader interrupts a voter session to read it (this may be desired behavior, since a voter would see these messages onscreen, too? open question)
- If a VxMark voter puts their headphones on before the poll worker selects the ballot style, they hear the content of the poll worker screen. 

https://votingworks.slack.com/archives/CJU9MSC6S/p1646357241268579

and 

https://votingworks.slack.com/archives/CJU9MSC6S/p1646405310055469

**Comment by adghayes** [comment]
Closing as the screen reader has been revamped and this may or may not be relevant. We are more explicit in our user design now about which strings are read and which are not. cc @kofi-q
