### ISSUE TITLE
VxMark copy needs update for use with VxScan

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1480]
We forgot to update the onscreen instructions for VxMark when we added the precinct scanner, so it still says to put the ballot in the ballot box instead of take it to the scanner. Eventually this should be configurable for the mode the system is used for, but for now everyone is using precinct scanners.

https://votingworks.slack.com/archives/CJU9MSC6S/p1646406298525299

**Comment by jamesturk** [comment]
Trying to knock out a few of these smaller ones.

Here's the current screen for context:

<img width="1215" alt="Screen Shot 2022-03-09 at 10 50 11 AM" src="https://user-images.githubusercontent.com/8034/157478113-a7ea9506-9e27-4de7-883f-e190c10bf8f9.png">

1. Should the graphic change too or are we OK with it as-is for now?  
2. New language just "Place your ballot in the scanner?"  Do we have language we typically use (e.g. VxScan?)?

**Comment by mcchilders** [comment]
1) yes - @beausmith do we have a generic scanner graphic? Where can that be found? 
2) We always want the instructions to be as plain-language as possible (hence avoiding product names like VxScan) - "place your ballot in the scanner" is fine by me, although since the scanner is in a different location (across the room, usually), we might want to say "take your ballot to the ballot scanner" and leave the instructions to insert it for the scanner screen?

**Comment by jamesturk** [comment]
@beausmith @mcchilders I looked at the existing SVGs  and unless I missed something this may be the best for now:  [./frontends/precinct-scanner/public/assets/insert-ballot.svg](https://github.com/votingworks/vxsuite/blob/main/frontends/precinct-scanner/public/assets/insert-ballot.svg)

**Comment by beausmith** [comment]
@jamesturk - I need to make a new graphic. There is another repo "assets" which has many graphics… and which I'm long overdue to push a massive commit to. 🙀
