### ISSUE TITLE
VxMark: Ensure laptop power cord does not come uplugged

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1481]
During m13a, the laptop power cord on VxMark came unplugged from the laptop (inside the foam) when users tried to plug the other end of the power cord into an outlet. 

See here: https://votingworks.slack.com/archives/CJU9MSC6S/p1646233916312989
and here: https://votingworks.slack.com/archives/CFSJEQ26N/p1646345902451019

**Comment by benadida** [comment]
Fixed by tying the cord around the foam, as per @adghayes
