### ISSUE TITLE
VxMark: Headphones may interfere with hearing aids

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1483]
Our headphones may cause interference with hearing aids. Voter with hearing aids complained that he was unable to hear the voice. Ultimately took off his hearing aids and his ability to understand the robotic voice dramatically improved. [@roe](https://votingworks.slack.com/team/U014XFVTG8P) mentioned that we may want to look into headphones with "t-coils".

See this Slack thread for context:
https://votingworks.slack.com/archives/CJU9MSC6S/p1646235558700779

Also may want to consider VVSG2 requirements if reevaluating headphones (need to sanitize, need to prevent sound from leaking etc.)

**Comment by mattroe** [comment]
Closing until we confirm / test with new hardware
