### ISSUE TITLE
VxMark: headphone volume control

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1484]
## Background

For any number of reasons, the headphone volume on the VxMark might be wrong. Right now, we don't provide any means of adjusting it. We should, and we have a button on the accessible controller that we can use.

## Expected Flow

- voter presses the single volume button on the accessible controller
- volume increases by a notch, with 9 levels from 20db to 100db in 10db increments
- on dispay, show "Volume 4/9" (in some kind of modal display that fades away after 3-4s.)
- audio interface says "volume set to 4 out of 9."
- if the volume is already at 9, then pressing the button cycles back to 1/9.

## Suggested Architecture

- do some calibration of volume on our headphones + hardware to see where 20db and 100db land.
- add `kiosk.volume.get()` and `kiosk.volume.set()` 
- intercept the appropriate function key that corresponds to the volume-button press and do the right thing using the APIs above.

**Comment by mattroe** [comment]
Relevant VVSG requirement for reference:
> 7.1-K – Audio settings
> 2. The default volume for each voting session is set between 60 and 70 dB SPL.
> 3. The volume is adjustable from a minimum of 20 dB SPL up to a maximum of 100 dB SPL, in increments no greater than 10 dB.

**Comment by adghayes** [comment]
I'm going to close this for now because we are meting _most_ of the requirements here. We're missing:
- Display feedback about audio level
- Decibel calibration:
> I don't have the volumes mapped to decibel levels. I'm yet quite sure how to do that, or if the choice of headphones affects that. But the VVSG range is, I think, an absolute maximum and minimum - not the maximum and minimum we have to use. We can't go outside of the range they specify. Because the VVSG maximum - 100dB - is equivalent to a jet plane taking off or a jackhammer. Perhaps I am misunderstanding something.

Since we are planning to revisit this to add a settings menu of sorts anyway, I am closing this issue and allowing future issues to be represented by other tickets. cc @mattroe @benadida
