### ISSUE TITLE
VxScan: Improve ballot insertion

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1486]
This is a longstanding issue, but m13a testers reported that it is still not working as well as we'd like, even with shelf improvements:
The biggest issue is inability to reliably insert the ballot and for the scanner to “catch it” initially without adjustment. This affected EOs, volunteers, and Vx staff. As Sara says “if it’s not exactly straight, it doesn’t like it”
See: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269468645499

**Comment by benadida** [comment]
will be part of the larger hardware redesign.
