### ISSUE TITLE
VxMark Automatic On/Off

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1487]
From m13a: "unless participants watched the video and knew where to go/how to position their finger, near universal inability to find the power button. Previous known issue but very obvious in user testing." Not necessarily something we want to make easy to find, though, since voters shouldn't find it.
See: https://votingworks.slack.com/archives/CJU9MSC6S/p1646269560249459

Beau's suggestion is to solve with automatic on/off, so pollworkers don't regularly have to find it at all:
- On when plugged into power
- Auto-off when not plugged in, battery is < 50%, and there not active user session.

**Comment by benadida** [comment]
given new hardware and training, not a serious problem, not going to fix this.
