### ISSUE TITLE
Placeholder: Overhaul VxAdmin UX

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1491]
Lots of user feedback from m13a about the UX in VxAdmin - leaving this card here so that we remember to go through it and rework.

Relevant threads: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1646332560422609
https://votingworks.slack.com/archives/CJU9MSC6S/p1646269792887069
https://votingworks.slack.com/archives/CJU9MSC6S/p1646269781719999
https://votingworks.slack.com/archives/CJU9MSC6S/p1646414482572169
https://votingworks.slack.com/archives/CJU9MSC6S/p1646405540778009

**Comment by benadida** [comment]
captured in the vxadmin spec, closing this ticket.
