### ISSUE TITLE
VxScan/VxMark: Consistent smartcard orientation 

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1493]
From m13a feedback:
"VxMark and VxScan card reader orientation needs to be consistent - yes, the backwards prompt helps but as one poll worker sarcastically said "makes sense that front would be back" - we need to pick a "front" and stick with it.  I still suggest that is easiest by flipping it on the VxMark and changing the card graphics."

See: https://votingworks.slack.com/archives/CJU9MSC6S/p1646405423298279

**Comment by mattroe** [comment]
Included as a requirement in new hardware prototypes
