### ISSUE TITLE
VxAdmin: when creating a card with PIN with keyboard, typing Enter should complete programming

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1494]
The keyboard can currently be used for typing the PIN itself, but then pressing enter does nothing, which requires clicking / touching the screen. Let's make "Enter" do the same thing as tapping/clicking the green button when programming a card with PIN.

**Comment by eventualbuddha** [comment]
Whoever does this should know that this is also a bug with essentially _all_ the modals.

**Comment by jamesturk** [comment]
Began cursory investigation of this, react-modal doesn't directly support onKeyPress but this ticket has a workaround: https://github.com/reactjs/react-modal/issues/184
