### ISSUE TITLE
NH: support ballots with bubbles on the right of the name

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1505]

**Comment by eventualbuddha** [comment]
Here's a [PDF](https://github.com/votingworks/vxsuite/files/8393517/election-d0696d9f5c-precinct-hudson-id-town-id-12101-precinct-id--style-card-number-54-English-live-absentee.pdf) that has the bubbles on the right and an annotated image showing where it found the contests & targets:

![election-d0696d9f5c-precinct-hudson-id-town-id-12101-precinct-id--style-card-number-54-English-live-absentee-p1-layout](https://user-images.githubusercontent.com/1938/161162806-377bf096-6c96-4692-a265-c09bf635741e.jpg)
