### ISSUE TITLE
write-in adjudication: determine flow, which machines, which exports, etc.

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1507]

**Comment by eventualbuddha** [comment]
This done with the writing of the [Demo Script](https://docs.google.com/document/d/1_mFGPv2W1epCWCAjQhaXvjj16Or3NUO0dBI0BN3vA2Y/edit?pli=1#heading=h.o4v829i6m73)?

**Comment by benadida** [comment]
> This done with the writing of the [Demo Script](https://docs.google.com/document/d/1_mFGPv2W1epCWCAjQhaXvjj16Or3NUO0dBI0BN3vA2Y/edit?pli=1#heading=h.o4v829i6m73)?

Yes!
