### ISSUE TITLE
Fix bug with Export Log File showing white screen 

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1518]
From Drew: "

VxAdmin: “Export Log File” button caused white, blank frozen screen. In order to continue using the application, the laptop had to be restarted. This can be replicated by clearing the election definition, rebooting the computer, and pressing the button. Loading an election definition will cause the button to start working properly, even if the election definition is removed (but the device is not restarted)."

**Comment by mattroe** [comment]
cannot repro
