### ISSUE TITLE
Loading an invalid/outdated election definition in VxMark results in a hung UI

### ISSUE THREAD

**Issue by jamesturk** [votingworks/vxsuite#1522]
## Description
When configuring a VxMark machine, if the admin card has an invalid election definition (in this case due to schema changes) the UI will get stuck on "Loading Election Definition..."

## Repro
1. Start the Smart Card service & VxMark services locally
2. When prompted to insert an admin card run `./mockCardReader.py enable --fixture fixtures/admin`
3. Click on "Load Election Definition"
4. See error message in console, but note UI will continue to display "Loading Election Definition from Admin Card..." until process is killed & restarted.

## Expected behavior

An error message of indicating a failure to load the election should be displayed visibly.

**Comment by mattroe** [comment]
Closing as this shouldn't impact users
