### ISSUE TITLE
ci: using deprecated Docker images

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1533]
## Description
We appear to be using at least one deprecated Docker convenience image. The link in the below image goes to https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034.

## Repro
1. Go to a CI test run, e.g. https://app.circleci.com/pipelines/github/votingworks/vxsuite/3127/workflows/99b313b9-7516-4d65-a743-fb4546e15e95/jobs/5255
2. See the deprecation warning.

## Expected behavior
We should see no warnings about this.

## Screenshots
<img width="806" alt="image" src="https://user-images.githubusercontent.com/1938/157534723-f6506892-7559-4fb4-b6c3-f948c2754fe7.png">

**Comment by adghayes** [comment]
Closed by #1735
