### ISSUE TITLE
Add a secure boot status indicator to tty2

### ISSUE THREAD

**Issue by umbernhard** [votingworks/vxsuite#1541]
Currently we display whether the machine was booted with dm-verity, but there is no way to tell if it was booted with Secure Boot in addition. Add another indicator to the tty2 menu to display this.

**Comment by umbernhard** [comment]
Ascertaining whether the machine is secure boot should be as easy as checking the file `/sys/firmware/efi/efivars/SecureBoot-*`. If it has content, than the machine is secure booted, otherwise it should be empty. I'm going to double check that this is right, but I'm pretty sure it will work.

**Comment by umbernhard** [comment]
Alternatively grep'ing `dmesg` should also work. It should have something like the following:
```
secureboot: Secure boot enabled
Kernel is locked down from EFI Secure Boot mode
```

**Comment by mattroe** [comment]
@umbernhard or @benadida did we implement this or another mechanism to confirm that secure boot is enabled?

**Comment by umbernhard** [comment]
Not as of yet. It's a fairly easy change that I can probably knock out in a few minutes.
