### ISSUE TITLE
flaky test: precinct-scanner: `admin and pollworker configuration`

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1545]
## Description
precinct-scanner `admin and pollworker configuration` test [appears to be flaky](https://app.circleci.com/pipelines/github/votingworks/vxsuite/3150/workflows/937c46e4-51c6-427e-9ac1-57bdc10e6a13/jobs/53020?invite=true#step-108-32).

## Repro
Run the build a sufficient number of times.

## Expected behavior
The test should pass consistently.

## Screenshots
<img width="790" alt="image" src="https://user-images.githubusercontent.com/1938/157767375-d198ff83-314e-46b1-a6cb-29ee913d2924.png">

**Comment by eventualbuddha** [comment]
Another instance: https://app.circleci.com/pipelines/github/votingworks/vxsuite/3541/workflows/e84b8bd6-a6c5-4af3-9c3e-a828b87dca47/jobs/63694?invite=true#step-108-237

**Comment by eventualbuddha** [comment]
Another instance: https://app.circleci.com/pipelines/github/votingworks/vxsuite/3544/workflows/267065c1-dcb6-43fa-8c47-79af990ed3b0/jobs/63766?invite=true#step-108-237

**Comment by carolinemodic** [comment]
I believe this has been fixed.
