### ISSUE TITLE
VxScan: "scanner not connected" error screen should provide more relevant action

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1549]
## Background

In VxScan, the single power cord powers both the tablet and the plustek scanning unit via an internal power strip. The tablet has a battery, so it can power up even if the power cord is not plugged in. The tablet is set up to power up automatically when it detects that the power cord has just been plugged in, but it can also power up via the power button. It's also possible to plug in, have the tablet automatically power up, and then unplug, and the tablet is still powered by its internal battery.

When the power cord is not connected to power (or a UPS), however, while the tablet may be functioning, the scanner obviously isn't. To the tablet, that looks like there is no scanner connected. Our error message in that case, "no scanner connected," is almost certainly wrong.

## Work to do

Right now it says:

```
Scanner not detected
Please ask a poll worker to connect the scanner
```

Instead it should say

```
Scanner not detected
Please ask a poll worker to check that the power cable is connected to an outlet
```

since that is the likely failure mode.

Stretch: if we detect that power *is* connected to the tablet, then the problem is with internal wiring, and the error screen can change to:

```
Scanner not detected
There is an internal connection problem, please report to election clerk
```

**Comment by jonahkagan** [comment]
Did you mean "Stretch: if we detect that power is connected to the _scanner_"

**Comment by benadida** [comment]
> Did you mean "Stretch: if we detect that power is connected to the _scanner_"?

No, we can't directly detect that power is connected to the scanner. We can only detect:
- can we see the scanner over USB?
- is there power going to the tablet?

So in the case that we can NOT see the scanner, but we DO have power to the tablet, that's an internal wiring problem which is a lot more serious than plugging the power cord into the outlet. Thus the different error screen when the power is connected to the *tablet* but we still can't see the scanner over USB.

**Comment by jonahkagan** [comment]
Why would not having the power cord plugged into the tablet make us unable to see the scanner though?

**Comment by eventualbuddha** [comment]
"No power to tablet" can mean:
1. power cable to tablet is not connected
2. power cable to whole VxScan unit is not connected

"Scanner not detected" can mean:
1. power cable to scanner is not connected
2. power cable to whole VxScan unit is not connected

So if the tablet _does_ have power, then the power cables to the tablet and to the whole VxScan unit are both connected. If that is true _and_ the scanner is not detected, then it must be the first cause: "power cable to scanner is not connected". This is the "internal wiring problem which is a lot more serious than plugging the power cord into the outlet" that @benadida  mentioned.

Does that make sense?

**Comment by jonahkagan** [comment]
Ah, I'm inferring that there's some sort of power strip inside VxScan that the tablet and scanner are both connected to. Is that right? If so, this all makes more sense.
