### ISSUE TITLE
VxAdmin: Test Deck Expected Results Report should have identical layout to normal tally report

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1552]
Right now, three visible differences between the Test Deck Expected Results Tally Report and a real tally report:
- the "Ballots By Voting Method" table is missing in the expected results
- the font size appears to be a tad bigger for Expected vs. real.
- the title bar is different, bigger font, on expected.

We should make Expected look like the current real tally report, with the only difference being in the words in the title of the report.

**Comment by mattroe** [comment]
@adghayes to confirm if this is still an issue

**Comment by adghayes** [comment]
The font size was fixed by a previous PR but the other two bullets are still a problem, will tackle this.

[testTallyReport.pdf](https://github.com/votingworks/vxsuite/files/9455376/testTallyReport.pdf)
[tallyReport.pdf](https://github.com/votingworks/vxsuite/files/9455377/tallyReport.pdf)
