### ISSUE TITLE
VxScan: remove old HMPB QR code formats

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1559]
## Summary
When we originally were building the VotingWorks hand-marked paper ballot design, we went through a couple iterations of what the QR code data should be. Originally it was just a URL with query params for the metadata such as ballot style. Due to concerns about size, we replaced this with a binary-encoded-as-base64 QR code. However, the code supporting the URL-style QR codes lingers.

Similarly, for BMD ballots we previously built the QR codes using raw binary data. This data would be corrupted sometimes when reading them with zbar (via qrdetect), so we encoded the raw binary data using base64. However, the code supporting the non-base64 QR codes lingers.

We should remove support for both of these outdated formats. However, some of our fixtures use them, so this task must be completed after #1524.

## Tasks
- [ ] remove URL-style HMPB QR code support
- [ ] remove raw binary BMD QR code support

**Comment by carolinemodic** [comment]
@jonahkagan is this done with your cleanup?

**Comment by jonahkagan** [comment]
Just peeked through the code. I don't see anything related to URL-encoded data. I see [one function](https://github.com/votingworks/vxsuite/blob/7668dbe9b6d37da522aec10d8634cfb33731cc85/libs/ballot-interpreter/src/bmd/utils/qrcode.ts#L24-L42) that still has a branch supporting binary decoding. I'm not sure if this is what @eventualbuddha was referring to.

**Comment by eventualbuddha** [comment]
I cleaned most of this up earlier this year. I think we can close this as anything left will be naturally removed as we transition ballot design.
