### ISSUE TITLE
The orientation of the accessible controller was confusing to people

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1564]
The orientation of the accessible controller was confusing to people. Maybe it was just how we put it down on the table but everyone kept picking it up sideways (90 degrees counter clockwise from the proper orientation)

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1646764149375289?thread_ts=1646764149.375289&cid=CJU9MSC6S

**Comment by mattroe** [comment]
We are exploring other a11y controllers as part of new hardware
