### ISSUE TITLE
Splash screen for production images is ugly

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1569]
Splash screen for production images is ugly. It should display the VotingWorks  logo. This should be configurable via [Plymouth](https://www.freedesktop.org/wiki/Software/Plymouth/)

Issue automatically created from slack feedback reported by bernhard 
https://votingworks.slack.com/archives/CJU9MSC6S/p1647307222114329

**Comment by umbernhard** [comment]
closed by votingworks/vxsuite-complete-system#160
