### ISSUE TITLE
VxAdmin: better looking file picker for election definition

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1572]
The default OS file picker is small and ugly. We should probably build our own that shows just the files on the USB stick anyways.

**Comment by adghayes** [comment]
Noting that we now have a non-file-picker path for zip files found at the root of the inserted drive. Leaving this open for now until we confirm that's enough.

**Comment by arsalansufi** [comment]
Yeah let's close this issue! In favor of https://github.com/votingworks/vxsuite/issues/5673

This issue is from before we added the nice in-app file picker
