### ISSUE TITLE
VxAdmin: "Print Test Deck" button should show number of ballots about to be printed

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1573]
## Summary

In VxMark, the final "print" button says "Print 3 ballots", which is super useful when testing and just in terms of expectation setting for how much paper you're going to need. We should have the same on the VxAdmin button, where right now it's a mystery how large the test deck will be.

**Comment by adghayes** [comment]
No test deck in VxAdmin, this is no longer relevant.
