### ISSUE TITLE
VxScan: "Scanner Not Detected" flashes on and off a couple of times when plustek is turned on

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1574]
It eventually lands on the right thing, which is that the scanner is detected, but for a few seconds it's confusing that it detects it, then stops detecting it, then starts again.

**Comment by jonahkagan** [comment]
I noticed this behavior in my VM but it didn't seem to happen when I tried it on a laptop. I traced it a bit and it seems like the device subscription we get from kiosk-browser has a blip.

**Comment by mattroe** [comment]
Closing as I haven't reproduced this behavior on the new precinct scanner state machine.
