### ISSUE TITLE
VxScan: move some configuration functions to sysadmin screen

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1578]
Admin screen is only accessible once machine is configured. However, we may want to do things like calibrate scanner, set date/time, etc. before an election is loaded. 

This could be part of a broader refactor of the admin flows on VxScan, where we think about how to load the data as part of the admin screen, not as a special "plug in the USB stick" one-off flow.

**Comment by adghayes** [comment]
Some functions have been moved to Sys. Admin, some are no longer relevant, closing.
