### ISSUE TITLE
Have USB writes & ejects actually take the appropriate amount of time, and guarantee removal safety by the end of ejecting

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1583]
## Summary
Previously we've just naively waited for 10seconds when ejecting usbs to make sure its safe to remove, this may be too much time or not enough time depending on the circumstance. There are some different ideas of how to solve this. 

One idea from @eventualbuddha : 

Sometimes we write to a USB drive and then unmount it, but we don't have a good way of knowing when it's safe to remove (i.e. the writes have been flushed). This may provide a clue how to do it in VxSuite: `watch -d grep -e Dirty: -e Writeback: /proc/meminfo`.

Originally posted by @umbernhard in [#tools](https://votingworks.slack.com/archives/CG1ACPNSZ/p1647364150181119):
> [@ben](https://votingworks.slack.com/team/UE87W5HHC) [@drew](https://votingworks.slack.com/team/U01S8KFEJ75) (and anyone else who has this problem): if you're stuck watching a USB eject waiting for data to finish syncing, you can use this one liner to monitor progress: `watch -d grep -e Dirty: -e Writeback: /proc/meminfo`
> as soon as the Dirty value gets close to 0 it's good to go (you'll still get an OS notification too, but)

From @adghayes 
We could use this “watching” approach or we could unmount by triggering sync and then pumount every time we unmount. The latter seems simpler to me, and is how I was thinking of https://github.com/votingworks/vxsuite/issues/2248.

**Comment by carolinemodic** [comment]
@adghayes Did our recent changes to exec cover this?

**Comment by adghayes** [comment]
No, changes to exec and adding of syncUsbDrive didn’t touch this. We could use this “watching” approach or we could unmount by triggering sync and then pumount every time we unmount.

**Comment by adghayes** [comment]
Closing #2248 has resolved this issue. @carolinemodic @eventualbuddha please re-open if you disagree!
