### ISSUE TITLE
VxAdmin: super-sample ballot

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1594]
*Superset sample ballot* - request for VxAdmin to produce a sample ballot that includes every contest across all ballot styles for sharing with the media like the current SEMS superset/master ballot that is produced: https://www.sos.ms.gov/content/documents/elections/FINAL%202020%20Sample%20GE%20Ballot%20with%20Flag.pdf

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/CJU9MSC6S/p1646269768529229?thread_ts=1646269768.529229&cid=CJU9MSC6S

**Comment by mattroe** [comment]
specification discussion/decision: https://votingworks.slack.com/archives/CEL6D3GAD/p1660238262435559
