### ISSUE TITLE
VxAdmin: count of CVRs in manually entered multi-seat contests has a buggy edge case

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1607]
## Description
When entering manual data for a multi-seat contest and nothing else, the calculation of number of CVRs is wrong.

## Repro
1. in VxAdmin
2. load an election with a multi-seat contest, say 2021-primaries county 73.
3. enter manually entered data with just a "3" in one of the multi-seat candidate numbers.
4. back to top-level tally screen, note that it counts that as only 1 CVR.

## Expected behavior
Because it's 3 for a single candidate, as opposed to 1/1/1 across 3 candidates, it really should be 3 CVRs, cause you can't vote twice for the same candidate.

**Comment by adghayes** [comment]
We now have users enter the ballot count for each contest themselves, so shouldn't have these weird cases where we're generating it ourselves. We don't check for this case specifically, though. Closing.
