### ISSUE TITLE
VxAdmin: timestamps on files appear to be inconsistent wrt timezone

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1608]
## Description
Timestamps on files on USB sticks, which show up when that USB stick is inserted into a mac / pc, appear to be inconsistent wrt timezone.

Specifically:
- single ballot PDF looks like it's saved as UTC without timezone
- tabulation reports and SEMS file export appear to be local time but also without timezone / or at least they're an hour earlier than they should be.

## Repro
1. save a ballot PDF
2. save a tally report PDF
3. go look at files on a mac/pc

**Comment by adghayes** [comment]
Noting that this was fixed for log files by @kofi-q (https://github.com/votingworks/vxsuite/pull/5548) but I'm not sure if it's been fixed in the general case. @arsalansufi do you know?

**Comment by arsalansufi** [comment]
I think we're fine to close this out @adghayes - @kofi-q found that CVR exports were already using a timezone-aware function, and he just had to update log exports to use the same function. I'm not sure if there are any other exports to update, but those are the two most important anyway. We can open new issues for any new issues we identify.
