### ISSUE TITLE
Upgrade to cypress v10.2.0

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1615]

**Comment by eventualbuddha** [comment]
I tried the `Dockerfile` in this comment: https://github.com/cypress-io/cypress/issues/4478#issuecomment-1068916303. It did successfully build, though it's a newer version of cypress than we're using. In theory we can build an older version using something similar, or update our cypress version to use the latest. The question then remains how we want to set this up for local development. Could just be a build script that installs and configures it, though that's a decent amount of work.

**Comment by carolinemodic** [comment]
This is solved by https://github.com/cypress-io/cypress/pull/22252, which I have tested locally, you can check out the pre-release binary following the steps in that PR. It will walk you through some automated conversion steps to upgrade to cypress v10 in order to work with the most recent code. If you are running in election-manager there are other issues with the plugins file where you have to change the imports to requires...

**Comment by carolinemodic** [comment]
This is now released as of cypress v10.2.0
