### ISSUE TITLE
Make kiosk-browser easier to develop on with mock hardware

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1616]
Today when you are using kiosk-browser even if you are using the mock card reader or mock scanner, it will enforce in the frontend apps that you have the right hardware connected. This can be really annoying when trying to test and develop one small thing that may be unrelated to these components. We should make kiosk-browser have ENV variables or some flag to mock out that you have those pieces of hardware connected. Stretch goal would be to make a mock usb drive that also works nicely with this.

**Comment by adghayes** [comment]
For card reader case, the check can be overriden with `REACT_APP_VX_DISABLE_CARD_READER_CHECK=1` after @benadida merged #2075. In your eyes, is that sufficient? I think it would be slicker to have the check tied to whether we are mocking in the card service or not. To do that, however, we'd have to make the app aware of whether the card service was in mock state or not, which would probably mean just extending the `card/read` API and passing that state to the frontend. That's pretty doable IMO, but would touch a number of things.

Thinking about the other cases...

**Comment by adghayes** [comment]
I think with the scanner case, it would be the same. It could either be an environment variable like #2075 or we could pass the mock vs. no mock state to the frontend, which would require touching scan service, but would probably be a better experience and make more sense.

The weird part is that in prod we'd be constantly passing "not a mock!" in all the requests but that's OK.

**Comment by adghayes** [comment]
Played around with this for the card reader case to see how it might work for `precinct-scanner`. Adds a bit of complexity, I'm not confident it's worth it, but I already appreciate playing around with it in `kiosk-browser`.

**Comment by carolinemodic** [comment]
Yeah I feel like automatically detecting it probably adds more complexity then its worth. For the scanner case there have also been times where I'm not actually needing to scan anything and don't set up the mock scanner but need to test something in the admin menu or the UI of the main screen and don't want to have to connect the scanner so I feel like it would be more flexible to just have an environment variable. I think some of our apps block on a no printer connected screen too, which we don't have a way to mock like this (maybe just VxMark does that?). 

It's interesting to me that Ben implemented the card reader variable in vxsuite, I guess I had imagined it would be set in kiosk-browser and kiosk-browser would pretend to have found that device but maybe vxsuite makes more sense, and that is where the other environment variables are managed. If these are all implemented as environment variables in vxsuite this might overlap some with https://github.com/votingworks/vxsuite/issues/2442 as I think its kind of confusing right now to know which variables exist (I didn't know Ben had added this card reader one) and it feels like for this case especially there should be an easy intuitive way to tell the app that you are not using any real hardware, or to not have to think about this every time you run things. 

I would recommend posting in slack and getting some of the other engineers thoughts as well as what would be most useful for them.

**Comment by adghayes** [comment]
Just updating status on this ticket. In terms of mocking:

- Card Reader =  👍 , using our regular mocking and the `REACT_APP_VX_DISABLE_CARD_READER_CHECK` environment variable. Will be changed / upended by Java Card work.
- Plustek Scanner = 😐, using `MOCK_SCANNER_HTTP=1` allows us to develop without a scanner. I'm not sure how good our fixtures are for actually mocking scanning when using the mock, but the main problem is just being able to develop without a scanner.
- Printer = 👎, if you want to develop in kiosk browser you need a printer attached for `MarkPrint` mode. I think this is OK for now. 

Generally, I don't think there's a lot to prioritize here while we still have some hardware questions up in the air.

**Comment by carolinemodic** [comment]
Moving to low priority based on update

**Comment by adghayes** [comment]
We have some better mocks than when this was originally made, and also our mocking is not related to `kiosk-browser` any more - anything going through `kiosk-browser` should just be moved to the backend. Closing because this is too nebulous, even though we need better mocking for some components (e.g. scanner) still.
