### ISSUE TITLE
flaky test: precinct-scanner `App shows warning message to connect to power when disconnected`

### ISSUE THREAD

**Issue by taravancil** [votingworks/vxsuite#1634]
## Description

In `app_unhappy_paths.test.tsx`, the `App shows warning message to connect to power when disconnected` test appears to be flaky. In this [failed build](https://app.circleci.com/pipelines/github/votingworks/vxsuite/3317/workflows/db72b585-a4d5-4794-b1ef-4b67ba42d712/jobs/57496), the text `Yes, Open the Polls` could not be found.

## Repro
Run the build a sufficient number of times.

## Expected behavior
The test should pass consistently.

**Comment by carolinemodic** [comment]
I believe this has been solved.
