### ISSUE TITLE
VxScan: ballot with 1 blank page and 1 overvoted page results in the blank ballot error message

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1638]
## Description
See repro

## Repro
Print a HMPB from the electionMinimalExhaustiveSample, ballot style 2f: https://github.com/votingworks/vxsuite/blob/main/libs/fixtures/src/data/electionMinimalExhaustiveSample/electionMinimalExhaustiveSample.json#L211 
Mark the front page with an overvote, and leave the back page contest blank
Scan with VxScan
See that it tells you you have a blank ballot

## Expected behavior
Expected to see the you have an overvoted ballot screen. Note that it IS still counting the overvotes, if you tabulate the ballot as is there ARE overvotes on the report. Also if you mark the back page then the overvote screen will come up properly. 

I think this bug does NOT repro on VxCentralScan

Potentially related to the solution: https://github.com/votingworks/vxsuite/issues/1421

**Comment by carolinemodic** [comment]
Note this does not seem to happen on VxCentralScan, right now all the logic about how to adjudicate a ballot is super complicated and spread out between VxScan frontend, VxCentralScan frontend, and the scanning service backend. We should probably just centralize everything in the scanning service backend and have that be super well tested. See https://github.com/votingworks/vxsuite/issues/1421 for a ticket for that refactor based on a previous, similar bug we encountered for the mock election.

**Comment by mattroe** [comment]
Putting this on the NH demo hit list as a nice-to-have because this just confused me again in testing!

**Comment by mattroe** [comment]
Just writing another comment about much I hate this issue

**Comment by mattroe** [comment]
Just writing another comment about much I hate this issue
