### ISSUE TITLE
Upgrade TypeScript

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1661]
## Summary
We're on TypeScript 4.3.5, and the latest is 4.6.3. We're a bit out of date. We should upgrade.

## Requirements
- Possibly upgrade related packages such as `ts-jest`, `@typescript-eslint/*`, `react-scripts`, etc.
- Decide whether we upgrade all packages at once or one at a time, probably starting with the libraries.

## Non-Requirements
- Adopt new TypeScript features, options, or syntax. We should wait to do that until after the upgrade. For any new breaking changes that apply by default, see if we can opt out of them for now (e.g. `catch` error bindings being `unknown` instead of `any`).

## Tasks
- [ ] upgrade TypeScript

**Comment by carolinemodic** [comment]
@eventualbuddha did we do this in the node upgrade or is this still pending?

**Comment by eventualbuddha** [comment]
It was done in https://github.com/votingworks/vxsuite/pull/1752.
