### ISSUE TITLE
VxScan: plustek driver – figure out which version we're using in prod and fix any lingering issues

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1662]
The latest version of the plustek driver seems to crash fairly regularly, thus why we're using a slightly older version in production.

The latest version is meant to offer an extra feature we do want, which is detection of a sheet of paper at the front and, in that case, refusing to accept an already-scanned-but-hanging-out-the-back sheet. This is to prevent the rare but still important situation where, if a ballot has been scanned and is being evaluated, and a second sheet is placed at the scanner intake, then accepting the first ballot will automatically ingest the second ballot without scanning it.

We have only seen this in testing, but it could happen in production when a ballot spans multiple sheets and the voter is anxious to scan their second sheet.

So, what we need to do:
- repro the crashes
- work with plustek to understand how to fix them
- eventually actually take into account the extra signal that a paper is present at intake so we can warn on screen and say "hold on, we're not done scanning this sheet, please remove the sheet you're holding".

**Comment by carolinemodic** [comment]
The new driver also introduces new error codes we will need to update our code to handle. To date we have used the no-double-feed driver, in order to test with that you need to check out the no-double-feed branch of plustekctl and rebuild/reinstall plustek.
