### ISSUE TITLE
"Export Ballot Package" Modal should let you download the package when running through chrome

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1680]
You should be able to run VxAdmin and port to localhost on chrome and download the ballot package locally without needing to use a real usb drive. The "save as" button should appear like in other modals instead of the hidden behavior to double click the usb button, and there is a bug that makes double clicking the usb button not work. 

Context: https://votingworks.slack.com/archives/CEL6D3GAD/p1649692662788759

**Comment by arsalansufi** [comment]
From Ben in Slack:

> quick clarification: I don't believe we can do export ballot package in just chrome, because it relies on the PDF rendering abilities of kiosk-browser. Now, once the ballot package stops including PDFs, once it's just an election definition, then yeah the flows should work in Chrome, but until then I don't think it's possible

**Comment by eventualbuddha** [comment]
@benadida is correct, we can't do this as long as we're rendering PDFs for the ballot package.

**Comment by carolinemodic** [comment]
This is impossible so closing but we should prioritize just configuring the scanners from an election definition.
