### ISSUE TITLE
Supported Scanners

### ISSUE THREAD

**Issue by openrecordsx** [votingworks/vxsuite#1703]
Are the Plustek VTM 300 or Fujitsu fi-7160 the required supported scanners?

We have a Brother ADS 2200 connected by USB.  OS is Ubuntu 20.04.
Scanner successfully runs simple-scan and delivers an image.
When running vxsuite we get -  Error: "Card Reader Not Detected"

**Comment by eventualbuddha** [comment]
Try loading the app in Chrome rather than kiosk-browser. We check that certain hardware devices are connected and present an error when they're not found. In Chrome we can't do that so we assume the best.
