### ISSUE TITLE
VxScan: bug that caused #flare-m13b-vxscan-freeze

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1704]

**Comment by carolinemodic** [comment]
See #flare-m13b-vxscan-freeze for a lot of historical context here. 

Essentially there are two problems going on. 

First problem is that the plustek driver process randomly crashes/seg faults on us and we don't know why. Plustek was surprised to hear about this and claims they have never seen this themself or had another customer complain. Ben wrote a small c-script that wraps the plustek driver to mimick scanning without all of the other usb polling and other things we do. AFAICT we can NOT reproduce the seg faults using this script, implying to me that something we are doing with usb polling or something else is causing a race condition that is causing plustek to crash. If we can stop the seg faults all together we can solve this ticket for m14. 

Second problem, if we can not solve the first problem, is that if the plustek process crashes immediately after a ballot is scanned in, before it is accepted, while the image data is being transferred over the usb, then it gets into a state where on ubuntu it can reconnect fine after the crash but on debian it can not and this is why we rolled back to ubuntu for m13b. So another solution is to figure out what is different in debian that is making us unable to reconnect in this case, debian/ubuntu do use subtly different versions of the libusb libraries. 

We have reproduced the bug on the no-double-feed driver we were using in m13b along with more recent drivers plustek has sent us, but I don't believe we have tested the most recent recent driver yet (for problem 2), but we have no reason to believe it would solve the problems we are seeing.

**Comment by carolinemodic** [comment]
My gut recommendation on next step is to keep pursuing solving problem 1 and see if we can figure out if there is something we are doing that is causing the seg faults that we could ... avoid doing lol.

**Comment by benadida** [comment]
A this point, the best we know is that it's a race condition in the plustek library that causes different outcomes in Ubuntu 18 and Debian 11. Debian 11 is a hard crash of the scanner that can only be resolved by power-cycling it or unplugging the plustek. Ubuntu 18 crashes the client but is able to reconnect immediately.

We did make progress with Plustek 2.4.17 that no longer spits out the ballot out the back on power-cycle. Which means that this error would be recoverable even on Debian. But power cycling every 50-100 ballots is not a great experience.

For m14, we're going to use Ubuntu18 and look for mitigations, as well as some debugging info for later fixes.

We should explore:
- reconnecting the plustek client every ballot
- on plustekctl crash right after a scan, just rescan automatically.
