### ISSUE TITLE
Investigate if we can find working wifi drivers for all of our hardware

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1705]
Current status
- Surface Go 2 / 3 - Works on Ubuntu 18.05+ but not 18.04, does not work on Debian
- Lenovo Thinkpads - Works on Ubuntu, mixed success on Debian it appears different models have different wifi cards
- Lenovo Flexpads - Works on Ubuntu, does not work out of the box on Debian but appears to work with the firmware blob previously provided by @umbernhard

**Comment by umbernhard** [comment]
Adding a bit more context: the Thinkpads either have an AX200 card or an AX210 card. The AX200 card is supported, while the 210 needs extra firmware.

**Comment by umbernhard** [comment]
This driver seems to make the surface go's wifi work with Debian: https://www.reddit.com/r/SurfaceLinux/comments/9t53gq/wifi_fixed_on_surface_go_ubuntu_1810/

**Comment by umbernhard** [comment]
note that this driver can be installed in a VM before flashing, which should make it a lot easier to distribute development images to folks.

**Comment by benadida** [comment]
given VxDev working on all hardware, is this now done?

**Comment by carolinemodic** [comment]
Yes now that we've figured out Roe's issue this is done!
