### ISSUE TITLE
`scan`: improve performance of `importer.getStatus()`

### ISSUE THREAD

**Issue by taravancil** [votingworks/vxsuite#1709]
## Summary
`importer.getStatus()` makes several calls that hit the db, and is called quite frequently. As Ben called out in #1580, we should investigate if we can improve the perf of any/all of these status calls.

> we're hammering sqlite on every status call which happens often, so doing a number of SQL queries every time gives me pause... it's not that much data so it's probably fine, but maybe worth a followup performance test ticket? (Also maybe worth an index on the timestamps in the sheets table.)

**Comment by carolinemodic** [comment]
@eventualbuddha @jonahkagan Not sure if we touched this as part of the more recent refactor of the scan service, is this ticket still relevant?

**Comment by jonahkagan** [comment]
The precinct scanner no longer uses `importer.getStatus`, but the central scanner does. I'm not sure if that resolves the original concern here.

**Comment by jonahkagan** [comment]
And the precinct scanner has its own status endpoint that does make similar db queries, so actually I would say this is still relevant there as well.
