### ISSUE TITLE
Update `frontend/election-manager/.nvmrc` to 16

### ISSUE THREAD

**Issue by taravancil** [votingworks/vxsuite#1729]
(Or delete it? Unclear to me yet how we're using using `.nvmrc` vs `.node-version`)

**Comment by eventualbuddha** [comment]
I don't think we advocate for any particular solution here. `.node-version` is probably the more generic of these node-specific ones, though tools other than `nvm` probably support `.nvmrc` to some degree. The minimal change is just to update the root `.node-version` to `16.14.2`.

**Comment by eventualbuddha** [comment]
Closed by #1731
