### ISSUE TITLE
Simplify the work of exporting all data needed at the end of an election

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1743]
Currently, election admins need to back up:
- VxAdmin results file
- VxAdmin tally reports
- VxAdmin log
- VxCentralScan CVR files
- VxCentralScan backup files
- VxCentralScan log
- VxScan CVR files
- VxScan backup files

That's a lot. Can we make this easier?

@ginvdr adds:

> At a minimum, I think just having the back up files also auto save on VxScan will save a huge chunk of work. If they didn't need those, they shouldn't have to do anything extra as long as they retained the election night USBs correctly

**Comment by mattroe** [comment]
closing until we receive feedback on the export process in m14
