### ISSUE TITLE
VxCentralScan Reorganize Advanced Screen

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1744]
The admin screen in VxCentralScan has had a lot of different functions added to it over time without a holistic strategy on how it should be laid out or organized. 

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/CJU9MSC6S/p1651082417519689?thread_ts=1651082417.519689&cid=CJU9MSC6S

**Comment by benadida** [comment]
we removed the ellipses, so we actually addressed the issue.
