### ISSUE TITLE
VxAdmin: USB formatting function to wipe/properly format a USB drive

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1746]
vxadmin feature request: a USB formatting function to wipe/properly format a USB drive

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/CJU9MSC6S/p1651095069214139

**Comment by mattroe** [comment]
The scope of this feature may now increase given the FAT size backup restriction we recently discovered. needs discussion

**Comment by mattroe** [comment]
- FAT formatting
- Definite use case for a superadmin, but could also be beneficial to an election manager role potentially. Given that cards are programmed only by superadmin, it is reasonable to restrict this to superadmin where the `Settings` tab is exposed as that is the most logical UI location for the `Format` feature.

Suggested implementation:
- A *Format USB* header is available within the `Settings` tab.
- One button is shown that is by default disabled when no usb is inserted with `No USB` shown.
- When USB inserted, the button state changes to `Format USB` and is enabled.
- Clicking `Format USB` shows a confirmation modal warning the user that all data will be deleted on the USB.
- After formatting, button state stays enabled but reads `Eject USB`.
- After ejecting, button state returns to disabled and reads `No USB` (like other USB functionality today)

**Comment by adghayes** [comment]
@mattroe @carolinemodic please take a look. @mattroe this is a little different from the flow you described, I improvised based on what I think might be smoother if you're formatting a bunch of USBs at once.

https://user-images.githubusercontent.com/37960853/211074225-87940e75-eba6-4c36-aeae-4abf6ade9e5c.mov

**Comment by mattroe** [comment]
@adghayes LGTM overall.

Two small things:
1. I assume the settings experience / format function access is the same in the non-configured VxAdmin state?
2. On the Format USB modal, I think you can remove the first sentence of copy and replace with: `Warning: formatting will delete all files on the USB drive."

**Comment by adghayes** [comment]
@mattroe can you clarify your suggestion? Currently there's two Format USB stages - the initial one and the confirm one. 

Initial Text:
> Format the inserted USB drive to be compatible with VotingWorks devices? Formatting will delete any files currently saved to the USB drive.

Confirm Text:
> Warning: Any files currently on the USB drive will be deleted. Make sure you have backed up any important files.

Are you suggesting having only one confirm rather than two? Or are you suggesting just editing the first one?

**Comment by mattroe** [comment]
Sorry @adghayes I clearly missed the two-stage modal. Here's my nit copy suggestion in that case:

Initial:
> The inserted USB drive format is not VotingWorks compatible. Would you like to format the USB drive?

Confirm:
> Warning: formatting will delete all files on the USB drive. Back up USB drive files before formatting.

Initial (if trivial to specify per slack thread):
> The inserted USB drive is VotingWorks compatible. Would you like to format the USB drive?
