### ISSUE TITLE
Remove ellipsis in various button components 

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1748]
We have inconsistent uses of ellipses through the product, notably in the VxCentralScan admin screen, and should remove them for consistency and simplicity. 

https://votingworks.slack.com/archives/CJU9MSC6S/p1651082417519689

**Comment by adghayes** [comment]
@beausmith some things make sense to keep ellipses - does this seem like an appropriate list of exceptions?

- Temporary status button text (e.g. "Exporting...")
- "Save As..." buttons
- "Select a precinct for this device..." dropdown in VxMark
- "Select File..." buttons

I'm not sure about the last one. I drafted #1804 if you prefer to take a look.
