### ISSUE TITLE
flaky test: `test-integration-testing-election-manager` Tallies for candidate contests compute end to end as expected

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1749]
[<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1938/165813001-75429a54-36b2-480b-b466-b5f3c118d4fd.png">](https://app.circleci.com/pipelines/github/votingworks/vxsuite/3659/workflows/63389bb8-17a6-4a3f-bd22-ecb36671118a/jobs/66993?invite=true#step-110-167)

**Comment by eventualbuddha** [comment]
Another instance: https://app.circleci.com/pipelines/github/votingworks/vxsuite/3668/workflows/848bdffc-1d0a-49cc-8d30-de6a76ff73ab/jobs/67225

**Comment by eventualbuddha** [comment]
Another instance: https://app.circleci.com/pipelines/github/votingworks/vxsuite/3668/workflows/dbf978ff-6802-431a-978c-eae5696668bf/jobs/67253?invite=true#step-110-167

**Comment by jonahkagan** [comment]
Another: https://app.circleci.com/pipelines/github/votingworks/vxsuite/5129/workflows/588c4039-eecf-467a-bc91-dd127481811e/jobs/112477
