### ISSUE TITLE
Implement CDF for CVR Exports

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1756]
Prior Research: https://docs.google.com/document/d/1eVHUmlnY7EgQErcZ3eMSzJm9j8mip8P1JONIuzj5e3E/edit#heading=h.6frdjxw3ogy5 

- [x] https://github.com/votingworks/vxsuite/issues/1240
- [x] https://github.com/votingworks/vxsuite/issues/1242
- [x] https://github.com/votingworks/vxsuite/issues/1241
- [ ] #1760

**Comment by adghayes** [comment]
Closed by #3283.
