### ISSUE TITLE
lint: enable `@typescript-eslint/require-await`

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1759]
We use `async` in places where it's not needed. We should consider enabling `@typescript-eslint/require-await` to disallow such uses of `async`. Looking into this a bit, we seem to have a few places where we use `async` without an `await` where we cannot simply remove the `async`:
1. **Implementing an interface:** If the method requires returning `Promise<…>`, but we don't actually need to `await` anything (such as in `MemoryStorage`), we've used `async` functions as a convenient way to wrap the return value in a `Promise`. The alternative is to explicitly use `return Promise.resolve(…)`. I'm not sure that's actually better.
1. **Forcing a `process.nextTick`:** Sometimes we need to wait in a test, and making something `async` that doesn't really need to be can force it to wait for the next tick, which _is_ needed when async operations happen as a result of e.g. `fireEvent.click`.

**Comment by jonahkagan** [comment]
1. Seems like a good case for an eslint ignore
2. I would probably convert these to use Testing Library's `findBy...` queries which are async
