### ISSUE TITLE
VxScan: undervote detection for MS

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1769]
## Background

We've learned that, in Mississippi, the requirement is for the precinct scanner to initially reject any ballot with even a single undervoted contest. While this is surprising and doesn't match other states, we need to support this.

First, we should confirm that this is truly a requirement. Then, if so, let's build it.

## Desired Flow

A ballot with one or more undervoted contests should be *held in the back of the scanner* and present a warning screen listing the undervoted contests. A button to "count as is" should appear very prominently, large target, likely centered on screen. If tapped, a modal confirmation should be presented, with the message:

"Please confirm that you would like this ballot counted as is, with undervotes for X, Y, and Z."

A second button to "return ballot" (wording TBD) should be a sibling to the "count as is" option. 

For discussion: is there a primary button? Button colors? etc.

## Tasks

- [ ] new undervote warning screen and behavior
- [ ] change default in SEMS conversion for Ms to reject undervotes by default in precinct scanning

## Non-Tasks

no change to central scanning, this is about second-chance voting only.

**Comment by eventualbuddha** [comment]
> My main concern now about implementing this feature is the significantly increased likelihood of Plustek failure by increasing the probability of ejection failure.

We could revisit the "don't eject the ballot when reviewing" work we'd done a while back.

**Comment by mattroe** [comment]
@jonahkagan actually reopening as this wasn't merged. you get to click it :)

**Comment by jonahkagan** [comment]
Ok it's merged now. Wanna try it out and see if you want to revise anything before we call it done?

**Comment by mattroe** [comment]
@jonahkagan will play with this next time I image my VxScan back into dev mode as I'm currently testing VxScan with locked down images for flare debugging.

**Comment by mattroe** [comment]
We can mark this as done for now and I'll reopen if I see an issue in further testing.

**Comment by mattroe** [comment]
@jonahkagan FYI just noticed this while testing undervote detection: https://github.com/votingworks/vxsuite/issues/2230

It doesn't really matter in practice as we convey the same information to the voter either way, but was unexpected to me.
