### ISSUE TITLE
store ballot images without a trace of timestamp/order

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#181]
VVSG 1.1 Section 2.4.4

**Comment by eventualbuddha** [comment]
How? Does this mean we can’t do on screen adjudication with 1.1?

**Comment by benadida** [comment]
I think I didn't think this one through when I added the ticket: I don't think there's any issue about timestamp in a central count situation. I'll confirm.

**Comment by adghayes** [comment]
We are comfortable with our timestamp strategy, so I am closing this. For central scanning, it does not matter. For precinct scanning, the timestamps on disk are protected by multiple layers of security. The timestamps in the exported CVR images are protected by random copying of files to mix up timestamps. See t[he relevant section of the TDP](https://docs.voting.works/vxsuite-tdp-v4/system-security-auditing-and-logging/system-security-architecture/artifact-authentication/preserving-voter-privacy) for details.
