### ISSUE TITLE
Update type or rename `<Main>` component's `maxWidth` prop

### ISSUE THREAD

**Issue by taravancil** [votingworks/vxsuite#1813]
## Summary
The `Main` component has a boolean prop `maxWidth` that should probably either be a number, or renamed to `maximizeWidth` as suggested by @eventualbuddha. https://github.com/votingworks/vxsuite/pull/1809#discussion_r869463541

**Comment by adghayes** [comment]
`Main` no longer has a `maxWidth` prop.
