### ISSUE TITLE
Central System: enable "tap to click"

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1821]
We have trackpads on VxAdmin and VxCentralScan. Tapping on them should function like a click.

**Comment by adghayes** [comment]
I did a little research and it looks like Chrome and Electron don't have touchpad tap event detection that we can use, so we have to do it on a machine-level. It can be set on a machine with the following command (tested): 

```gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click 'true'```

Is the right place to tuck this in in the `setup-machine.sh` script in `vxsuite-complete-system`? Depending on the machine being set up. If that's the case, I will add it in there.

**Comment by benadida** [comment]
@adghayes in general yes, that's exactly where you want to put it.

One thing: I'm not sure if that will work as I'm not sure that gnome preferences apply in production mode where we just have a raw X server and very simple window manager, so you may want to look into how to enable this in `libinput` or `openbox`. Here's one starting point:

https://wiki.archlinux.org/title/Libinput#Button_re-mapping

**Comment by eventualbuddha** [comment]
If I can question the premise: tap-to-click has always struck me as a power user feature and is off by default on at least macOS because of the likelihood of accidental input. Enough that some people have coined the term [tap-to-click wizard](https://atp.fm/129) to describe people who use it without messing it up.

**Comment by mattroe** [comment]
I discovered today that I can actually press instead of tap the trackpad on the Thinkpads that makes this is a non-issue in my opinion, especially considering @eventualbuddha's tap-to-click wizard comment.
