### ISSUE TITLE
VxMark: "Done" screen is shown too long

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1823]
When a ballot is printed, the final instructions are shown for a very long and should timeout after a short period of time.

Suggest 30 seconds as the timeout.

**Comment by mattroe** [comment]
On VxDev, I don't ever see this screen go away unless I click `Done`. Do we have a specific timeout set or is just the general kiosk-browser refresh timeout?

**Comment by benadida** [comment]
I think I'm seeing this, too. This is unrelated to kiosk-browser. I think we need to time this out faster, and at least time it out after some time. One thing I forgot to mention in my review: also when you put in the poll worker card, it thinks the voter is still activated at that point, so you have to deactivate and then activate a new voter. That's suboptimal.

**Comment by taravancil** [comment]
This [timeout](https://github.com/votingworks/vxsuite/blob/main/frontends/bmd/src/app_root.tsx#L426,L437) is currently set for [60 seconds](https://github.com/votingworks/vxsuite/blob/main/frontends/bmd/src/config/globals.ts#L6), I will bump it down to 30.
