### ISSUE TITLE
VxScan: "Count Ballot" as is text is too small on the ballot review screen for blank/overvote

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1824]

**Comment by beausmith** [comment]
There is a confirmation modal, thus making this button larger should not result in ballots accidentally being counted as is.

The larger button should be displayed in a different location than the confirm button in the confirmation modal to help avoid a double tap and further confirm the voter's intent to accept ballot with undervotes, overvotes, etc.

**Comment by eventualbuddha** [comment]
> Did this button get removed? I'm not seeing the string 'count anyway/s' in the codebase.

https://github.com/votingworks/vxsuite/blob/3f0433a8654e48cd4ba06765542debb91e7a80f0/frontends/bsd/src/screens/ballot_eject_screen.tsx#L463

**Comment by mattroe** [comment]
@taravancil button text is actually `Count Ballot`

I didn't realize this issue was assigned to you though. Let's punt on this one for a bit as this experience is likely going to be modified as part of the VxScan updates as we update ballot review screen UX.

**Comment by eventualbuddha** [comment]
https://github.com/votingworks/vxsuite/blob/3f0433a8654e48cd4ba06765542debb91e7a80f0/frontends/precinct-scanner/src/screens/scan_warning_screen.tsx#L77
