### ISSUE TITLE
Single sheet polls/open closed reports

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1836]
A few things about our polls open/close report:
- there's a lot of stuff printing: signature page, tally sheet, VxQR QR code.
- in primaries, we print separate tally sheets, but not separate signature pages.

Let's solve both of these problems at once by aiming for a polls open report that is, in most cases, just one sheet. In the case of primaries, one sheet per party. The polls open report should include:

- a top banner with the title ("Polls Open"), machine information, compact space for signatures, and ideally a VxQR code in the upper right-hand corner or the like
- the rest of the sheet shows the tally, much like today, only lower by a couple of inches to leave room for the top banner.

Thus, in a primary, a polls open report would be 4 sheets:
- 1 sheet for R, 1 sheet for D --> to be posted on the wall
- 1 sheet for R, 1 sheet for D --> to be filed for records.

**Comment by mattroe** [comment]
For New Hampshire specifically, the main requirement is to have the signatures on the tally sheet itself.

**Comment by adghayes** [comment]
@mattroe I’m thinking about how to consolidate the precinct reports, a few design questions:
- Should / can we drop the seal? Nice to have but would free up space for contests.
- Can we drop the “Unofficial” vs. “Official”? I don’t understand why we have this on our top-level signature page at all, as precinct results can’t be “Official” in the certified sense.
- Signatures at top or bottom of page? Signature at bottom makes more sense, but in the case where tally reports span multiple pages then the print formatting becomes more complicated (signature on every page or only on last page?) cc @benadida 

Other things to move, not controversial:
- Signature Space, somewhere
- TEST vs. not test
- Machine ID
- Report saved vs. report create times (do both if different)

**Comment by adghayes** [comment]
If we want to put signatures on the bottom of the page but, in the case of multi-page reports, only on the last page, that gets us into PagedJS territory. Which is definitely out of scope for this change. So the options are:

- Signature at top of page
- Signatures at bottom of page, but will appear on every page for multi-page reports
- 
This is a bit of an edge case because I don’t think we’re expecting multi-page reports for the closest elections.

**Comment by adghayes** [comment]
@benadida is the VxQR code going to be the same across all pages of the report if there are multiple pages?

**Comment by adghayes** [comment]
@mattroe are we comfortable dropping the seal?

**Comment by mattroe** [comment]
@adghayes yes, we can drop the seal -- it is not a hard requirement.

Re: VxQR, for the first version of this for NH, we can continue to have VxQR on a second page as we will not have the feature enabled for them. We can then take a second pass at this to unify VxQR when we eventually enable it for a customer in a future election.

**Comment by adghayes** [comment]
Need to style some things, but here's a first pass at getting all the info on the page.

<img width="519" alt="Screen Shot 2022-09-30 at 1 21 46 PM" src="https://user-images.githubusercontent.com/37960853/193350425-73242b7e-c9e4-4892-bf0e-ef446826dda8.png">
