### ISSUE TITLE
VxAdmin: determine m14 ballot content, expected sheet size, and test auto-layout

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1838]
Confirmed races as of 05-24:
* US House Race (all counties, max 3 candidates currently filed)
* Court of Appeals Judge (most counties, max 3 candidates currently filed)
* Chancery Court Judge (all counties, up to 3 contests per county, max 5 candidates currently filed)
* Circuit Court Judge (all counties, up to 3 contests per county, max 5 candidates currently filed)

Unknown:
* Specials
* Levee Commissioners
* School Board

https://legiscan.com/MS/bill/HC39/2022 failed which means there will not be any initiatives on the Nov 2022 ballot, which was my largest concern.

Relevant reference docs: 
- https://sos.ms.gov/sites/default/files/election_and_voting/eleChart-2000-12.pdf
- https://www.sos.ms.gov/Content/documents/Elections/candidate%20qualifying/2022%20Candidate%20Qualifying%20List.pdf

**Comment by mattroe** [comment]
Latest update from Warren County: https://votingworks.slack.com/archives/C03GUQNPD7X/p1658357599479889

I'm going to create a sample ballot based on this information for us during m14 QA

**Comment by mattroe** [comment]
Confident we are ok after doing this exercise: https://github.com/votingworks/election-definitions/pull/111
