### ISSUE TITLE
VxScan: override mark thresholds

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1856]
VxScan does not have the admin capability to override mark thresholds like VxCentralScan. The implementation should follow the model on VxCentralScan:

- Inserting an Election Manager card should provide an `Override Mark Thresholds` button in the admin settings view
- This button should guide the user through the same override mark thresholds modal experience as VxCentralScan

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1652997057490029

**Comment by mattroe** [comment]
@taravancil updated the issue description for clarity
