### ISSUE TITLE
ESI: identify all issues with read-only partitioning scheme

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1857]
We've got a read-only partitioning scheme for Enhanced System Integrity. We need to catalog all of the issues we hit when running on this partitioning scheme. We can probably do this in a VM.

## All Machines

- ✅  ability to mount and unmount USB sticks repeatedly (note single mount point only for now that was created pre-lockdown)

- ✅  ability to set clock and works across reboots

- ❌  set timezone

- ❌ set machine ID (cause hostname)

- ✅  setting machine type works.

- ✅  setting signing key works.

- ✅  starting config wizard on next boot.

- ❌ printing – fails with `lpadmin: Unable to copy PPD file – Read-only filesystem`

## VxAdmin

- ✅  machine configuration works and survives reboot

- ✅  CVRs load and survive reboot

- ✅  printed-ballots report works and survives reboot (after fixed printing, confirmed)

## VxMark

- ✅  machine configuration works and survives reboot

- ✅  test mode / live mode works and survives reboot

- ✅  change app mode (mark only)

- speech synthesis

## VxScan

~~Something is off with the scan service, exploring.~~
That was transient, due to a bad USB stick. Looking good now.

- ✅ machine configuration works and survives reboot

- ✅ scanning data properly stored and survives reboot

## VxCentralScan

- ✅ machine configuration works and survives reboot

- ✅ scanning data properly stored and survives reboot

- ✅ export CVR to USB works

**Comment by umbernhard** [comment]
@benadida adding this to your list too: https://github.com/votingworks/vx-iso/issues/25#issuecomment-1132172155

**Comment by benadida** [comment]
> @benadida adding this to your list too: [votingworks/vx-iso#25 (comment)](https://github.com/votingworks/vx-iso/issues/25#issuecomment-1132172155)

As per discussion in that ticket, we will address this by not changing the hostname.

**Comment by benadida** [comment]
Whole system mapped out as per above, looking good.
