### ISSUE TITLE
Avoid using array index as key in test deck ballot generation

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#1864]
HMPB test deck ballots: https://github.com/votingworks/vxsuite/blob/499fc20eb2f2de3c419a6350a73d253bdc58b89e/frontends/election-manager/src/screens/print_test_deck_screen.tsx#L163

BMD test deck ballots: https://github.com/votingworks/vxsuite/blob/499fc20eb2f2de3c419a6350a73d253bdc58b89e/frontends/election-manager/src/screens/print_test_deck_screen.tsx#L104

Note that we can't just use something like `ballot-${ballot.precinctId}-${ballot.ballotStyleId}` because, in a test deck, there are multiple ballots for each precinct + ballot style combo.

**Comment by adghayes** [comment]
no longer relevant, no test deck generation in VxAdmin.
