### ISSUE TITLE
nh-accuvote VxCentralScan: ballot shows up upside down on screen for overvote

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1893]
When a NH-accuvote ballot is scanned top-in-first into VxCentralScan and is rejected because of overvote (and possibly blank but need to test), it is shown on the overvote screen upside down, with the overvote highlight in the place where it should be if the ballot were right-side up.

Seems like everything is working except the orientation of the displayed ballot.

**Comment by mattroe** [comment]
Confirming this is still happening as described ealier.

**Comment by mattroe** [comment]
And confirming the behavior is the same for blank ballots.
