### ISSUE TITLE
nh-accuvote: adapt to 100% ballot

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1895]
specifically bubble size and timing mark size and spacing.

**Comment by benadida** [comment]
I believe this is done, right @eventualbuddha ?

**Comment by eventualbuddha** [comment]
I didn't specifically do anything for this. It may be worth re-adjusting the oval template image for use with the Amherst ballot to make it have lower scores on unmarked ovals.

**Comment by benadida** [comment]
Right now, I'm seeing max of 5.5% on blank bubbles. Checkmarks at ~20%, X at ~25%, line through bubble at 18%, mostly filled in bubble at 50+%. I don't think it's worth messing with this for now.
