### ISSUE TITLE
Lock down all partitions, leaving only /var and /tmp

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1899]
We want to lock down as much of the drive as possible. In particular, we want to lock down `/home`. 

To consider:
- kiosk-browser saves stuff in `/home/vx-ui/.config` --> should we symlink that to `/var`, should we rearchitecture to not saving anything in that directory

**Comment by mattroe** [comment]
@benadida is this issue still relevant?

**Comment by benadida** [comment]
yes, still relevant, but not high priority and not needed for m14.

**Comment by benadida** [comment]
started:
https://github.com/votingworks/vxsuite-complete-system/pull/273

**Comment by benadida** [comment]
made significant progress in https://github.com/votingworks/vxsuite-complete-system/pull/273

now need to remove the separate `/home` partition altogether.

**Comment by arsalansufi** [comment]
Marking as done per discussion in Slack: https://votingworks.slack.com/archives/CEL6D3GAD/p1720721174227079
