### ISSUE TITLE
VxAdmin: Add Save as PDF option to anywhere where we are printing but not allowing you to save right now

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#1903]
In VxAdmin we print many things in many places and in some of those we also allow users to save things as a PDF, but we are inconsistent in this, we should update the locations that don't have it to include the option to save as pdf, most notably with the L&A files. 

Our printing story recently changed thanks to @adghayes which should make this task easier then it was in the past.

**Comment by adghayes** [comment]
@mattroe I think we should tackle this one after we rethink printing across all our apps #1531, because it will be a lot lower lift at that point.

**Comment by adghayes** [comment]
Closed by #3072, correct me if I'm wrong @kshen0.

**Comment by kshen0** [comment]
Correct, thanks for closing
