### ISSUE TITLE
Implement success screen that instructs admins to remove their card after successful auth on VxAdmin and VxCentralScan

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#1910]

**Comment by arsalansufi** [comment]
Chatted with @beausmith and he noted that this page should look something like this:

[ Card-removal icon, to be provided by @beausmith ]
**Successfully Authenticated**
Remove card.

**Comment by beausmith** [comment]
The remove card icon is in the vxsuite repo: `frontends/bas/public/images/remove-card.svg`

**Comment by adghayes** [comment]
Couple questions for @beausmith and @arsalansufi:

- When an election definition is loaded, do we want to show the `ElectionInfoBar` on this screen? Or as a temporary screen, does it not matter? I'm wondering whether I have to put it in the `frontends` to have the election context or if I can just do it in `libs/ui` as I've already done locally.
- Do we source all our assets from the `public` folder in each app, meaning an asset used in multiple apps should be in the `public` folder of each app?

**Comment by adghayes** [comment]
It seems like the current pattern is to have the auth screens duplicated across both apps. Is that necessary and something we want to continue with?

**Comment by arsalansufi** [comment]
> When an election definition is loaded, do we want to show the ElectionInfoBar on this screen? Or as a temporary screen, does it not matter?

I'll defer to @beausmith on this one!

If we do want to display the ElectionInfoBar, we can still put the new component in `libs/ui` and have it take an (optional) `Election` object as a prop.

> Do we source all our assets from the public folder in each app, meaning an asset used in multiple apps should be in the public folder of each app?

Briefly looking through the code, that seems to be the case, with the caveat that `libs/ui` pulls its images from `src/images` instead of `public`. There are ways to keep images in a shared location, though this does get a bit tricky with the mono-repo setup.

> It seems like the current pattern is to have the auth screens duplicated across both apps. Is that necessary and something we want to continue with?

In an ideal world, these components would be shared! https://github.com/votingworks/vxsuite/issues/893 The duplication is probably just an artifact of how the codebase grew over time.

**Comment by beausmith** [comment]
Agreed with @arsalansufi's answers. 

Ideally, once we have an election definition an `ElectionInfoBar` footer should be displayed as the footer on all non-"modal" screens.

On VxAdmin, I had designed that "US State Name" and "Jurisdiction Name" should be in global settings such that the footer would always have information. These settings are marked "m14 puntable" so for now, the footer can be omitted if there is an election definition is undefined.
