### ISSUE TITLE
Triage Charlie's L&A feedback doc

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1929]
https://docs.google.com/document/d/167zfGWe_KZyaJ0zBYiBi6e_otgIpTUJ7WmInH1GBn_M/edit?usp=sharing

Issue automatically created from slack feedback reported by charlie 
https://votingworks.slack.com/archives/CJU9MSC6S/p1654530547030519

**Comment by benadida** [comment]
done!
