### ISSUE TITLE
VxMark: on polls open/close, use flows that clearly confirm action, like on VxScan

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1937]
Confusion post closing polls on VxMark

I think we already have this logged, but after clicking close polls on VxMark, it's not obvious at all that you've finished. Suggest we present to poll workers like we do on VxScan where it auto navigates to the big polls closed header screen.

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/CJU9MSC6S/p1654647665013389

**Comment by benadida** [comment]
is this basically done by new close-polls approach with integrated vxscan behavior? @mattroe ?

**Comment by mattroe** [comment]
This was suggesting something else (obviously showing open/close state onscreen after action), but we can close this and test how the new polls open-close flow improves the user experience before making further changes.
