### ISSUE TITLE
VxAdmin: clicking "print ballot" button when printer is disconnected shows no user feedback for seconds

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1946]
Eventually it shows a "printer not connected" modal. But in the interim few seconds I'm tempted to just keep clicking print and not sure why nothing is happening. Some immediate modal would be best.

**Comment by mattroe** [comment]
@benadida are you still reproducing this delay? I'm not seeing it.

**Comment by benadida** [comment]
nope, this is solved, it's nice.
