### ISSUE TITLE
Investigate and Implement what different paper jam messages we can / should show in the UI 

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1960]
After m13b, there is a desire to show more information about paper jams in the VxScan UI. There are various error codes in new versions of the plustek drivers we don't know how to interpret and should investigate what those enum values mean and what new UIs, if any, we should surface in the precinct-scanner and how to handle crazy edge cases in jam scenarios. Closely related to https://github.com/votingworks/vxsuite/issues/1958

**Comment by mattroe** [comment]
closing in favor of roadmap issue https://github.com/votingworks/vxsuite-roadmap/issues/59
