### ISSUE TITLE
VxAdmin: change "create new election definition" to load "demo election definition" and update demo content

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1967]
VxAdmin currently doesn't give you the ability to create a new election definition, so we shouldn't present that option. Instead, it should enable you to "Load Demo Election Definition" that should program VxAdmin with a test fixture election definition (suggest latest Lincoln Municipal General Election).

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/CJU9MSC6S/p1654021026669759?thread_ts=1654021026.669759&cid=CJU9MSC6S

**Comment by mattroe** [comment]
@benadida also tackled via https://github.com/votingworks/vxsuite/pull/2332
