### ISSUE TITLE
How can ballot accounting be made easier for primaries?

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1969]
*VxScan "ballots counted" shows breakdown by party.*
In the current primary in Choctaw there are two check-in tables, one for each party. They have to add their numbers when checking against the count reported on the VxScan screen. They asked if it were possible to view a breakdown by party.

(But honestly… they should consolidating their checkin tables and number of poll workers necessary. This was a low-turnout election and most polling places had 5–7 poll workers.)

Issue automatically created from slack feedback reported by beau 
https://votingworks.slack.com/archives/CJU9MSC6S/p1654639946180799

**Comment by mattroe** [comment]
Closing as other customers did not have any issues with this ballot accounting flow
