### ISSUE TITLE
Try out AssemblyScript for custom image processing

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1989]
In completing #1896 I tried out a few things before settling on the (rather obvious in hindsight) solution of just using the native `canvas` APIs. At first I wrote a box sampling downscale function based on [this article](https://towardsdatascience.com/image-processing-image-scaling-algorithms-ae29aaa6b36c). I wrote it in TypeScript:

```ts
/**
 * Downscale a grayscale image to fit inside a given size.
 */
export function downscale(image: ImageData, size: Size): ImageData {
  const src = image.data;
  const channels = src.length / image.width / image.height;
  assert(channels === 1, 'expected 1-channel image');

  const xScale = size.width / image.width;
  const yScale = size.height / image.height;
  const scale = Math.min(xScale, yScale);
  const width = Math.round(image.width * scale);
  const height = Math.round(image.height * scale);
  const dst = new Uint8ClampedArray(width * height * channels);
  const result = createImageData(dst, width, height);
  const boxWidth = Math.ceil(1 / xScale);
  const boxHeight = Math.ceil(1 / yScale);

  for (let y = 0, offset = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1, offset += 1) {
      const xMin = Math.floor(x / scale);
      const yMin = Math.floor(y / scale);
      const xMax = Math.min(xMin + boxWidth - 1, image.width - 1);
      const yMax = Math.min(yMin + boxHeight - 1, image.height - 1);

      let lum = 0;
      for (let yy = yMin; yy <= yMax; yy += 1) {
        for (let xx = xMin; xx <= xMax; xx += 1) {
          lum += src[yy * image.width + xx] as number;
        }
      }

      dst[offset] = Math.round(lum / ((xMax - xMin + 1) * (yMax - yMin + 1)));
    }
  }

  return result;
}
```

It worked but performed terribly, taking just over 2s to downscale a 300 dpi legal-size ballot to a 200 dpi legal-size ballot. So I tried converting the code to [AssemblyScript](https://www.assemblyscript.org/), which is a subset of TypeScript using more specific number types that can be compiled to WebAssembly. I think of it sort of like [asm.js](http://asmjs.org/) is to JavaScript, though the analogy is not perfect. Here's that version:

```ts
/**
 * Downscale a grayscale image to fit inside a given size.
 */
export function downscale(
  src: Uint8ClampedArray,
  srcWidth: u32,
  srcHeight: u32,
  dstWidth: u32,
  dstHeight: u32
): ImageData {
  if (src.length !== srcWidth * srcHeight * 4) {
    throw new Error(
      `expected RGBA source image of ${srcWidth}x${srcHeight}x4 pixels, got ${src.length}`
    );
  }

  const xScale = (dstWidth as f64) / (srcWidth as f64);
  const yScale = (dstHeight as f64) / (srcHeight as f64);
  const scale = Math.min(xScale, yScale);
  const width = Math.round(srcWidth * scale) as u32;
  const height = Math.round(srcHeight * scale) as u32;
  const dst = new Uint8ClampedArray(width * height * 4);
  const boxWidth = Math.ceil(1 / xScale);
  const boxHeight = Math.ceil(1 / yScale);

  for (let y: u32 = 0, offset: u32 = 0; y < height; y += 1) {
    for (let x: u32 = 0; x < width; x += 1, offset += 4) {
      const xMin = Math.floor((x as f64) / scale) as u32;
      const yMin = Math.floor((y as f64) / scale) as u32;
      const xMax = Math.min(xMin + boxWidth - 1, srcWidth - 1) as u32;
      const yMax = Math.min(yMin + boxHeight - 1, srcHeight - 1) as u32;

      let r = 0;
      let g = 0;
      let b = 0;
      for (let yy = yMin; yy <= yMax; yy += 1) {
        for (let xx = xMin; xx <= xMax; xx += 1) {
          const boxOffset = (yy * srcWidth + xx) * 4;
          r += src[boxOffset];
          g += src[boxOffset + 1];
          b += src[boxOffset + 2];
        }
      }

      const boxArea = (xMax - xMin + 1) * (yMax - yMin + 1);

      dst[offset] = Math.round(r / boxArea) as u32;
      dst[offset + 1] = Math.round(g / boxArea) as u32;
      dst[offset + 2] = Math.round(b / boxArea) as u32;
      dst[offset + 3] = 255;
    }
  }

  return {
    data: dst,
    width,
    height,
  };
}
```

This version is mostly the same but operates on an RGBA image, so it looks a little different and operates on 4x as much data. I measured it at about 10x faster than the JS version, taking 200ms to downsample a 300 dpi legal-size image.

As I mentioned at the top, the `drawImage` API is already well suited to this and highly optimized and performed the task in 17ms, so there's no good reason to use this. However, we do a fair amount of image processing that is not already part of some API we can use, such as the majority of `ballot-interpreter-vx` and `ballot-interpreter-nh`. AssemblyScript may be a way to improve the performance of these without switching to another language. To be sure, there are significant differences between AssemblyScript and TypeScript and the toolchain is different, but there remains much overlap.

**Comment by MaxGraey** [comment]
I also recommend use `unchecked` for all array's operations. This will skip bounds ckecks:
```diff
-         r += src[boxOffset];
-         g += src[boxOffset + 1];
-         b += src[boxOffset + 2];
+         r += unchecked(src[boxOffset]);
+         g += unchecked(src[boxOffset + 1]);
+         b += unchecked(src[boxOffset + 2]);
```
and
```diff
- dst[offset] = Math.round(r / boxArea) as u32;
- dst[offset + 1] = Math.round(g / boxArea) as u32;
- dst[offset + 2] = Math.round(b / boxArea) as u32;
- dst[offset + 3] = 255;
+ unchecked(dst[offset] = Math.round(r / boxArea) as u32);
+ unchecked(dst[offset + 1] = Math.round(g / boxArea) as u32);
+ unchecked(dst[offset + 2] = Math.round(b / boxArea) as u32);
+ unchecked(dst[offset + 3] = 255);
```
Also instead `Uint8ClampedArray` better to use `Uint8Array` if you sure this fit into 0-255 range and saturating is unnecessary. Even better use `StaticArray<u8>` for input and output arrays

**Comment by MaxGraey** [comment]
Also in AS `r, g, b` in your example are integers, so you don't need use round or floor after divisins. It's unnecessary conversions to float and back to integers. Just use `r / boxArea`. Also if you need a `min / max` over integers better use global generic builtins `min(a, b)` / `max(a, b)` instead `Math.min(a, b)` / `Math.max(a, b)`

**Comment by adghayes** [comment]
Since we've settled on using Rust for our image processing, I am closing this.
