### ISSUE TITLE
Add support for more ballot types

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#200]
There are two categories of ballot types:
- on ballot (absentee, affidavit)
- designated only at scanning (Absentee 5-day hold)

Let's have a configurable list of ballot types as part of the election definition. Tabulation can be broken down by ballot type, whether on-ballot or designated at scanning.

For those ballot types designated at scanning:
- provide a way to specify the type of ballot when scanning a batch
- when exporting CVRs, export one file per type of ballot scanned
- include a metadata line at the top of the CVR file, a JSON object with metadata.

**Comment by benadida** [comment]
too broad, will review based on real vvsg2 requirements.
