### ISSUE TITLE
Tweak <Prose> spacing such that a <p> tag that follows an <h2> and that contains a button doesn't feel so cramped

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#2013]
<img src='https://user-images.githubusercontent.com/12616928/175357886-0526fcdf-404f-45ac-a0df-068673acbc72.png' alt='spacing' width='400' />

When a `<p>` tag following an `<h2>` contains only text and no buttons, the spacing looks okay.

**Comment by adghayes** [comment]
We should, instead, just stop using the formally deprecated `Prose`.
