### ISSUE TITLE
`ballot-interpreter-vx` fixtures do not work with `MOCK_SCANNER_FILES`

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2033]
@taravancil ran into issues where the election hash didn't match. We both saw something where the ballots failed to load due to a correspondence issue between template and scanned ballot. Unsure what the root cause is.

Related: #1524 

Some Slack discussion [here](https://votingworks.slack.com/archives/CEL6D3GAD/p1656521377580499).

**Comment by adghayes** [comment]
Outdated.
