### ISSUE TITLE
Remove useSmartcard hook

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#2048]
The useSmartcard hook is now replaced by useDippedSmartcardAuth and useInsertedSmartcardAuth. It's still used in one fronted, however: bas. Once we add the card programming interface to the new auth hooks, we can replace useSmartcard in bas and then remove the old hook.

**Comment by arsalansufi** [comment]
Copying from https://github.com/votingworks/vxsuite/pull/2444:

> While we initially planned to update VxEncode to use the new smartcard hooks so that we could remove the old `useSmartcard` hook, VxEncode has some unique needs not currently covered by the new smartcard hooks, namely programming of voter cards by poll workers. Instead of updating `useDippedSmartcardAuth` to support this need (currently, only system admins and election managers can use dipped smartcard auth, and only system admins can program cards), I've just moved the old `useSmartcard` hook from `libs/ui` to `frontends/bas` to guarantee it isn't mistakenly used in other frontends.

Updating the title of this ticket accordingly
