### ISSUE TITLE
VxScan frozen on insert after invalid ballot scan

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2055]
Today I have been able to somewhat consistently reproduce the issue in the video below, where VxScan is frozen and won’t pull in ballots from the “Scan Your Ballot Screen”

Reproduction Steps:
• Insert invalid ballot (blank piece of paper)
• On rejection, pull it out and re-insert it after 1 - 2 seconds
    ◦ If you re-insert too quickly, it will stay on the “Scanning Error” Screen
    ◦ If you re-insert too slowly, it will scan the ballot normally
    ◦ If you re-insert sometime in between, it will do the following:
        ▪︎ Pull paper very slightly in, push it out, pull it in
        ▪︎ Scan it, but the screen will not change to “Scanning…“, it will stay on “Scan Your Ballot”
        ▪︎ Once rejected, VxScan will be wedged in this state
I can consistently wedge it within 25 tries or so.

@caroline I’m not sure if you want to dedicate any troubleshooting time to this if the whole scanner flow is going to be reworked? But documenting here so we can at least re-test later

Issue automatically created from slack feedback reported by drew 
https://votingworks.slack.com/archives/CJU9MSC6S/p1656697896700599?thread_ts=1656697896.700599&cid=CJU9MSC6S

**Comment by jonahkagan** [comment]
@adghayes I'm pretty sure this is resolved now, so gonna close, but let me know if you can still repro this
