### ISSUE TITLE
nh-accuvote WIA: cropping of Contest and Write In Selection for NH ballot Images

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2060]
See: https://votingworks.slack.com/archives/C02Q3M874SV/p1656701769812609

It is currently misaligned. 
The code to export the layout information can be seen here: https://github.com/votingworks/vxsuite/pull/2052
And that information is interpretted in VxAdmin here. https://github.com/votingworks/vxsuite/pull/2058

**Comment by mattroe** [comment]
Reopening this task as the wiring up of the images in the adjudication screen still hasn't been completed although the layout information is now included in interpretations to make images easier to associate in CVRs https://github.com/votingworks/vxsuite/pull/2086

**Comment by mattroe** [comment]
Closing this for now as it's primarily done. Opening a separate issue for the new bug.
