### ISSUE TITLE
nh-demo: demo hardware production

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2066]
see checklist: https://docs.google.com/document/d/1HK7KI0Y7NLcmUlMkMT9GABXz-4o_2CDx9F61_RnGyw0/edit#heading=h.ppnkstb3xi82

**Comment by benadida** [comment]
Now that I've demo'ed with VxDev, I think there's a good reason to make these production builds, not VxDev, if we have time. If the software is in good working order by Friday, this should be doable.

**Comment by mattroe** [comment]
This may be another reason: https://github.com/votingworks/vxsuite/issues/2073

**Comment by benadida** [comment]
also we want to consider Debian vs. Ubuntu here.

**Comment by benadida** [comment]
feeling strongly that we should do a production build. With Ubuntu if we can't figure out the Debian plustek issue this week. Either way, we know how to build this in VMs and create installer images.

**Comment by benadida** [comment]
given what I just repro'ed in terms of Debian-related crash, at least for the scanner, I want an Ubuntu based, likely production locked down image.

**Comment by benadida** [comment]
Reminder to turn on the right feature flags: livecheck, wia, vx_dev to activate wia, and converter set to nh-accuvote
