### ISSUE TITLE
nh-accuvote: cross party endorsement contest tabulation errors

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2072]
## Description
* A mark for `Edward Randolph - Republican` is not tabulated when it's the only selection for the contest.
* A mark for `Edward Randolph - Republican` and `write-in` on the contest is not rejected as an overvote by the scanner and neither mark is counted.

## Repro
1. Scan a ballot where `Edward Randolph - Republican` is the only mark. It will be flagged as a blank ballot. Note: if you "count" the blank ballot, it will actually be counted as a mark for the correct `Edward Randolph` candidate selection.
2. Scan a ballot where `Edward Randolph - Republican` is the only mark for the contest. Edward Randolph will not appear on the tally report.
3. Scan a ballot where `Edward Randolph - Republican` and `write-in` is marked and neither mark will be tabulated, nor will the scanner reject as an overvote.

## Related conditions that are tabulated correctly
- Scan a ballot where `Edward Randolph - Democrat` is the only mark for the contest. It will be correctly tabulated as a vote for `Edward Randolph`.
- Scan a ballot where both `Edward Randolph` bubbles are marked. It will be correctly tabulated as one vote for `Edward Randolph`
- Scan a ballot where both `Edward Randolph` bubbles are marked as well as `write-in`. It will be correctly rejected as an overvote.

**Comment by eventualbuddha** [comment]
This is because [`convertMarksToAdjudicationInfo`](libs/ballot-interpreter-nh/src/interpret/convert_marks_to_adjudication_info.ts) finds the first oval that matches the `contestId`/`optionId`, expecting that there's only one. Instead, we should select all of the ones that match and consider it a mark if any of them are marked.
