### ISSUE TITLE
VxCentralScan often stops and doesn't count the last ballot in the batch

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2073]
I’m running into a pretty regular problem on VxDev VxCentralScan that I _think_ is specific to VxDev as I don’t believe we’ve seen this in production, but we should definitely confirm.

In the middle of a batch of ballots, the Fujitsu will just stop scanning ballots and the last ballot scanned won’t be counted in the batch. This often happens on the first ballot in the batch where it records a batch of zero ballots.

No errors in VxDev terminal or browser console.

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/C03C0DZL021/p1656819971450519

**Comment by benadida** [comment]
I have not seen this yet. Trying a few times.

**Comment by benadida** [comment]
no repro on my system after a number of tries. This is likely @mattroe's scanner.
