### ISSUE TITLE
VxScan: plustek maxSize determine how to config & if it improves scanning

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2083]
@benadida has an email out to plustek about how to configure for MaxSize image capture

**Comment by mattroe** [comment]
Yes, let's close if @eventualbuddha agrees that it won't meaningfully improve scanning.

**Comment by eventualbuddha** [comment]
Sounds right to me. It could be a marginal improvement in the future that we decide to pursue if we're seeing issues with timing mark detection.
