### ISSUE TITLE
production pre-seed: bigger drive and home partition

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2089]
I keep getting caught with no disk space while building on production pre-seed. Let's tweak it so:

- /home is 5GB bigger
- /var, while we're at it, is 45GB bigger.

That will make a 100GB total image, which will be safe for a while. `lz4` is very good at compressing empty space, so not worried about our compressed image sizes.

**Comment by umbernhard** [comment]
My only concern is lz4 is heavily performance bound by processor, so larger sizes will have an impact on install time on our devices. That may not be that big a deal tho.
