### ISSUE TITLE
VxScan: disable image interpretation for high-volume scanning tests

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2114]
## Summary

@adghayes is coordinating testing of different potential hardware changes which includes high-volume scanning of paper. Enabling continuous scanning of paper and bypassing image interpretation will increase the rate of testing and reduce the amount of preparation required. 

## Requirements
- @adghayes can configure a VxScan with this setting for the test units at the bakery. A potential location for this feature could be behind the superadmin or admin screen on VxScan.
- This feature should not be customer facing. It could be behind a feature flag.

When configured with this feature:
- VxScan should accept blank sheets of paper without rejecting to prevent needing to print ballot images on every sheet of paper included in the test
- VxScan should skip the ballot interpretation step to increase the throughput of ballots and a user should be able to continuously scan sheets.

**Comment by eventualbuddha** [comment]
First pass is on [`ben/quickscan-testing`](https://github.com/votingworks/vxsuite/tree/ben/quickscan-testing). Unsure if that meets the requirements of this issue.
