### ISSUE TITLE
vxadmin waiting on "load election" screen heats up a good bit

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2118]
It may be on other screens too, but that's the one I saw, when I happened to have installed it on surface go. I know that's not the hardware we run it on, it was for testing, but it likely indicates a tight loop somewhere that's causing some serious CPU usage.

**Comment by adghayes** [comment]
VxAdmin software architecture is very different now, and we're no longer designing for the Surface Go, so closing this.
