### ISSUE TITLE
VxAdmin: importing of 0 CVR file crashes app

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2119]
## Description

VxAdmin crashes if you import a 0 CVR file requiring a reboot and reconfiguration to access the tally screen again.

## Repro
1. Scan 0 ballots
2. Export CVR from scanner
3. Import CVR on VxAdmin
4. See white screen
5. Reboot
6. Navigate to tally
7. See white screen

You can avoid this behavior if you reboot and first reconfigure before navigating to tally screen.

**Comment by carolinemodic** [comment]
@mattroe Did you only repro this on the nh-demo branch or on main? I just noticed this ticket came from nh testing and the code that handles the import here was completely rewritten on that branch,

**Comment by mattroe** [comment]
@carolinemodic just tested on latest main and couldn't reproduce. thanks for calling this out - closing.
