### ISSUE TITLE
VxScan: investigate duplicate CVR saving

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2120]
During m13b, Warren County experienced multiple incidents where duplicate CVRs were saved to the USB drive. We have not been able to reproduce this behavior thus far without exporting twice manually.

**Comment by mattroe** [comment]
@adghayes did you happen to reproduce this in your testing of CVR exporting?

**Comment by adghayes** [comment]
no, I haven't seen it yet

**Comment by mattroe** [comment]
@adghayes OK. I'm going to close this now as I can't reproduce myself, but let's keep an eye out for this during app QA as it may be something we only identify on locked down machines.
