### ISSUE TITLE
[services/scan] interpreter does not reset expected election hash on reconfigure

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2130]
## Description
When reconfiguring `services/scan` through the BSD UI and without restarting the service, ballots will be rejected for being associated with the wrong election even though they are for the newly configured election.

## Repro
1. Start VxCentralScan (this probably also happens with VxScan) and its related services.
2. Configure it with an arbitrary election `A` (election.json only–I didn't test with a ballot package).
3. Delete its configuration.
4. Configure it again with an arbitrary election `B` where `B ≠ A` (election.json only–I didn't test with a ballot package).
5. Scan a ballot associated with election `B`.
6. The ballot is rejected due to "Wrong Election".
7. Restart `services/scan`.
8. Re-scan the ballot from step 6.
9. The ballot is accepted.

## Expected behavior
The ballot should not be rejected with "Wrong Election" as happens on step 6.

## Screenshots
![localhost_3000_(Lenovo 14_) (3)](https://user-images.githubusercontent.com/1938/178370126-193cc5f8-c80a-466e-8137-39c1fe6f9281.png)

**Comment by mattroe** [comment]
@eventualbuddha during the demo today, I unconfigured BSD and then reconfigured without restarting. Ballots were scanned as unreadable when I reconfigured with the election def only (local-election.json in the nh-demo election def repo). I then reconfigured without restarting using the ballot package and it worked normally.

**Comment by eventualbuddha** [comment]
We still need the ballot package for interpreting our HMPB format. We don't need it for NH ballots or BMD ballots.

**Comment by adghayes** [comment]
Unclear if this is an issue anymore, architecture has changed a lot, closing.
