### ISSUE TITLE
[VxAdmin] Definition shows raw "seal" SVG

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2132]
Rather than showing the raw SVG data, we should just render the SVG:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/1938/178555807-1bdce25b-6d62-4e0d-817f-99c9262e4a8a.png">

**Comment by mattroe** [comment]
@eventualbuddha I'm never seeing the raw seal data for my election definitions - I'm always just seeing the SVG file path.

**Comment by eventualbuddha** [comment]
Most of our elections are configured with just `sealURL`.

**Comment by mattroe** [comment]
Oh, makes sense. Didn't see that distinction.

**Comment by mattroe** [comment]
@eventualbuddha when would we want to use `seal` vs. `sealURL`? Trying to determine if this matters in practice.

**Comment by eventualbuddha** [comment]
For now it probably doesn't as our cards aren't big enough to fit most seals. But with the switch to Java cards it may come back as a thing.

**Comment by adghayes** [comment]
definitely fixed!
