### ISSUE TITLE
VxScan: on startup shows 0 ballots

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2136]
I noticed that when I refresh the precinct-scanner, it starts out with 0 ballots counted and then loads the actual count after a delay. It might be a little confusing - maybe starting with no number rendered would be better. (Not sure if this was always the behavior and is more noticeable now that it’s bigger, or if it was always this way).

Issue automatically created from slack feedback reported by jonah 
https://votingworks.slack.com/archives/CJU9MSC6S/p1657750901338289?thread_ts=1657750901.338289&cid=CJU9MSC6S

**Comment by mattroe** [comment]
cannot repro in kiosk browser

**Comment by mattroe** [comment]
@jonahkagan fixed on new state machine
