### ISSUE TITLE
Consider how to make test storage API consistent with `KioskStorage`

### ISSUE THREAD

**Issue by taravancil** [votingworks/vxsuite#2157]
## Description
This is a ticket to consider how to improve parity between our test storage API and `KioskStorage`.

Context in #2134 
> I also added a test in VxScan, but interestingly I cannot get it to fail with my change commented out. Manual testing in kiosk-browser reliably reproduces the incorrect behavior, however.

@jonahkagan's thoughts: https://github.com/votingworks/vxsuite/pull/2134#discussion_r920568302

> I realized that I could reproduce the behavior in kiosk-browser but not Chrome, which gave me a clue to look at the difference between KioskStorage (which is truly async) and LocalStorage (which is fake async). Making LocalStorage truly async and fiddling with timeouts can cause the same race condition to happen as we're seeing with kiosk-browser. I think tweaking MemoryStorage in a similar way will make your test fail, though it's a very specific tweak so I'm not sure if it's something we want to do permanently.

## Expected behavior
This [test](https://github.com/votingworks/vxsuite/pull/2134/files#diff-ffdcf7e63af87a7063891efbfbfe54a89437643d7bc17bad2113f905532bd21aR123) should fail when [this check](https://github.com/votingworks/vxsuite/pull/2134/files#diff-3c7f25e7ae7a0bc31c1dbc39d4452c7d559ad9742875cbc953601c52ad36d747R687) is disabled.

**Comment by adghayes** [comment]
no more storage API
