### ISSUE TITLE
Reject ballot sheets with invalid QR code metadata

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#217]
e.g. non-sequential page numbers, invalid precinct id, invalid ballot style id, etc.

Unify scan import / CVR export validation logic.

**Comment by eventualbuddha** [comment]
We do some of this on the export side, but we should have the same validation on the import side: https://github.com/votingworks/vxsuite/blob/b1a67d6b1b27ab9a8e935368ac17f3ae1d17bae8/apps/module-scan/src/buildCastVoteRecord.ts#L174-L199

**Comment by adghayes** [comment]
We now are validating QR codes within the interpretation logic, and have been for some time.
