### ISSUE TITLE
VxAdmin: enable printing of all ballot styles for a given ballot type

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2175]
Warren County m13 feedback:
> VxAdmin – Print test ballots for proofing – need a way to print all precincts, with one click, instead of printing one at a time. When working down the list of precincts, when I go back, I am at the top of the page again, and have to scroll back down.

VxAdmin should enable a user to print one copy of all ballot styles for a given ballot type [official/test/sample] in a one-click manner.

Printing of all ballot styles should be available for Election Managers, but System Administrators should only be able to print draft ballots.

**Comment by adghayes** [comment]
My suggestion for design of this feature:

- Add "Print All" button on ballots list page, next to "Export Ballot Package" button
- It opens a modal. The modal has instructive text reuses components from the individual ballot pages - Official / Test / Sample, Absentee / Precinct, Counter, and a print button.
- Printing progress shown in smaller modal.

@mattroe if this sounds roughly close I can start on it week.

**Comment by mattroe** [comment]
@adghayes that's essentially what I was envisioning as well. @beausmith do you have thoughts? 

@adghayes priority wise, I still think the third-party printing enabling issue is more important than this so we should pick that up first: https://github.com/votingworks/vxsuite/issues/2146

**Comment by beausmith** [comment]
Love it!

**Comment by adghayes** [comment]
I agree about the priority distinction, will think more about the other one.

**Comment by mattroe** [comment]
Printing of all ballot styles should be available for Election Managers, but System Administrators should only be able to print draft ballots.

**Comment by adghayes** [comment]
@beausmith @mattroe @ginvdr feedback on copy and flow please!

[screen-capture (7).webm](https://user-images.githubusercontent.com/37960853/182974585-e2762dd5-b1d9-4d63-a100-f503a8d69bc5.webm)

**Comment by mattroe** [comment]
@adghayes Overall flow looks good to me. 

A few specific thoughts:
1/ The ballots tab sub nav is getting pretty cluttered with the three functions (print all, export pdfs, export ballot package). Curious if @beausmith has thoughts here on how to declutter. Options could be unifying the print/export all into one top-level button or (crazy idea) move the Export Ballot Package to a different tab (L&A?) as it isn't part of the proofing flow. In the immediate term, I think simplifying the button titles could help. Suggest removing redundant references to "ballots", :
- `Print All`
- `Export PDFs`
- `Export Package`

2/ In the modal, suggest the following simplified copy: 

> Select the ballot type and number of copies to print:

**Comment by mattroe** [comment]
@beausmith to your questions:
1. Not yet. It's actually a heavy lift with a bunch of engineering consequences so we decided not to do this yet.
2. Export PDFs currently has the same options shown in the Print All. Designed that way because the common workflow is likely selecting just one of the style permutations (most likely just Official Precinct, but not always).

**Comment by adghayes** [comment]
Thank you both!

I have this implemented for draft ballots, just didn't video that yet.

@mattroe we could combine it, but I think having them separate is easier to build and maintain because the features require different hardware (usb stick vs. printer) and if they were combined it would be a pretty complex modal. There is one difference between the options - the export has no "Copies" option and the printing does. That being said, if a later design requirement is to combine, that is certainly doable.

**Comment by mattroe** [comment]
@adghayes sounds good. let's keep them separate for now.

related copy question: should we using `Export` or `Save` language here?

**Comment by ginvdr** [comment]
My thoughts - 
1. Save PDFs seems better to me
2. I'd like to see Export Ballot Package renamed and put somewhere else eventually but I'm not sure we have an intuitive spot yet
3. This will be helpful but I can already anticipate the next request and that is to pick a specific quantity for each ballot style.  Do we have a ticket for that?  Not important for m14 but for smaller elections when they print their own ballots, they won't want the same number for each precinct.
