### ISSUE TITLE
VxMark: audio prompts voter to review ballot content after printing

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2179]
VxMark audio reads the final screen to a voter to review the printed ballot. Customers have provided feedback that this is not relevant to blind voters using VxMark.

Related feedback: voters do not read the content on this screen as the ballot is already printing at this point. If we find these instructions to be important, we may want to present before printing.

**Comment by adghayes** [comment]
Audio prompts are now improved, but will will have to make sure this makes it's way onto VxMarkOld when we update those.
