### ISSUE TITLE
tally reports: split by voting method in data and visual reporting

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2199]
## Summary

We only show the *number* ballots that are absentee vs. in-person, not the breakdown of results. For VxQR but also for our reports overall, we should have the breakdown in our data structures and in our reports.

**Comment by adghayes** [comment]
Although it's not implemented in the way @benadida has at times described (absentee vs. precinct numbers on the same lines, side-by-side) we can get these splits with the VxAdmin reporting revamp.
