### ISSUE TITLE
Review Model names on components

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2206]
https://github.com/votingworks/vxsuite-complete-system/pull/123 Introduces manufacturer and model names in vxsuite-complete-system. Currently used in logging files but could eventually be used for other purposes. We may want version numbers in these names (i.e. VxScan 1.0) and we don't have an officially decided name for the precinct-scanner. VxPrecinctScan was used as a placeholder but should be reviewed.

**Comment by adghayes** [comment]
Closing as the model names have been established and reviewed for the VVSG 2.0 submission.
