### ISSUE TITLE
[VxDev] Enable users to exit apps without knowing keyboard shortcuts

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2209]
Add some control panel or something where you can quit kiosk-browser and not have to know the keyboard shortcuts to get out

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/C03C0DZL021/p1650404615283379

**Comment by arsalansufi** [comment]
Covering this as part of https://github.com/votingworks/vxsuite/pull/2236!
