### ISSUE TITLE
[VxDev] Screenshot & screen recording apps included in dock

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2210]
Add a way to take screenshots, maybe even record videos?

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/C03C0DZL021/p1650404595634009?thread_ts=1650404595.634009&cid=C03C0DZL021

**Comment by mattroe** [comment]
Default screenshot app in Debian image works well for documentation purposes. 

Suggest that we also include a screen recording app in the default VxDev image to capture videos. I like Kazam or SimpleScreenRecorder on Linux.

These two apps should be included in the dock on the next VxDev image release.
