### ISSUE TITLE
[VxDev] Needing to use a keyboard on the “Update Code” program to chose between the latest and the stable release will be painful on VxScan

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2215]
Needing to use a keyboard on the “Update Code” program to chose between the latest and the stable release will be painful on VxScan

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/C03C0DZL021/p1650400057194159

**Comment by mattroe** [comment]
You can use the touchscreen keyboard which is shown by default - not that bad of an experience.
