### ISSUE TITLE
VxSuite: white screen shown for 15-30s on startup

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2219]

**Comment by adghayes** [comment]
@mattroe have you seen this on production images as well?

**Comment by mattroe** [comment]
@adghayes yes, I was waiting to open it until I saw this on a production image.

**Comment by mattroe** [comment]
Reproducible on both Ubuntu and Debian images

**Comment by adghayes** [comment]
Not reproducible in my VM, interestingly. I think this will require playing with hardware.

Do you happen to know the most recent image that you've used that did _not_ have this issue? Might help narrow down the changes.

**Comment by mattroe** [comment]
I've been able to reproduce in dev & locked down running complete-system on debian and ubuntu.

I can confidently state this doesn't reproduce on a m13b-rc2 image.

I believe this was working on kiosk-browser post-election upgrade and that I started noticing this in the past ~3 weeks.

**Comment by mattroe** [comment]
I think this may be fixed with the latest kiosk browser changes. Cannot repro in dev.

**Comment by adghayes** [comment]
@benadida hasn't been able to repro and I am not able to repro after just installing prod images. Closing for now.
