### ISSUE TITLE
vxscan: speed of initial startup time long when 1,000+ ballots scanned

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2223]
## Description

When opening the polls, with 1,000 ballots previously scanned, it's quite slow. Likely due to CVR download, but still shouldn't be that slow.

**Comment by mattroe** [comment]
@benadida how slow of a startup were you seeing? @adghayes mentioned that he has not observed this in any high-volume testing at bakery.

**Comment by benadida** [comment]
I'm totally willing to believe that this was also due to the synchronous kiosk-browser issue. Closing until we repro.
