### ISSUE TITLE
VxScan: one yellow-orange Plustek light

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2240]
Slack discussion: https://votingworks.slack.com/archives/CEL6D3GAD/p1659132867252809?thread_ts=1659132432.040419&cid=CEL6D3GAD

1. Need to determine what this status is
2. Depending on status determination, decide what the user-facing flow should be, but it probably shouldn't be "Internal Connection Problem"

**Comment by mattroe** [comment]
Thread discussing similar behavior as seen on latest main: https://votingworks.slack.com/archives/CEL6D3GAD/p1659570987125819

**Comment by jonahkagan** [comment]
Closed by https://github.com/votingworks/vxsuite/pull/2303
