### ISSUE TITLE
vxsuite: make it possible to change test election definitions without failing a bunch of tests

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2247]
Over time, we need to add new fields to the election definition. Because that changes the Election Hash / ID, that causes a number of tests to fail that technically don't need to fail.

We should consider adjusting those tests so they don't fail.

**Comment by adghayes** [comment]
Closing this due to being too generic and old. With the distinction between ballot hash and election package hash we've addressed a good deal of this.
