### ISSUE TITLE
fix(bmd): kiosk-browser quit-and-restart sometimes fails and hangs

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2257]
## Description

In BMD, we quit and automatically restart kiosk-browser on idle. Unfortunately, on Debian, the latest kiosk-browser does not always quit nicely – sometimes it hangs in zombie state. That prevents the calling script from restarting kiosk-browser. The symptom on BMD is: leave it running for a bit idle, and eventually the screen just goes dark and only a reboot solves it.

**Comment by mattroe** [comment]
I'm actually able to reproduce this in dev as well; very confusing and frustrating.

**Comment by mattroe** [comment]
https://github.com/votingworks/vxsuite-complete-system/pull/220
