### ISSUE TITLE
vxscan: export of CVRs/card tallies do not include under/overvotes

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2258]
## Description

Using the `mock-m14` election definition, I scanned 8 ballots, but CVR export only shows 2. I suspect the issue has to do with our undervote adjudication, because 2 of my 8 scans were fully filled out ballots, while the others were either overvote or undervote. Also, this is the first time I've seen this and it's also the first time we have undervote adjudication turned on. I don't know for sure, though.

## Repro
1. Scan some ballots on vxscan with `mock-m14` election definition
2. Make sure some are undervotes that you choose to cast anyways.
3. Export CVRs, either by closing polls or explicit export on admin screen
4. See CVR file showing fewer ballots than expected.

## Expected behavior
Show me all the CVRs.

**Comment by mattroe** [comment]
https://github.com/votingworks/vxsuite/pull/2261
