### ISSUE TITLE
vx-iso: /vx/config directory not properly copied over from m13b to m14

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2266]
There appears to be some partition map / format difference.

**Comment by adghayes** [comment]
@amcmanus @benadida where are we at with preserving config between installs? Is it possible? Does it make sense to work into @amcmanus's current VxISO passion project?

**Comment by amcmanus** [comment]
@adghayes, this seems totally reasonable to include in my current vx-iso work. If you want to add any additional details/requirements to the Passion Project doc, that'd be great.

**Comment by adghayes** [comment]
@amcmanus closing this issue in favor of the more recent duplicate issue, https://github.com/votingworks/vxsuite/issues/5384
