### ISSUE TITLE
VxScan: skew interpretation investigation

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2279]
backup of spurious overvotes from recent test: https://drive.google.com/file/d/1NDGAGv8rfn_S5uoRYEK4pj7hGdYnEHbZ/view?usp=sharing

initial investigation discussion: https://votingworks.slack.com/archives/CEL6D3GAD/p1659730177901069

**Comment by benadida** [comment]
should be resolved by #2301
