### ISSUE TITLE
VxScan: ballot bag capacity stop

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2280]
## Description
When a VxScan ballot bag reaches capacity, no new ballots should be scanned until a poll worker confirms the ballot bag has been replaced and sealed.

## Requirements
- No new ballots are scanned after capacity is met and a new ballot bag full error screen should be shown. 
- The ballot bag full screen should still show the ballot bag count for poll workers to document for ballot accounting purposes.
- A poll worker can confirm the ballot bag has been swapped to continue voting and advance to the insert your ballot screen.

## Suggested Implementation (needs discussion)
- The screen in this state should read: *Ballot Bag Full* _Insert poll worker card to continue scanning after replacing ballot bag._
- Poll worker inserts card to access a button "Swap Ballot Bag" with a confirmation modal to confirm bag was swapped and sealed to begin voting.
- Insert your ballot screen is shown after card removal.

**Comment by mattroe** [comment]
Question raised as to whether this should be a poll worker or admin action

**Comment by beausmith** [comment]
Why is there a question about if this is task for a Poll Worker or the Election Manager?

We should be able to  can assume that there will be a Poll Worker card at the precinct. 

The Election Manager Card (previously Admin Card) should not be at the precinct. It should be used to set up a machine and then not used again until after the polls are closed. The exception to this is if there is some error or issue beyond what a Poll Worker should be able to take card of.

**Comment by mattroe** [comment]
@beausmith the question is whether a jurisdiction wants a poll worker to access the ballot bag, or if this is a procedure they would prefer for an administrator to perform.
