### ISSUE TITLE
Standardize Backup Flow in VxScan and VxCentralScan, use export modal in VxCentralScan

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#2295]
Currently the VxCentralScan and VxScan backups have different filenames and export to different folders. They are duplicating a lot of logic. It could be refactored for simpler code and streamlined behavior.

They also use different UIs, VxScan uses the nice export modal flow whereas VxCentralScan just opens a filepicker, we should update VxCentralScan to use the same UI as VxScan and save files to the same paths with the same naming structure.

**Comment by carolinemodic** [comment]
We should also make them both use the same back modal UI

**Comment by carolinemodic** [comment]
@arsalansufi this will be irrelevant after your project right?

**Comment by arsalansufi** [comment]
^ That's correct @carolinemodic!
