### ISSUE TITLE
VxScan: wrong election error thrown on valid BMD ballots

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2297]
During bakery high volume testing on 8/3 and 8/4, one of the two VxScan units [repeatedly reproduced](https://votingworks.slack.com/archives/C03KGSP78MQ/p1659569471709449) an issue where the "Wrong Election" error was shown for a BMD ballot with the correct election.

A discussion of this issue can be found here: https://votingworks.slack.com/archives/C03KGSP78MQ/p1659636212668319

**Comment by benadida** [comment]
#2309
