### ISSUE TITLE
Double print if printer is disconnected during printing

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#2299]
## Description
If you send a document to the printer, but then disconnect the printer after it has started printing, the document will print twice: once immediately, and once after reconnecting the printer. 

## Repro
1. Print a document, best a large one
2. Disconnect printer during printing
3. Let the current print job finish
4. Reconnect to the printer

## Expected behavior
We should not be printing jobs twice.

## Ideas
As a quick fix, we could cancel jobs on a printer when it is disconnected. That would require a new `kiosk-browser` API and a call to it [here](https://github.com/votingworks/vxsuite/blob/61091ef7a6f36634fca1638df2083e1ca83e7bce/libs/ui/src/hooks/use_devices.ts#L115). Alternatively, we could make this change alongside other slightly larger changes in how we print, like tracking print job IDs from our app and actually waiting on print jobs rather than using constant timeouts.

**Comment by carolinemodic** [comment]
@mattroe I'm removing tech-improvement from this as its a bug report but I think it will likely be solved as a part of https://github.com/votingworks/vxsuite/issues/1531

**Comment by carolinemodic** [comment]
@adghayes Do you know if this is still a bug after the other printing work we've done?

**Comment by adghayes** [comment]
Because we're no longer printer ballots from VxAdmin, and ballots are where the stakes are significant, I don't think this is very important anymore and I am closing.
