### ISSUE TITLE
VxMark: confirm volume control is expected volume

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2304]
@mattroe noticed that in dev the audio volumes are much lower than expected due to the default digital output selected. Discussion of the issue here: https://votingworks.slack.com/archives/CEL6D3GAD/p1660083281096599

Need to confirm volume is expected values when running the amixer commands on real hardware with headphones plugged into controller.

**Comment by benadida** [comment]
checked on production hardware with production image, sound levels are good.
