### ISSUE TITLE
scan: consider adding jsQR back as a fallback QR code reader

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2316]
We took out jsQR in #2315 because it was slowing down BMD ballot scanning when there's noise in the back page.

We should consider adding it back. A few ways to do so safely:
- parallelize front and back pages
- binarize image before QR detection
- run the fast QR codes on front and back first, if we find one side is a BMD ballot, we're good we don't need to use jsQR as a fallback.

**Comment by arsalansufi** [comment]
I'm closing this out as I believe this is no longer relevant and BMD scanning has changed quite a lot since. We're also going to Rustify BMD ballot interpretation
