### ISSUE TITLE
VxAdmin: results by precinct and voting method csv

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2317]
Schema: https://docs.google.com/spreadsheets/d/17hwQKDRHsQr4B2y-yC-cl7Dp95KLImr6KX_xNfD7HgA/edit#gid=0

UX:
- On reports tab, `Save Results` saves this file named as votingworks-mode-results-election-date.csv
- If in MS/SEMS converter mode, reports tab also has `Save SEMS Results` which saves the file named sems-mode-results-election-date.csv

**Comment by carolinemodic** [comment]
This function should support filtering by both precinct and voting method already but we will want to do some manual testing of this: https://github.com/votingworks/vxsuite/blob/e90cf6d5dd644a6bc8d610b63ec275ea83e191a5/libs/utils/src/votes.ts#L479
