### ISSUE TITLE
Standardize capitalization

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2339]
It’s weird to me that in some places user roles and cards are capitalized and some places not. E.g. in VxScan that I happen to be checking our right now: “Ask a poll worker for help” vs “Insert a Poll Worker Card after the ballot bag is replaced” vs “Remove the card to continue.” That’s one example, but I’ve noticed it throughout.

Personal opinion: don’t capitalize any of it, they aren’t official titles, just everyday people and objects.

Issue automatically created from slack feedback reported by jonah 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660252239585629?thread_ts=1660252239.585629&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Example:

On VxScan we have "Insert a poll worker card to open polls." and on VxMark we have "Insert Poll Worker card to open."
