### ISSUE TITLE
Generalize app copy to not be MS specific

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2359]
There are several MS-specific pieces of our app copy, potentially referencing SEMS, how we handle adjudication in the central scanner, etc. We should do a holistic review of app copy and make sure everything is generalized, or properly switches to NH language where appropriate.

**Comment by mattroe** [comment]
Closing this as I just did a copy review to ensure everything was not MS specific.

The only outstanding thing is the use of the word "Precinct" which is not applicable to NH and we may want to generalize to "Polling Place" in the future (to also accommodate other models like vote centers). It's referenced in so many places though that's it is not worth touching for this pilot.
