### ISSUE TITLE
vxscan: sound is not working

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2366]
probably because `amixer` does not seem to be installed on the `vxscan` prod image, not sure why.

*a few minutes later*: Yep, `festival`, which we install on vxmark only, depends on `alsa-utils`, which includes `amixer`. We should install `alsa-utils` independently, wherever we want sound.

**Comment by mattroe** [comment]
https://github.com/votingworks/vxsuite-complete-system/pull/230
