### ISSUE TITLE
VxAdmin: if you unprogram a pw/em card from the sysadmin card creation view, it then asks you immediately to program a sysadmin card

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2367]
VxAdmin: if you unprogram a pw/em card from the sysadmin card creation view, it then asks you immediately to program a sysadmin card

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660580462738109

**Comment by adghayes** [comment]
not the case in the new card programming scheme
