### ISSUE TITLE
Precinct System: new compute units

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2369]

**Comment by carolinemodic** [comment]
@mattroe can you write down v3 hardware requirements for this?

**Comment by mattroe** [comment]
### Compute
- No network connectivity hardware, or at least very easily removable in production.
- Plays nice with Debian
- ESI compatible TPM
- Connects easily to selected touchscreen
- Unknown minimum CPU requirements -- we may benefit from something beefier than the surface go for scanning on VxScan though.
- Fast USB read/writes

### Display
- Greg is currently designing around with the [ELO 15" touchscreen in mind.](https://www.elotouch.com/touchscreen-monitors-1502l.html) which I believe meets all product requirements I know about. This may be our best option as well.
- We can't go larger than 15" based on current hardware specification, but we could go smaller.
- Hard requirements: VESA mount, speakers, min 1920 x 1080 resolution

**Comment by umbernhard** [comment]
I'm closing out this task, decision doc is here: https://docs.google.com/document/d/1pO7tjHCgZtuCGCj7_fMR5xKULWqq5oaxycdwwpPcQ14/edit?usp=sharing
