### ISSUE TITLE
ID areas where SSO can be mandatory

### ISSUE THREAD

**Issue by umbernhard** [votingworks/vxsuite#2375]
In addition to GSuite and Github, Vx may use other third-party services that support single sign-on. As Google is likely to be more secure than random one-off authentication implementations, and it makes management of security controls much more streamlined, we should use Google SSO wherever we can. 

Third party services to investigate:

- [ ] Slack
- [ ] Copper
- [ ] Others?

Target Date: 11/01/22

**Comment by mattroe** [comment]
AWS
