### ISSUE TITLE
Use zod schemas to disallow ballot style and precinct IDs beginning with vx-

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#2385]
To prevent conflicts with the special-case ballot style and precinct IDs for super ballots. See https://github.com/votingworks/vxsuite/pull/2346#discussion_r946064301

**Comment by adghayes** [comment]
I don't believe this is relevant for v4, re-open if I am incorrect @arsalansufi @jonahkagan, but it does remind me that as part of 4.1 MS we will have to re-implement super ballots in VxDesign. I will create a separate issue for that.

**Comment by adghayes** [comment]
https://github.com/votingworks/vxsuite/issues/5640
