### ISSUE TITLE
Have tests fail if expected fetchMock calls aren't made at all

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#2386]
Many of our vxsuite tests use `fetchMock` to mock API calls. Tests fail when an unexpected call is made but often don't fail when no call at all is made. To avoid the latter, we should add assertions to make sure that calls are made or perhaps look into `fetchMock` settings to see if we can automatically throw errors when calls aren't made.

See https://github.com/votingworks/vxsuite/pull/2379#discussion_r946845492 for the discussion that led to this ticket

**Comment by adghayes** [comment]
`grout` gives us this behavior
