### ISSUE TITLE
[VxDev-BMD] standard build/run process throws node error

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2406]
I see the attached node error when I run the bmd after building via `./build.sh bmd` or building via the vxdev buttons. It goes away if I `make build` instead before running but that takes forever.

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/C03C0DZL021/p1660082417768909

**Comment by mattroe** [comment]
mitigation:
> cd vxsuite/frontends/bmd
> pnpm type-check
