### ISSUE TITLE
Candidate names appear to be aligned slightly above the centerline of the bubble

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2416]
Candidate names appear to be aligned slightly above the centerline of the bubble. This looks ok when there’s a party association as well, but looks slightly off to me when it’s just a candidate name (particularly for the candidate names starting with “Foo”)

Issue automatically created from slack feedback reported by jonah 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660758888071679?thread_ts=1660758888.071679&cid=CJU9MSC6S

**Comment by adghayes** [comment]
I believe this is different / better in the new ballot format.
