### ISSUE TITLE
VxAdmin: unpredictable behavior if you remove a card during programming

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2419]
VxAdmin: noticing some unpredictable behavior if you remove a card during programming. Here are two different examples

Issue automatically created from slack feedback reported by jonah 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660760115718479?thread_ts=1660760115.718479&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Card programming has been revamped as part of the auth project. Closing. cc @arsalansufi
