### ISSUE TITLE
VxAdmin: back navigation

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2423]
*In VxAdmin, when navigating to a sub screen of a main tab screen, the user should should not be confused about how to get back to the previous screen.*

Prompted by @ginny’s https://votingworks.slack.com/archives/CJU9MSC6S/p1660762101666279comment about back buttons> reminded me of this long-standing navigational issue.

*Problem:*
• The “Back” buttons are inconsistently placed under variable-height content on various pages. 
*Potential Solutions and Related Issues:*
• Consistently placed “back” button (or button with icon). Pushing the main content down or to the right to make space for a consistently placed “back button” would take up a lot of screen real estate. 
• Click the tab to get back to the main tab screen. Though it does work, this is not a common approach to going “back” that users don’t find to be very obvious.
• Open all sub-tab screens in fullscreen view. This would focus the content and require that the user click a “close” button or “X” to get back to the initial tab screen. This may seem heavy handed as it would require that the user always go back to the main tab screen before they could switch tabs.
• Use a contextual navigation where possible. eg. When viewing Definition &gt; Contest there could be a nav with three buttons: 
    ◦ “:arrow_left:Previous Contest”
    ◦ “Next Contest :arrow_right:”
    ◦ “:arrow_up: Full Election Definition”
• Add a “breadcrumbs” list of links (not buttons) on sub screens which lists the current page and links to the parent pages “above” it. For example:
    ◦ &lt;http://#|Definition&gt; &gt; Contest Details
    ◦ &lt;http://#|Ballots&gt; &gt; Ballot Details
    ◦ &lt;http://#|L&amp;A&gt; &gt; Precinct Ballot Packages
• Use inconsistently placed “back” buttons (as we are now) with labels that make the most sense given the sub screen. eg. When viewing a ballot in VxAdmin should the button be?
    ◦ “Go Back” - short, but requires context.
    ◦ “Back to List Ballots” - go back with context
    ◦ “View All Ballots” - go forward
What other potential solutions might we consider?

Issue automatically created from slack feedback reported by beau 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660773209707339

**Comment by jonahkagan** [comment]
I believe this issue was solved by the recent redesign of desktop apps
