### ISSUE TITLE
VxScan: remove "No" pollworker open/closed flow

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2427]
VxScan: As a poll worker, it seems odd that selecting “No” when asked whether I want to open/close the polls just drops me into a screen with the same action and no other options.

Issue automatically created from slack feedback reported by jonah 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660774588414119?thread_ts=1660774588.414119&cid=CJU9MSC6S

**Comment by adghayes** [comment]
The screen has other options now, so it's al little less confusing. Closing until there is more clarity on a different polls flow.
