### ISSUE TITLE
Improve management of environment variables 

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2442]
Now that we are using environment variables for feature flagging and for managing workarounds to make local development simpler there are already a quickly growing list of environment variables. It is hard to remember which environment variables  exist, what they all do, the right way to spell them, etc. 

This task may be as simple as adding better documentation for the environment variables but I think there should at the very least be a forcing function to make sure it gets updated when new env variables are added. Maybe we have to add them to a file somewhere that autogenerates documentation similar to the logging repo. We could also write a small script that asks you whether or want to enable or disable various flags and then generates the right .env file for you. 

One thing this is a pain point is how you have to have these files in each application's repo and it's also hard to remember where the right place for the right flag is.

**Comment by carolinemodic** [comment]
@eventualbuddha Would it be possible to just have one shared env file people can maintain at the root level of vxsuite that all of the apps know to read in from? I feel like its a little confusing and hard to manage right now which flags are available in different apps, and some like the disabling card reader check have the feature config code living in a shared directory like libs/ui and then can apply to multiple different frontends.  

I guess I'm imagining if we have just one .env file then we could put all of the code to define different feature flags in one shared locations (maybe utils or a new sub repo) and there could be a little script in there that could auto-generate a .env file for you after asking you what things you want to enable, or at least autogenerate documentation of the available flags. 

This would also make VxDev's interaction with feature flags a bit simpler as VxDev would just have to copy its config file with flags to one spot.

**Comment by eventualbuddha** [comment]
The simplest way to have just one `.env` file would be to use symlinks. Or we could change the frontends to look up the directory tree to keep one at the root.
