### ISSUE TITLE
VxScan: update blank ballot screen copy

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2476]
This message could be better in the future.  Instead of "Your votes will count, even if you leave some blank", it should say something like, "No votes will count on this ballot, make sure you filled in the bubble next to the candidate(s) of your choice" or something more succinct ;)

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/CJU9MSC6S/p1661356906848319?thread_ts=1661356906.848319&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Blank ballot now has specific copy.
