### ISSUE TITLE
VxScan: can delete ballot data/unconfigure before saving backup

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2491]

**Comment by arsalansufi** [comment]
Update: This is actually working fine for election managers:

<img width="400" alt="election-managers" src="https://user-images.githubusercontent.com/12616928/187478577-64b53729-7c1e-4943-9835-4e1c50eb8a67.png">

We intentionally don't gate when the machine is in test mode, which was the source of confusion here.

And for system admins, we decided that the lack of a gate was okay (and that if we were to gate we'd want to add the backup button to the sys admin screen).
