### ISSUE TITLE
Use Shared Button Component in All Apps

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#2494]
We're currently using the Button component in all apps except `bsd`, after #2493 lands. We should try to standardize to have all our click/touch logic and styles in one place.

**Comment by adghayes** [comment]
Will be addressed by @kofi-q's VVSG design revamp now that we've decided in include `bsd`.

**Comment by kofi-q** [comment]
Thanks for calling out - ended up removing the centralscan-specific button and replacing with the libs/ui one, so this got resolved for free!
