### ISSUE TITLE
VxScan: unblock Greg to high volume scan 19" ballots

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2500]
Greg needs to be able to test the paper path / ballot box capacity of a large volume of ballots. He has a Surface Go and a Plustek scanner, and could follow steps to image the device if documented for him.

His desired VxScan functionality as it differs from our software today:
1. Scanning of blank paper. For rapid testing, he needs software that will just accept any piece of paper and not interpret the ballot.
2. Support for 19" ballots. Our current software does not support this.
3. Even though we won't be doing interpretation, he'll still need the ability to test rejections of ballots as well.

Note: it is possible to coordinate ballot printing of 19" ballots, but it is just much more logistically difficult to support so blank ballot scanning would be preferred.

**Comment by eventualbuddha** [comment]
Does the plustek scanner not do 19"? It just scans until it can't anymore from what I've seen.

**Comment by mattroe** [comment]
@eventualbuddha I haven't actually tested this. According to [spec](https://plustek.com/us/products/customized-scan-modules/vtm300/spec.php), it supports up to 23" sheets. I was told from someone that our software doesn't support this right now though for larger ballots, but maybe that is irrelevant if interpretation is disabled?

**Comment by eventualbuddha** [comment]
I think it'd be irrelevant. Maybe there's something else that'd fall down, but I think we'll get a 19" sheet fed through and get an image back just fine.

**Comment by mattroe** [comment]
thank you @benadida for shipping this super quickly!
