### ISSUE TITLE
[VxDev] Could be useful if there is a way to make anything that prints to an IRL printer instead just save as a PDF in VxDev: https://votingworks

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2502]
Could be useful if there is a way to make anything that prints to an IRL printer instead just save as a PDF in VxDev: https://votingworks.slack.com/archives/CEL6D3GAD/p1661887967753119

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/C03C0DZL021/p1661901862482639

**Comment by adghayes** [comment]
completed
