### ISSUE TITLE
Implement poll worker card PINs

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2524]
VVSG requires that all authentication implements MFA, which is met through smart card PINs today. We decided to not implement this for poll workers initially as we determined it to be unnecessarily arduous for our customers. The language of VVSG states the system "must be capable of", which suggests that this can be an optional configuration for administrators.

VVSG 11.3.1-B.4: At a minimum, the voting system must be capable of using multi-factor authentication to verify a user has authorized access to perform critical operations, including: At a minimum, the voting system must be capable of using multi-factor authentication to verify a user has authorized access to perform critical operations, including: *changing device states, including opening and closing the polls*

Before creating smart cards, a system administrator should have the option of enabling poll worker PINs in VxAdmin. Cards programmed with this option enabled should be programmed with PINs in the same manner as Election Manager cards.

**Comment by kofi-q** [comment]
@mattroe - is this a setting we should make consistent across all cards for a given election? Or would we allow an admin to enable/disable poll worker PINs at any point between programming the cards?

**Comment by mattroe** [comment]
@kofi-q As we discussed synchronously:
- a user will not want to change this within an election (and should probably not be allowed to)
- administrators will most likely keep the same setting across all elections
- this could be a VxAdmin-device-level setting with some of the additional device-level auth settings we'll need to implement
