### ISSUE TITLE
VxMark: a11y control behavior review

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2533]
Also the accessible controller interface is pretty unintuitive to me. The fact that the left and right buttons advance screens no matter what state the current screen is is a little difficult to deal with. For instance, on the write-in dialog, if you accidentally hit the right button the write-in session is cancelled and we jump straight to the next contest with no confirmation or anything. I'm curious to know if we've dug into this more and if that's expected behavior.

Issue automatically created from slack feedback reported by bernhard 
https://votingworks.slack.com/archives/CJU9MSC6S/p1662502759912279?thread_ts=1662502759.912279&cid=CJU9MSC6S

**Comment by mattroe** [comment]
covered by other issues
