### ISSUE TITLE
WIA: clarify write-in counts for official candidates

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2588]
The count of write-ins for a given official candidate cannot be found in the current reporting format. @beausmith discussed a solution to modify the write-in report to include this with an explanation that they are already tallied on the main tally report.

**Comment by adghayes** [comment]
We have decided to not move forward with this, at least for now: https://votingworks.slack.com/archives/CEL6D3GAD/p1664396264766649
