### ISSUE TITLE
nh-pilot detailed logistics

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2610]

**Comment by carolinemodic** [comment]
- October 14th: Code Freeze
- October 17th - 19th: QA 
- October 20th-21st: Installs
- October 24th: Shipping 

This would have the machines in NH by October 27th which is the earliest they may want to do L&A if that ends up being later we may have some more time.

**Comment by mattroe** [comment]
Will finalize next week, but tentative plan is 31st and 1st for L&A so this timeline should work well. L&A would not be sooner than later the week of the 24th.

**Comment by carolinemodic** [comment]
Timeline is finalized @mattroe will followup with more detailed logistics.

**Comment by mattroe** [comment]
plan of record: https://docs.google.com/document/d/1S1XHJ38yY6yq_tQG7Mt4yWBYkFA7MMkHxCJqh_8KRW0/edit#

still some open questions, but they should all be highlighted in the doc so closing out this issue
