### ISSUE TITLE
use real short IDs for transcriptions rather than UUIDs

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2612]
Since we want to display them to the user for possible livestream/projection so observers can refer to specific transcriptions by a ~4-6 character ID. Right now we're using a UUID but just slicing it, which doesn't guarantee uniqueness.

@mattroe to prioritize and clarify requirements

**Comment by adghayes** [comment]
Closing as we don't have transcriptions independent from adjudications anymore, and short adjudication IDs is covered in #2664.
