### ISSUE TITLE
V2 VxAdmin: ballot package export will occasionally not complete and white screen will flash 

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2616]
## Description
Warren County is reporting that their general election ballot package will not always save and show a white screen.

Slack discussion: https://votingworks.slack.com/archives/C03GUQNPD7X/p1664465636124789

## Repro
1. load the election definition in this ballot package: https://votingworks.slack.com/archives/C03GUQNPD7X/p1664466188875329?thread_ts=1664465636.124789&cid=C03GUQNPD7X
2. save the ballot package to USB drive
3. repeat until reproduces (took 5 times on my first reproduction attempt)

**Comment by adghayes** [comment]
Closed because we will not address v2 issues. Rather, we will upgrade v2 to v4.
