### ISSUE TITLE
nh-accuvote: hide precinct vs. absentee counts

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2631]
We don't have a mechanism of distinguishing precinct vs. absentee ballot counts when scanning accuvote ballots and therefore are misrepresenting on tally reporting absentee vs. precinct ballots.

When in accuvote-converter mode, we should not show:
- Precinct vs. absentee on tally reports - in both VxAdmin and VxScan reports
- The reports by voting method section on the reports page

**Comment by carolinemodic** [comment]
@eventualbuddha Do you mean adding something to the election definition for can distinigush ballot type? 

@kofi-q For context here in VxAdmin there are various reports, you can see on the reports tab that all have a box at the top showing the total number of ballots that are "precinct" ballots or "absentee" ballots, we just want to remove that box entirely for all of the reports. Separately on the reports page in VxAdmin there are reports and a table that break down the tallies by precinct/absentee voting method and we should hide that table. 

VxScan also prints a polls closed and polls open report that has the same box (and general layout) as the VxAdmin report so we will want to remove the box there too, figuring out how to test that part might be a bit trickier so I would start with the VxAdmin pieces.

**Comment by eventualbuddha** [comment]
Doesn't have to be in the election definition. Can still ultimately be checking for `gridLayouts`, but I just want to have a function called something like `canDistinguishPrecinctAndAbsenteeBallots` to make it so we can change how we make that decision later.
