### ISSUE TITLE
scan: add tooling for inspecting a workspace

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2635]
We need to have better tooling in place for inspecting scanned ballots. Right now only I (and sort of @benadida) are set up to do it, but it should be something other engineers plus @mattroe can do. I think we can get something basic going in a few days. Prototype screenshot:

![localhost_5173_](https://user-images.githubusercontent.com/1938/194366492-16bd9e5b-ee6b-434b-b275-79ced6ce9998.png)

Includes both sides of a sheet, each detected mark, its score, where it expected the bubble to be (blue) and where it decided the best match is (green).

**Comment by adghayes** [comment]
We mostly have this with the CLI, and are discussing exposing it more broadly in a browser. Should track separately if we commit to that more user friendly tool.
