### ISSUE TITLE
NH: conversion of constitutional questions yields the same title for each

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2643]
We just [hardcode](https://github.com/votingworks/vxsuite/blob/b3b77baaf3c0b45e273668763c69034bc6993aa1/libs/ballot-interpreter-nh/src/convert.ts#L786-L787) the section and title to "Constitutional Question Question". The order is preserved, but the reports don't distinguish between them usefully:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1938/194914176-90da0262-a582-4954-a139-f2f13c5e8201.png">

We can use some of the other information in them, but the titles may be [long](https://github.com/votingworks/election-definitions/blob/dcd4ec89d1f651c657797cf12ba55a56b6d203ce/2022-11-08-nh-general/ashland/election.json#L370-L378):

```json
      "description": "Are you in favor of amending articles 71 and 81 of the second part of the constitution to read as follows:\n\n[Art.] 71. [County Treasurers, County Attorneys, Sheriffs, and Registers of Deeds Elected.] The county treasurers, county attorneys, sheriffs and registers of deeds, shall be elected by the inhabitants of the several towns, in the several counties in the State, according to the method now practiced, and the laws of the state, provided nevertheless the legislature shall have authority to alter the manner of certifying the votes, and the mode of electing those officers; but not so as to deprive the people of the right they now have of electing them. [Art.] 81. [Judges Not to Act as Counsel.] No judge shall be of counsel, act as advocate, or receive any fees as advocate or counsel, in any probate business which is pending, or may be brought into any court of probate in the county of which he or she is judge.\n\n(Passed by the N.H. House 294 Yes 43 No; Passed by Senate 21 Yes 3 No.) CACR 21"

      "description": "Shall there be a convention to amend or revise the constitution?"
```

@mattroe let me know if you need more information to make a call here.

**Comment by mattroe** [comment]
As discussed in slack, we should find a solution to disambiguate multiple constitutional questions. Can be as simple as a numeric distinction: `Constitutional Amendment Question 1` vs. `Constitutional Amendment Question 2`
