### ISSUE TITLE
VxScan: printed additional open/close reports are blank

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#2644]
## Description
In testing the "Print Additional Polls Opened Report" feature initially added in https://github.com/votingworks/vxsuite/pull/2617, it appears that it prints blank pages. I tested in macOS Chrome, not `kiosk-browser`.

## Repro
1. Start VxScan.
2. Load any election (I used [this one](https://github.com/votingworks/election-definitions/blob/dcd4ec89d1f651c657797cf12ba55a56b6d203ce/2022-11-08-nh-general/newington/election.json), but I don't think it matters).
3. Insert poll worker card and open the polls.
4. Note the printed report is as expected, i.e. has zeros but is not blank.
5. Trigger "Print Additional Polls Opened Report" button.
6. Note the printed report is a completely blank sheet.

## Expected behavior
The additional printed reports should be the same as the first.

## Screenshots
https://user-images.githubusercontent.com/1938/194916483-9bb90359-b401-427d-b311-dcaa8f258c2d.mov

**Comment by carolinemodic** [comment]
Tested this in VxDev and it appeared to work fine for the polls closed report.

**Comment by carolinemodic** [comment]
Added to QA checklist to make sure we test when locked down
