### ISSUE TITLE
Show "Wrong Election" screen in VxScan when nh-accuvotes from wrong elections are scanned

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2647]
These ballots are not accepted today but are rejected with a generic "No ballot counted" error rather then the specific "Ballot for wrong election scanned" error screen we have for our own ballots. Can we use the timing mark bar code on the bottom of the ballots to determine this information?

**Comment by adghayes** [comment]
I believe we are also solving this by just putting QR codes on NH ballots. cc @mattroe @eventualbuddha
