### ISSUE TITLE
VxAdmin: loading a cvr for the wrong election is not rejected

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2680]
Tested on NH elections. Steps to reproduce:

1. Program VxAdmin for Test Ballot
2. Import a CVR for Ashland
3. Total CVR count is shown as 0, reports are shown as 0, but the CVR is loaded
4. Write-in tab is populated with adjudication available. No write-in images are shown though.

Expected behavior: CVR should be rejected for not matching the election.

**Comment by carolinemodic** [comment]
Adding that if the election is only slightly wrong, same contests but different scan thresholds for example, it will import the tallies of the wrong cvr file as well. This can only happen if you manually select the file.

**Comment by mattroe** [comment]
closing in favor of https://github.com/votingworks/vxsuite/issues/2716
