### ISSUE TITLE
Allow Polls Suspension on VxScan

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#2683]
See the [Tech Spec](https://docs.google.com/document/d/15mSk4QPQUqsLlHFwF5Dw058OsprmoJixwxm7C2GmGGk/edit?usp=sharing) for the overall [roadmap item](https://github.com/votingworks/vxsuite-roadmap/issues/37).

Implement polls suspension on VxScan, including:
- Creating Polls State type(s)
- Managing polls state on the "backend"
- Updating poll worker screens
- Updating idle screens

This chunk of work will not update the printed reports or reports saved to the tally, which is tracked in a separate ticket.

**Comment by adghayes** [comment]
cc @mattroe @beausmith 

[vxscan-polls-pause-flow.webm](https://user-images.githubusercontent.com/37960853/197843805-99f10c81-8976-41d5-8268-a16548536ffb.webm)

**Comment by mattroe** [comment]
Overall flow LGTM. A few specific thoughts:

- We should use a distinct pause symbol icon on the main "Polls Paused" screen instead of the same polls closed icon
- Nit: would prefer "Voting is" instead of "Voting has" -- maybe "Voting is complete."?
