### ISSUE TITLE
Update Polls Reports for Suspension

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#2686]
See the [Tech Spec](https://docs.google.com/document/d/15mSk4QPQUqsLlHFwF5Dw058OsprmoJixwxm7C2GmGGk/edit?usp=sharing) for the overall https://github.com/votingworks/vxsuite-roadmap/issues/37.

Update the polls open report to:
- Include titles and metadata relevant to polls suspension
- Have different report format for polls suspension and unsuspension, which only includes ballot counts in addition to metadata

**Comment by adghayes** [comment]
@mattroe @beausmith @ginvdr I'm just taking a stab in the dark here on design, let me know what you think.

![paused_report](https://user-images.githubusercontent.com/37960853/199318348-153cd6fe-7871-4229-af4b-2e41014d2f5b.jpg)

![unpaused_report](https://user-images.githubusercontent.com/37960853/199318354-226533c4-0919-435e-a65b-ab13a0740234.jpg)

**Comment by mattroe** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/1476320/199322835-d9752560-0f29-4445-b51b-2a50882b0fb7.png">

Posting the old style just for reference.

**Comment by mattroe** [comment]
My feedback:
- Move the ballot scanned count to the top. It's the most important important information. Design preference to remove the border.
- Remove redundant metadata that's in the footer. We can add the "from Paused" into the first header metadata timestamp.

**Comment by adghayes** [comment]
rev2 @mattroe @beausmith, check out this hot left-only border for the ballot count

![paused_report_rev2](https://user-images.githubusercontent.com/37960853/199360737-9b1ed571-181c-471f-a99a-bcaceaf39a8c.jpg)
![reopened_report_rev2](https://user-images.githubusercontent.com/37960853/199360740-f58bc172-f15e-413a-8435-682d1f19e262.jpg)

**Comment by mattroe** [comment]
Second version LGTM!

**Comment by beausmith** [comment]
LGTM. The new hotness left-side only border leaves me with more questions than the full box design does. I like that the full box really draws attention to the most important part of this report that needs to be checked against other reports for a match. I suggest that we use the full box (optionally with a small `border-radius`) or no box and simply the larger text.
