### ISSUE TITLE
VxScan/Admin: CVRs are exporting as live mode regardless of the testing vs. live mode of the machine 

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2703]
Exporting CVRs in testing mode and then importing to VxAdmin shows that they are live mode CVRs. The files themselves seem to have the proper TEST__ prefix in the filename, so it seems like an issue on VxAdmin potentially?

**Comment by eventualbuddha** [comment]
Do they have `"_testBallot": true`?

**Comment by carolinemodic** [comment]
Look like no: https://votingworks.slack.com/archives/C02Q3M874SV/p1666135634602069?thread_ts=1666123893.433989&cid=C02Q3M874SV

**Comment by eventualbuddha** [comment]
This seems not to be fixed. See [this Slack thread](https://votingworks.slack.com/archives/C02Q3M874SV/p1666192691204109).
