### ISSUE TITLE
VxScan: first mode change to live requires reboot

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2705]
## Description
After first configuration, the first mode change to live mode hangs indefinitely on a loading screen. The mode change takes effect after reboot and this issue does not persist across future mode changes or reconfigurations.

## Repro
1. Configure VxScan
2. Change test to live mode
3. See Loading screen hang
4. Kill app or restart device depending on dev or prod setup
5. Mode change takes effect
6. Make future mode changes successfully

## Expected behavior
The mode should change without killing/restarting.

**Comment by eventualbuddha** [comment]
Which election/ballot package did you use?

**Comment by mattroe** [comment]
@eventualbuddha this was reproduced using the nh-demo test ballot. Converted from: https://github.com/votingworks/election-definitions/tree/main/2022-07-12-nh-demo

**Comment by eventualbuddha** [comment]
I was unable to reproduce with that election or any other. I tested in my VM, so it's not exactly the same environment. I don't have a Surface Go 2 so I can't try with that, but I can try testing with a Lenovo laptop (BMD).
