### ISSUE TITLE
VxAdmin: Connect WIA to CSV results export

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2731]
Post-adjudication data is currently not in the CSV results export, which we decided to originally not include in scope.

The CSV results format does not need to be modified, the data just needs need to be updated after adjudication to reflect the data in the results export file. This does not apply to the SEMS export CSV.

**Comment by kofi-q** [comment]
**[Postponed]**

This should technically be a no-op, based on the proposed implementation plan for https://github.com/votingworks/vxsuite/issues/2738, but leaving this open to make sure we verify it's fixed as part of that work.
