### ISSUE TITLE
Investigate + Implement Print Timeouts tied to Print Jobs

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#2761]
It should be possible, by polling the CUPS server, to know when a print job is finished. And to get the print id by using `lp` instead of `lpr. Then we can have realistic print timeouts rather than constantly estimating. We may discover something unusual about `lp` or CUPS, however, so it's not guaranteed this will be possible or, if possible, superior.

**Comment by adghayes** [comment]
[Print Error Handling Brief](https://docs.google.com/document/d/1yel9Uhocss3V8Vsm1ZCEd1WiSGfT6Gfy4Hqety480-8/edit#heading=h.l87vj5e4w9j5)

@adghayes did the investigation to find that it is possible to tie print timeouts tied to jobs, but it opens up the larger and more important question of how to handle printing errors. We are now tracking that in votingworks/vxsuite-roadmap#86.

@carolinemodic I made some changes in `kiosk-browser` which are mergable to `kiosk-browser`. Should I polish that up and try to merge it while it's fresh? It's work that should be mostly independent of printer, approach, etc.

Otherwise, will close this issue.

**Comment by carolinemodic** [comment]
@adghayes is this still relevant?

**Comment by adghayes** [comment]
Given the printing inconsistencies we've had reported by Warren County in the latest election, I think print reliability work is still important and this would be a part of that.

**Comment by adghayes** [comment]
Closing as this seems specific to v2 ballot printing and we're not going to address it - we're going to upgrade v2 to v4.
