### ISSUE TITLE
Refer to Official/Test Ballots instead of Live/Test Mode

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2783]
The apps inconsistently refer ballot type (official/test) and mode (live/test). Copy across all apps should consistently refer to ballot types (official/test).

Slack discussion: https://votingworks.slack.com/archives/CEL6D3GAD/p1668619331313739

**Comment by adghayes** [comment]
@kshen0 should this issue be closed?

**Comment by kshen0** [comment]
Closed, thanks for flagging
