### ISSUE TITLE
WIA: adjudicate write-in mark as undervote

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2808]
When a voter marks a write-in bubble, but writes no candidate name, there is currently no product flow allowing the user to properly adjudicate this mark as an undervote.

### Suggested Implementation

- Add a persistent `Undervote` selection in the transcription screen view for a user to select when no write-in content is present, but the write-in bubble is filled.
- Count these ballots as a Undervote in post-adjudication tally reporting.

Open question: should we show the count of Undervotes adjudicated on the adjudication table screen? It is not strictly necessary to meet this requirement, but it provides additional visibility into the results of adjudication. The UX on the adjudication screen may become a bit confusing where you have an unmodifiable/unmappable `Undervote` option included in the table though.

**Comment by kofi-q** [comment]
[Postponed]

This has some overlap with https://github.com/votingworks/vxsuite/issues/2738 WRT data schema and UI display/report generation logic, so we're going to roll this into the tally computation refactor work and spec out a combined solution to address each edge case.

**Comment by adghayes** [comment]
Closed as part of #3417
