### ISSUE TITLE
Editing the number of seats crashes election-manager

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#281]
In the GUI for editing the election definition, pick a contest and edit the "seats" field:

- if you select the number "1" and replace it in one keystroke with "3", it's fine
- if you delete the number "1" with the intention of then typing "3", it crashes before you can type 3. I imagine this is because the empty string is not a valid integer.

**Comment by beausmith** [comment]
FUN!

**Comment by mattroe** [comment]
will tackle as part of election definition creation project if/when we get there
