### ISSUE TITLE
Investigate test failure in libs/ui/set_clock

### ISSUE THREAD

**Issue by kofi-q** [votingworks/vxsuite#2825]
Noticed a fast-check failure in this test - https://app.circleci.com/pipelines/github/votingworks/vxsuite/6690/workflows/7f66e9d1-5090-455c-9679-61aa58c3c87b/jobs/163905/tests#failed-test-0

Needs investigation/potential fix

**Comment by adghayes** [comment]
I believe we've fixed this in our flaky test management.
