### ISSUE TITLE
VxMark: inconsistent capitalization of “Polls Opened Report”

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2830]
VxMark: inconsistent capitalization of “Polls Opened Report”. in particular, with it being all lowercase in the message body it reads weirdly

Issue automatically created from slack feedback reported by brian 
https://votingworks.slack.com/archives/CJU9MSC6S/p1660781623528039

**Comment by adghayes** [comment]
The screen this was reported on is no longer a part of VxMarkOld, or will not be in v4.
