### ISSUE TITLE
VxScan: review screen pluralization

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2831]
The copy in the undervotes dialog doesn't really make sense when there is more then one undervoted contest. It pluralizes contest but then only lists the first one. 

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1662593976197689

**Comment by adghayes** [comment]
Resolved by previous work and confirmed in copy pass.
