### ISSUE TITLE
VxScan: investigate override mark thresholds please wait bug

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2832]
VxScan: After you override mark thresholds when you remove the election admin card there is briefly, strangely, the “Please Wait ballot is scanning” screen before it clears back to “Insert your ballot” (saw this with a NH election not sure if its a NH specific issue)

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1665442315057289

**Comment by adghayes** [comment]
We no longer have threshold overrides.
