### ISSUE TITLE
All app and report copy should align on consistent `Official` or `Live` copy for non-test ballot scanning modes

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2834]
All app and report copy should align on consistent `Official` or `Live` copy for non-test ballot scanning modes

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/CJU9MSC6S/p1666280698826849

**Comment by adghayes** [comment]
I think this was closed by @kshen0.
