### ISSUE TITLE
VxScan: persistent additional report printing function

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2839]
I know we just decided not to do this with sus-polls but I still think we should provide a way to print extra report copies from the pollworker screen to help this situation (after polls open before any ballots are cast, or after polls closed) : https://votingworks.slack.com/archives/C02Q3M874SV/p1667912860296459?thread_ts=1667912600.790539&amp;cid=C02Q3M874SV

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1667931764800919?thread_ts=1667931764.800919&cid=CJU9MSC6S

**Comment by mattroe** [comment]
https://github.com/votingworks/vxsuite/issues/4015

**Comment by mattroe** [comment]
* Add a new pollworker action button in the menu behind `No`
* When selected, the previously printed report should print similar to the behavior of "print additional reports" button
* The action should be disabled in the cases where reports should not be printed. Specifically, additional reports should not be able to be printed when polls are open and ballots have been cast.
* In other states, all the relevant previously printed reports (open, paused, closed) should be able to be reprinted.
