### ISSUE TITLE
kiosk-browser: remove old USB mount directories

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#284]
When we unplug a USB stick and plug it in again, we still have the old USB mount directories present, which is confusing in the custom file picker UX.

**Comment by eventualbuddha** [comment]
I have not been able to reproduce this. When I plug in a USB stick I get it mounted at `/media/usb-drive-sdb1`. When I unplug and re-plug it, it is mounted at the same place. What behavior are you seeing?

**Comment by benadida** [comment]
I wonder if it's a production machine issue. I'll try to repro.
