### ISSUE TITLE
VxAdmin: provide election managers ability to track CVR loading progress

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2840]
Numbering the CVR files in VxAdmin would be a big help for bigger counties.

Issue automatically created from slack feedback reported by ben 
https://votingworks.slack.com/archives/CJU9MSC6S/p1667962267703249?thread_ts=1667962267.703249&cid=CJU9MSC6S

**Comment by adghayes** [comment]
We do number the CVR files now. Also closing this in favor of #1939.
