### ISSUE TITLE
VxCentralScan: investigate unreadable ballot bug

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2842]
Lynn is actually running into a VxCentralScan issue I’ve never seen before where a problem ballot that is torn is stopping the Fujitsu, but VxCentralScan does not recognize it as unreadable and thinks that the scanning of a batch is still in progress.

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/CJU9MSC6S/p1669771827988059?thread_ts=1669771827.988059&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Adding v2 label and closing. Not sure this is relevant to v4.
