### ISSUE TITLE
Determine max report size for JavaCards

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2849]

**Comment by arsalansufi** [comment]
Looked into this last week and posted the following findings in Slack:

> The max I can store in a single data slot seems to be 2^15 bytes or ~32KB. We can of course split data across multiple slots to exceed that limit. I've been able to load data to capacity into 3 slots, so 32KB * 3 = **96KB**. I get card OS errors when I try a 4th slot.
>
> It takes about 7.5 seconds to load 32KB into a single slot. To get to **50KB**, I need to load 32KB into one slot and 18KB into another. That takes about 7.5 seconds + 5 seconds = **12.5 seconds**.
