### ISSUE TITLE
VxCentralScan: ensure we don't detect phantom QR codes

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#2859]
When separating VxScan and VxCentralScan codebases, I encountered a test for ignoring phantom QR codes that seemed to pass for VxScan and fail for VxCentralScan. https://github.com/votingworks/vxsuite/pull/2822#discussion_r1037604710

We should look deeper into this failing test to make sure VxCentralScan does properly ignore phantom QR codes.

**Comment by mattroe** [comment]
@jonahkagan @eventualbuddha is this still relevant?
