### ISSUE TITLE
Provide signature function in all components

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2868]
## Summary

Once we have keypairs (#2864) on every machine, we need a way to sign data that can be used for signing files we write to disk, for signing VxQR results QR codes, and for signing LiveCheck QR codes.

**Comment by benadida** [comment]
currently, we have this function in `window.kiosk.sign` – we can keep it there for now.

This needs to be reviewed to match the spec of signature domain separation.

**Comment by arsalansufi** [comment]
We now have backend signing functions that live in `vxsuite/libs/auth`:

https://github.com/votingworks/vxsuite/blob/a726765605c74dc097e67f86ee28195eab4ec5b8/libs/auth/src/openssl.ts#L510

https://github.com/votingworks/vxsuite/blob/a726765605c74dc097e67f86ee28195eab4ec5b8/libs/auth/src/signatures.ts#L20

These functions are used for artifact authentication and Live Check:

https://github.com/votingworks/vxsuite/blob/a726765605c74dc097e67f86ee28195eab4ec5b8/libs/auth/src/artifact_authenticator.ts#L62

https://github.com/votingworks/vxsuite/blob/a726765605c74dc097e67f86ee28195eab4ec5b8/libs/auth/src/live_check.ts#L21
