### ISSUE TITLE
LiveCheck web app for verifying system integrity

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2869]
## Summary

A standalone web app at https://check.voting.works that is used to perform the challenge-based LiveCheck protocol with any VotingWorks component. This includes:
- generating a random challenge
- opening up the camera and scanning for a QR code
- verifying the QR code and displaying the verified data.

## Requirements

- static web content
- builds in the VotingWorks root certificate(s)
- mobile friendly
- very lightweight web content, loads fast.

## Non-Requirements

- desktop rendering is not necessary
- trying to work around lack of camera

**Comment by adghayes** [comment]
Closing this as the web app does exist. If we want to track particular work on the app, let's do that separately.
