### ISSUE TITLE
Fix Circle CI for kiosk-browser 

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2872]
@benadida do you have context on why this is broken?

**Comment by eventualbuddha** [comment]
Looks like this was the most recent passing CI build: https://github.com/votingworks/kiosk-browser/actions/runs/2626148980.

**Comment by benadida** [comment]
@carolinemodic I don't have context, no.

**Comment by eventualbuddha** [comment]
Also, kiosk-browser's CI is currently done via GitHub Actions, not CircleCI. Perhaps we should change that?

**Comment by adghayes** [comment]
Resolved.
