### ISSUE TITLE
VxAdmin: clarify races that are not included in tally report data

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#2873]
https://votingworks.slack.com/archives/C044XSX6NTY/p1672166127850839

Issue automatically created from slack feedback reported by roe 
https://votingworks.slack.com/archives/CJU9MSC6S/p1672875094831509?thread_ts=1672875094.831509&cid=CJU9MSC6S

**Comment by adghayes** [comment]
We dealt with this by only including the races on reports that are relevant - no more greyed out races.
