### ISSUE TITLE
Add security policy and/or instructions for reporting security vulnerabilities

### ISSUE THREAD

**Issue by cjerdonek** [votingworks/vxsuite#2916]
Not that I necessarily have one to report, but I was looking around to see if you had instructions and/or a preferred way to report security vulnerabilities, and I couldn't seem to find any. I also tried: https://www.voting.works/.well-known/security.txt. GitHub also has some different methods to help with this: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by arsalansufi** [comment]
Done! https://github.com/votingworks/vxsuite?tab=security-ov-file
