### ISSUE TITLE
Disable the auto-install-peers PNPM setting and manually add explicit peers where needed

### ISSUE THREAD

**Issue by kofi-q** [votingworks/vxsuite#2922]
While migrating from pnpm v5 to v7, we needed to enable the `auto-install-peers` config setting to maintain parity with our v5 setup. However, this setting slows down pnpm installs, now that they require checking for peer dependency requirements (what used to take ~8s now takes ~30s).

We'll need to add required peer dependencies explicitly for each package in the monorepo and potentially lock versions of some existing deps. Ran into issues that seemingly required code changes while attempting this earlier, so it might take a non-trivial amount of time to get things working properly.

**Comment by adghayes** [comment]
@kofi-q is this still relevant?
