### ISSUE TITLE
Consolidate dotenv env var logic

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#2964]
We currently repeat this logic in a number of places. To list a few:

- https://github.com/votingworks/vxsuite/blob/5cf6e3799241734a67f63b87663cd081b416ad73/apps/vx-mark/backend/src/index.ts#L11-L34
- https://github.com/votingworks/vxsuite/blob/5cf6e3799241734a67f63b87663cd081b416ad73/apps/vx-scan/backend/src/index.ts#L14-L37
- https://github.com/votingworks/vxsuite/blob/5cf6e3799241734a67f63b87663cd081b416ad73/frontends/election-manager/config/env.js#L17-L43

Let's consolidate this logic in a lib. If there are challenges with using shared code in frontend `config/env.js` files, let's at least consolidate for backend use.

**Comment by adghayes** [comment]
this is now consolidated in `libs/backend`
