### ISSUE TITLE
Wait for backend server before starting frontend server

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#3028]
When running `pnpm start` in any `apps/<app>/frontend` directory to start the app, the frontend and backend dev servers are started at the same time. This can lead to a race condition where the frontend starts first, tries to communicate with the backend, and fails. 

We should instead start the backend server first, make sure it's up, and then start the frontend.

Also worth checking to make sure this isn't an issue in prod as well.

**Comment by adghayes** [comment]
@jonahkagan @eventualbuddha I think we do this now?
