### ISSUE TITLE
Pare down openssl.cnf

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3111]
https://github.com/votingworks/vxsuite/pull/3106#pullrequestreview-1333884571

**Comment by adghayes** [comment]
@arsalansufi not sure if this is relevant

**Comment by arsalansufi** [comment]
@adghayes This was actually addressed as part of the recent FIPS compliance work! Rather than copying the default OpenSSL config into the auth lib and editing it, we now make use of includes, making it easier to identify the VotingWorks-specific parts of the config(s):

https://github.com/votingworks/vxsuite/blob/5e8e3f376a621076b41b42db2032aa07d7b2e9fe/libs/auth/config/openssl.vx.cnf#L3-L12

https://github.com/votingworks/vxsuite/blob/5e8e3f376a621076b41b42db2032aa07d7b2e9fe/libs/auth/config/openssl.vx-tpm.cnf#L1-L20
