### ISSUE TITLE
nh-interpreter: handle multi-sheet on one ballot style

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#3141]
If a town requires has multiple elections (ballot styles) and one of them requires multiple sheets

related discussion: https://votingworks.slack.com/archives/CEL6D3GAD/p1678739573505259

**Comment by eventualbuddha** [comment]
The interpreter now handles this, but the converter does not. That is, you cannot take multiple XML/PDF pairs and generate a single election definition with all of them. You can, however, generate one manually and use it to configure a scanner.
