### ISSUE TITLE
Prepare for Java Card use during NH pilot

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#3169]

**Comment by arsalansufi** [comment]
Relevant spec: https://docs.google.com/document/d/169VWj8W9AX2ir6T1fb9Tr3aEouJO9Ptt2MC8dzvN7FQ/edit?usp=sharing

**Comment by arsalansufi** [comment]
Relevant state of the world for NH: [NH Pilot Build Instructions](https://docs.google.com/document/d/1K_5XY94qi-zBljIJQhSFOIsO-hpmJIzWzGiNrB032sI/edit?usp=sharing)
