### ISSUE TITLE
BMD: sometimes "no printer connected" appears even if printer is connected

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#317]
may be an initialization condition. Resolved by unplugging / replugging in, so not the end of the world, but could be more robust.

**Comment by eventualbuddha** [comment]
Logs would help.

**Comment by eventualbuddha** [comment]
Any tips on reproducing this?

**Comment by benadida** [comment]
this was very consistent on the hardware when the BMD boots up with the printer already plugged in. Needed to unplug and replug.

**Comment by eventualbuddha** [comment]
Looks like this is a race condition. Here's how I reproduced it, though this may not be the only way:
- no printer is configured
- kiosk-browser starts
- kiosk-browser auto-configure of printer subscribes to devices list
- kiosk-browser starts loading USB devices
- BMD loads in kiosk-browser
- BMD subscribes to USB devices
- list of USB devices sent both to auto-configure and BMD
- BMD asks for printer info while kiosk-browser sees printer and starts configuring, if BMD wins then we see "No Printer Connected"
