### ISSUE TITLE
Grout: Update serialization logic to better support Dates

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3233]
Copying from https://github.com/votingworks/vxsuite/pull/3192#discussion_r1148012901:

> I encountered some interesting serialization bugs when I was using Dates. JSON.stringify automatically converts Dates to strings. So when I was using a Date type here, the type was inaccurate on the frontend, which was actually working with a string.

> I looked into updating Grout's serialization to handle Dates, but Grout's serialization special-casing works best for types that can't be serialized at all. Dates actually are serialized by JSON.stringify, so I'd have to do some guess work to gauge whether a value was originally a Date before it became a string but then run the risk of accidentally converting some values that were meant to be strings into Dates. I ultimately decided that finding a general solution was out of scope, so I switched to Unix timestamps in milliseconds instead. Will open an issue for this!

**Comment by eventualbuddha** [comment]
I think there’s a case to be made that we should use ISO-8601 strings or add support for `DateTime` from luxon which has a better API.
