### ISSUE TITLE
module-scan: stop storing whole template image in memory

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#335]
We only need the image of a bubble to compare with the scan. We're not doing marginal marks, and this will save us a lot of memory.

**Comment by benadida** [comment]
@eventualbuddha are we doing this already?

**Comment by eventualbuddha** [comment]
No, not yet. We've made progress, but we're still doing this.

**Comment by carolinemodic** [comment]
We don't use template images anymore
