### ISSUE TITLE
Ensure test keys and certs are regenerated when the relevant election def is changed

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3351]
If you edit `electionFamousNames2021Fixtures` in `libs/fixtures`, you need to re-run `./scripts/generate-test-keys-and-certs` in `libs/auth`. To avoid confusion, a CI check that makes sure that this command has been run would be helpful.

Relevant Slack thread: https://votingworks.slack.com/archives/CEL6D3GAD/p1682363799514749

**Comment by eventualbuddha** [comment]
Ideally such a check would run before the tests in `test:ci` since the Jest tests will fail.

**Comment by adghayes** [comment]
@arsalansufi not sure if this is still relevant

**Comment by arsalansufi** [comment]
@adghayes Now that election card certs use a stable election ID + date rather than an election hash, this should be less relevant. Previously, when a fixture used to create test election card certs was updated, the test election card certs were invalidated and needed to be regenerated. That should now only be necessary if the relevant election ID or date changes, which is highly unlikely:

https://github.com/votingworks/vxsuite/blob/5e8e3f376a621076b41b42db2032aa07d7b2e9fe/libs/fixtures/data/electionFamousNames2021/election.json#L2

So we're good to close!
