### ISSUE TITLE
hash of software version displayed in app

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#343]
we need a reasonable model for computing the hash of our executable code and displaying it in app.

Possibly compute it during `setup-machine.sh` and store it in the right location with permissions such that it can no longer be changed.

Display this hash in all component admin screens, as a version check.

**Comment by eventualbuddha** [comment]
Just sanity checking: is a git SHA okay as a first rev?

**Comment by eventualbuddha** [comment]
Passing off to @beausmith and @carolinemodic.
