### ISSUE TITLE
limit sudo privileges

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#3446]
## Description

In https://github.com/votingworks/vxsuite-complete-system/blob/main/config/sudoers

we've granted sudo permissions to `mkfs.fat` and other filesystem utils to `vx-ui`. That is likely a lot more than we strictly need to do. I'd prefer if we had a wrapper shell script that creates filesystems only on `/media` partitions, for example, and it would be much better if this could be on the server side so only `vx-services` has those limited permissions.

**Comment by adghayes** [comment]
@jonahkagan moved VxScan to `libs/usb-drive`. We need to move VxAdmin to `libs/usb-drive` which will involve adding the formatting functionality into `vxsuite`, at which point we can change these permissions. It will also move permissions away from `vx-ui` to `vx-services`
