### ISSUE TITLE
BMD: results compilation feature

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#346]
Problem: when "Happy Meal" BMDs each have their own printer, an unofficial precinct tally is difficult to generate, as each BMD prints its own report independently of others.

Let's build a "Results Compilation" feature as follows:
- once polls are closed after some votes have been cast. (Note this means that each BMD will have printed a polls closed report for its own votes... that's good for auditing, let's keep that.)
- poll worker card insert shows an option to "save tally to the card", which will write a tally data structure to the poll worker card.
- poll worker card insert into subsequent BMDs indicates "card contains results for machine IDs X, Y, and Z."  The same "save tally to the card" option exists.
- on any BMD with poll worker card inserted, a "print unofficial tabulation report" button should appear.
- when tapped, a modal dialog should prompt "just this machine" or "include other tallies saved on card"
- the appropriate unofficial tabulation report should print, including the list of machine IDs included in the report. Only the aggregate numbers, not per-machine. The report should ideally also include the time at which the results from each machine was saved (since polls were closed, it shouldn't make a difference, but it's one more helpful data point.)

NOTE: this will clearly *not* work for ranked-choice voting since we are not saving CVRs to the card. We'll have to figure out a solution for that when we get to it. But then again, ranked-choice voting and precinct counts don't mix either.

**Comment by benadida** [comment]
in the multi-printer model.

**Comment by beausmith** [comment]
After discussion with @benadida and @carolinemodic we've defined the following implementation:

Once polls are closed on a BMD with print mode enabled (Happy Meal and Print Kiosk) and when there is a Poll Worker card inserted, there is a section displaying a table of results which are currently on the card along with the results on the current machine. 

The table has two columns: "Machine ID", "Saved on Card At".

On the row of the current machine, there is a button "Save to Card" button in the "Saved on Card At" column. When clicked, it opens a modal to block user interaction while saving to the card. Once saved, the modal closes and the button on the row is replaced with the date-time the data was saved.

```
Machine Id                       Saved on Card At
001 (current machine)            [Save to Card]
002                              Mon, Jun 2, 2021, 3:25pm
```

Below the table of results is a button to "Print Combined Results Report from N machines". When clicked, it opens a modal which confirms:

> ## Print Combined Results Report
> 
> Do you want to print the combined results report from the 3 machines (001, 002, 003) and clear data from the card?
> 
> [Cancel] [Print Report and Clear Data]
