### ISSUE TITLE
Add logs to aid in debugging

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3484]
While we have logs in place for user-level actions as relevant to election officials, there are a few places that we could add logs to aid in lower-level debugging:

_Invalid/unprogrammed Java Cards_

https://github.com/votingworks/vxsuite/blob/0bb50ec41595eaf63da175be22bbc74640c42f66/libs/auth/src/java_card.ts#L399-L401

_Artifact authentication errors_

https://github.com/votingworks/vxsuite/blob/500e4d2f0b145ab752e4037d2c6affd6b9429315/libs/auth/src/artifact_authenticator.ts#L85-L90

**Comment by adghayes** [comment]
Closing due to outdatedness and lacking specificity.
