### ISSUE TITLE
Printed ballots report shows the wrong timestamp for election configured at

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3501]
Printed ballots report shows the wrong timestamp for election configured at.

I’m not sure if I did something weird with changing clock times (but I don’t think I ever had it set to 5pm) but the printed ballot report is telling me I configured the election at a time later then I really did? @ben can you see if these times look normal for you

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1684865838193219?thread_ts=1684865838.193219&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Going to close this as we don't have a printed ballots report now.
