### ISSUE TITLE
vxmark/scan: unable to unconfigure vxmark if the inserted usb drive has a ballot package on it

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3510]
it seems impossible to actually unconfigure VxMark as an Election Manager if the inserted USB drive has the ballot package in it. is this expected behavior?

Issue automatically created from slack feedback reported by brian 
https://votingworks.slack.com/archives/CJU9MSC6S/p1684954713470189?thread_ts=1684954713.470189&cid=CJU9MSC6S

**Comment by arsalansufi** [comment]
Need to repro this as it's old as it may no longer be relevant. If it's no longer relevant, we can close

**Comment by carolinemodic** [comment]
I feel like we fixed this by ejecting the usb when we unconfigure but will look into it

**Comment by carolinemodic** [comment]
Still happens on election-manager screen
