### ISSUE TITLE
VxAdmin: Handle BMD Write-Ins

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#3527]
## Summary

Currently VxAdmin does not have any handling of BMD write-ins. We had [a discussion](https://votingworks.slack.com/archives/CEL6D3GAD/p1683580468063749) on how we'd like to handle BMD write-ins. We'd like BMD ballots to have images, like HMPBs. Ideally these images are also zoomable on the contest in question, like HMPBs. In order to accomplish that, we'd have to have BMD ballot layouts calculated and exported with the BMD ballot images, which makes this a substantial project.

## Requirements

- Adjudicate BMD write-ins in existing VxAdmin write-in interface
- Include and show image of ballot for adjudication flow
- (Flexible) Enable zooming in on the BMD contest, as you can with HMPBs

**Comment by adghayes** [comment]
@mattroe and @adghayes discussed a few weeks ago with more specifics about scope. We will not enable any kind of zooming on the ballot. We _will_ show the ballot image, just without zoom. The voter transcribed value can be presented within the sidebar, with the administrator then selecting an adjudicated value (as they might for an HMPB ballot). Optionally, we may implement auto-selection if the transcribed value perfectly matches an adjudication option.

**Comment by adghayes** [comment]
Building and validating this feature requires scanning BMD ballots for `gridlayouts` elections, which is unfortunately broken on `main`: https://github.com/votingworks/vxsuite/issues/4659. This task is blocked on that issue. cc @arsalansufi

**Comment by arsalansufi** [comment]
Thanks for noting @adghayes! I think it's fine to put your focus elsewhere for now. Planning to have Brian address that issue more fully (pending CACVote timelines). There's also a quick fix that we can implement to unblock (try interpreting as an HMPB, catch if there's an error and try interpreting as a BMDB). It doesn't need to be you who does that, just documenting for our future selves.
