### ISSUE TITLE
Asus boot error

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#3567]

**Comment by arsalansufi** [comment]
I believe we determined that these errors are not cause for concern. From @benadida in Slack:

> I'm seeing the same error you saw on boot /caroline, and a little bit of research indicates this is a power-management incompatibility error between some kernel versions and some BIOS/UEFI. I don't see any relation to security, and so I think this is something we can safely ignore. We may be able to suppress the error message with an extra `acpi=off` kernel parameter, which is worth doing at some point, but not a blocker as best as I can tell.
