### ISSUE TITLE
Initiate a reboot after TTY2 options that require it

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3580]
Certain TTY2 actions render TTY1 in a funky state. We should initiate a reboot after they complete, in cases where we aren't doing so already.

- Recreating the machine cert
- Re-programming sys admin cards

**Comment by adghayes** [comment]
Currently we are pretty aggressively requiring reboot after most options, so I believe this has been addressed.

**Comment by arsalansufi** [comment]
@adghayes That's correct! I added some of the last few missing required restarts here: https://github.com/votingworks/vxsuite-complete-system/commit/6a9eb82d861ddf1d7312b13f44c91425d51d460f
