### ISSUE TITLE
WIA "Add" button is noticeably slow to react to input

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3582]
When entering write-in candidates in the adjudication flow, the "Add" button is noticeably slow to react to input. If it's a perf issue that scales with data size, it might be more pronounced with more CVRs/write-ins loaded (this test had 4 CVRs).

https://github.com/votingworks/vxsuite/assets/12616928/2920cc45-8728-4790-81d1-d9d1db97ff59

**Comment by kofi-q** [comment]
@adghayes - not sure, but I think some of your recent perf improvements address this case? Feel free to close if so!

**Comment by adghayes** [comment]
Good catch! I'm pretty sure it does.
