### ISSUE TITLE
VxScan: ELO 13 is unresponsive to touch briefly after idle state

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3588]
Both @kofi-q and I have seen this behavior. After that second or two, touch works fine. We've seen this with both usb-a-to-c and usb-c-to-c connections. @kofi-q hasn't noticed this behavior when the ELO is connected to his Mac/VM.

**Comment by mattroe** [comment]
https://votingworks.slack.com/archives/CEL6D3GAD/p1687515347205579

**Comment by benadida** [comment]
This is solved by a firmware update to the screen shipped to us by ELO.
