### ISSUE TITLE
VxAdmin can't load all-bubble-ballot election definitions, likely because of their size

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3592]
Trying to load any of the 3 all-bubble-ballot election definitions (https://github.com/votingworks/vxsuite/tree/main/apps/design/frontend/fixtures) triggers the default VxAdmin "Something went wrong" error screen.

The backend logs the following error:

```
[backend:run] PayloadTooLargeError: request entity too large
```

**Comment by adghayes** [comment]
I'm thinking we should do #3048  to fix.
