### ISSUE TITLE
VxScan: confirm & document Asus secure boot process

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#3617]

**Comment by benadida** [comment]
This works in the standard way, only one has to know how the ASUS BIOS presents things.

The BIOS option `OS Type` with values `Windows UEFI mode` or `Other OS` really means `Secure Boot` with values `on` and `off` respectively.

This is confirmed by ASUS's own documentation: https://www.asus.com/support/FAQ/1049829/

I've confirmed it experimentally.

So the process for setting up an ASUS machine is:
* `DEL` key to boot to BIOS
* set `OS Type` to `Other OS`  --> this turns off secure boot
* clear secure boot keys --> this puts it in setup mode to accept new keys
* boot from vx-iso
* write keys as per vx-iso
* when done imaging, reboot to bios
* set `OS Type` to `Windows UEFI mode` --> this turns secure boot back on
* reboot, voila
