### ISSUE TITLE
BMD: on precinct change, close polls

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#368]

**Comment by eventualbuddha** [comment]
What do you think of this, @benadida? Ignore the bad styling for now.

![image.png](https://zube.io/files/votingworks/53e8cdf8a2521923b893bbdf635828f3-image.png)

**Comment by benadida** [comment]
I'm not sure.... Closing polls in testing mode on a vxprint requires printing, which requires a printer connected... I can imagine an admin might need to just reset a machine to live life without a printer connected at that moment. Let me noodle on it some more.

**Comment by benadida** [comment]
OK, here's how this should work: change of precinct with admin card just closes the polls without any further action. It's not like we're forcing admin to close polls to unconfigure right now, so let's just keep it consistent. If later we want to further constrain this, we can, but don't see the need right now.

**Comment by eventualbuddha** [comment]
Consensus from meeting: admin can always unconfigure, but changing other things like precinct or test mode while polls are open are not allowed.
