### ISSUE TITLE
surface the machine jurisdiction somewhere in the UI, maybe even in an error screen for the wrong card

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3681]
surface the machine jurisdiction somewhere in the UI, maybe even in an error screen for the wrong card.

Issue automatically created from slack feedback reported by ben 
https://votingworks.slack.com/archives/CJU9MSC6S/p1688670518211329

**Comment by arsalansufi** [comment]
Related issue: https://github.com/votingworks/vxsuite/issues/3615

**Comment by arsalansufi** [comment]
Going to close this issue in favor of the other one
