### ISSUE TITLE
For our internal use, a script that reports the programmed state of a Java Card, e

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3690]
For our internal use, a script that reports the programmed state of a Java Card, e.g.

```
Root VotingWorks cert: [ Dev | Prod ]
User role:             [ System administrator | Election manager | Poll worker ]
Jurisdiction:          nh.test-jurisdiction
Election hash:         abcd1234 (if applicable)
```

Or

```
Unprogrammed or incorrectly programmed
```

Issue automatically created from slack feedback reported by arsalan 
https://votingworks.slack.com/archives/CJU9MSC6S/p1688759375684979

**Comment by arsalansufi** [comment]
Tackled in https://github.com/votingworks/vxsuite/pull/3775!
