### ISSUE TITLE
Autogenerate ballot PDF fixtures for manual testing usage from VxDesign

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3696]
So that people can manually test with ballot images autogenerate pdfs and store them in fixtures (or somewhere appropriate) from fixture elections. Perhaps just famous names and/or minimal exhaustive to start. Ideally also generate some marked pdfs for adjudication reasons so that you can easily test all adjudication types.

**Comment by jonahkagan** [comment]
These exist in libs/hmpb
