### ISSUE TITLE
Election Manager: add ability to generate PDFs for all the ballot types

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#370]
Doesn't need to be an official ballot package, useful for outsourced printing.

**Comment by eventualbuddha** [comment]
I think this needs more spec'ing. What should it actually contain?

**Comment by benadida** [comment]
The goal here is that we can easily generate a PDF for any ballot style + type (absentee vs. in-precinct, test vs. non-test).

A good first version would simply be a "save PDF" button in the single-ballot view, next to the "print" button.
