### ISSUE TITLE
Make sure we can save logs larger then 512mb

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3833]
I tried to get Lynn to save the VxAdmin logs but she ended up with this error message trying both formats. 

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/CJU9MSC6S/p1692138475270959?thread_ts=1692138475.270959&cid=CJU9MSC6S

**Comment by eventualbuddha** [comment]
We need to move [this](https://github.com/votingworks/vxsuite/blob/dffb657cad7f104fc8f2f345186eeea236dd33b2/libs/ui/src/export_logs_modal.tsx#L103) to the backend.

**Comment by adghayes** [comment]
Log exports have been moved to the backend so I believe this limitation no longer applies, but leaving this open until we confirm.

**Comment by mattroe** [comment]
closing until we repro in the vvsg logging project
