### ISSUE TITLE
scanners: investigate scanning performance improvements for mvcp

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3849]
Consider any scanning performance improvements we might want to make, if any, for mvcp.

**Comment by carolinemodic** [comment]
@jonahkagan can you write up what your idea was around not saving/loading the image?

**Comment by jonahkagan** [comment]
Another idea is to lower the two scan status polling intervals in VxScan. They are both currently set to 500ms. This means in the worst case there could be a 1s delay to begin a scan.
- VxScan's frontend won't initiate a scan until it knows that there's paper to be scanned, which it learns from the scan status endpoint. This polling can be either moved to the backend (now that auth status is located there, and we want to only initiate scans when the machine is in voter mode), or we can remove it entirely and move the logic for determining whether to initiate a scan or not into the state machine.
- The state machine's paper status polling observer also has an interval that we could potentially shorten.

**Comment by arsalansufi** [comment]
Closing this out as this is already captured in newer issues and current work
