### ISSUE TITLE
vxscan: state machine can get stuck on msd screen

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3891]
I tried to double feed one ballot right after the other and managed to jam the scanner with no recovery. I had to pull it out of the box (I like how it pulls out) but had to insert a poll worker card to get this error message to go away. 

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/CJU9MSC6S/p1693246675490209?thread_ts=1693246675.490209&cid=CJU9MSC6S

**Comment by mattroe** [comment]
closing in favor of other msd pdi issues
