### ISSUE TITLE
Introduce the ability to export all images, including images for ballots that weren't accepted, so that we can deprecate existing backup functionality

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3922]

**Comment by adghayes** [comment]
Does any of our backup tooling rely on the exported `db` file? Because we wouldn't be able to export that in the CVR export due to privacy concerns.

**Comment by arsalansufi** [comment]
@adghayes Good q! In this [Slack thread](https://votingworks.slack.com/archives/CEL6D3GAD/p1691523484960869), we reached the conclusion that the DB file isn't critical for any analysis. And given the privacy concerns that you mention, we have all the more reason to never export it. Another reason why we want to deprecate the existing backup functionality and consolidate on just one kind of export.
