### ISSUE TITLE
vxmarkscan: image creation / prod-specific issues

### ISSUE THREAD

**Issue by kshen0** [votingworks/vxsuite#3998]
Some special concerns eg. image must be < ~26 gb (need to confirm exact size)

- Screen is rotated
- Cursor needs to be hidden
- Interpretation is no-op
- Hardware daemons need to be run as services

**Comment by mattroe** [comment]
Just noting from the conversation this morning that disk image size doesn't need to be a constraint. We can image a 128GB SD card and use that with standard 110GB images.
