### ISSUE TITLE
WIA: visually clarify selected write-in

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#4025]
the write-in highlights are a little tall, so when there are two write-ins in a row, it could be hard to know for sure which one I'm transcribing. Two thoughts:
• we could make it less tall
• we could highlight in color the filled bubble that we identified, so there's clarity as to which one we're transcribing.

Issue automatically created from slack feedback reported by ben 
https://votingworks.slack.com/archives/CJU9MSC6S/p1682451531541429?thread_ts=1682451531.541429&cid=CJU9MSC6S

**Comment by mattroe** [comment]
https://votingworks.slack.com/archives/CEL6D3GAD/p1699987754781639?thread_ts=1699914454.155639&cid=CEL6D3GAD
