### ISSUE TITLE
VxScan: Add UI for log export

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#4035]
We don't have a way to export logs in VxScan right now like we do in VxAdmin and VxCentralScan we need to add that.

**Comment by kshen0** [comment]
Will need same button in VxMark and VxMarkScan, but less urgently (not for march-nh deadline), so add if trivial or make portable if not

**Comment by kshen0** [comment]
VxScan: https://github.com/votingworks/vxsuite/pull/4149

If urgency for Mark and MarkScan is still low, I'll do Mark and MarkScan on a day when I'm not in the bakery
