### ISSUE TITLE
Breaking out from the thread above but VxDesign seems buggy when removing empty candidate rows, I keep accidentally adding more candidates then I need to and then I get into a state where its impossible to remove the last empty row

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#4067]
Breaking out from the thread above but VxDesign seems buggy when removing empty candidate rows, I keep accidentally adding more candidates then I need to and then I get into a state where its impossible to remove the last empty row

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1696981753447599?thread_ts=1696981753.447599&cid=CJU9MSC6S

**Comment by adghayes** [comment]
@jonahkagan, I think this was fixed by your latest design revamp?
