### ISSUE TITLE
vxdesign: duplicate candidate IDs generated across contests

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#4068]
https://votingworks.slack.com/archives/CEL6D3GAD/p1696981239570269

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1696981706011659?thread_ts=1696981706.011659&cid=CJU9MSC6S

**Comment by jonahkagan** [comment]
Another issue with this form: If you have two candidates with the same ID, the form controls will affect both candidates. This is because we're using the contest ID in the `onChange` handlers for all of the form controls.
