### ISSUE TITLE
VxScan: unauthorized access alarm (v3.1)

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4136]
Software requirements:
- Alarm should only go off when in an activated state (polls open)
- If the alarm signal is sent, VxScan should show an error screen and emit an error sound. The same components on the existing VxScan error screen can be reused. As this will likely never occur in the field, we can reuse the same error sound, but will need to eventually measure the sound emission on the device to ensure it meets the VVSG volume requirements.
- To disable the active alarm, the screen should prompt a user to insert the poll worker card. Once inserted, the poll worker should click a button confirming to turn off the alarm. This implementation is the same model used in the v2 ballot bag swap.

**Comment by carolinemodic** [comment]
We should log when the alarm goes off and when its armed/disarmed by a user as well.

**Comment by mattroe** [comment]
out of scope
