### ISSUE TITLE
Preserving log integrity / review logging

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4138]

**Comment by carolinemodic** [comment]
See https://docs.google.com/spreadsheets/d/1WKDjI_WO_nPHTLwyMbzf1CcXnczzbMOSua-pyGSldDw/edit#gid=0 

Requirement 11.1-C and all subrequirements. I'm not sure we're configuring logrotate properly for this so we should review and make sure that we are.

**Comment by mattroe** [comment]
@amcmanus clarifying the specific events we need to make sure we log:

11.1-A: 
- failed and successful authentication
- all access control changes (card programming events)
- @arsalansufi should have already covered all of this in the auth project, but worth double checking

12.1-G:
- log when we switch to backup power (we currently don't do this and know it's a gap so don't worry about it)

13.2-B:
- log when the digital signature check of CVRs/ballot images fails
- @arsalansufi should have also covered this in the digital signature work, but worth double checking

**Comment by arsalansufi** [comment]
Confirming that 11.1-A and 13.2-B are in place!

11.1-A

- [Central system auth event logs](https://github.com/votingworks/vxsuite/blob/72c1e62c5d406891cb2aa3eb5a4fa1e2df5c24af/libs/auth/src/dipped_smart_card_auth.ts#L84-L172)
- [Precinct system auth event logs](https://github.com/votingworks/vxsuite/blob/72c1e62c5d406891cb2aa3eb5a4fa1e2df5c24af/libs/auth/src/inserted_smart_card_auth.ts#L56-L143)
- [Card programming logs](https://github.com/votingworks/vxsuite/blob/72c1e62c5d406891cb2aa3eb5a4fa1e2df5c24af/libs/auth/src/dipped_smart_card_auth.ts#L243-L330)

13.2-B

- [Ballot package signature check failure log](https://github.com/votingworks/vxsuite/blob/72c1e62c5d406891cb2aa3eb5a4fa1e2df5c24af/libs/backend/src/ballot_package/ballot_package_io.ts#L110-L113)
- [CVR import failure log, which includes signature check failures](https://github.com/votingworks/vxsuite/blob/72c1e62c5d406891cb2aa3eb5a4fa1e2df5c24af/apps/admin/backend/src/app.ts#L447-L452)

**Comment by amcmanus** [comment]
I have two Debian 12.2 vxadmin systems configured with the new logrotation configuration in place. One will remain powered on overnight, the other one has been powered off. Tomorrow, I'll confirm both machines rotate and new actions are correctly written to the latest log. I'll also test the tty2 log export since it supports wildcard exports, but I can't test the vxadmin log export until wildcard exports are supported in vxsuite.

**Comment by mattroe** [comment]
https://docs.google.com/document/d/1eZp2LMf8LzLW-YQhzceQi-vHHfQ27-uepK77mPwcrKc/edit

**Comment by amcmanus** [comment]
This is complete in `vxsuite-build-system` and `vxsuite-complete-system`. All that remains is a small change to `vxsuite`, tracked here: https://github.com/votingworks/vxsuite/issues/4152
