### ISSUE TITLE
Upgrade to Node 20 (or 18)

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#4163]
Node 16 is now EOL'd

**Comment by amcmanus** [comment]
This is no longer part of the nh-march-freeze. We will revisit afterward.

**Comment by eventualbuddha** [comment]
Node v22 is now current.

**Comment by eventualbuddha** [comment]
Slack thread from the last look at this: https://votingworks.slack.com/archives/CEL6D3GAD/p1700198455681619

**Comment by kofi-q** [comment]
All seems to be good in dev envs, CI, and on prod images (although prod's only tested on VxMark so far, but these should be fairly good signal). Will keep an eye out for anything that pops up that might be related and if I'm OOO while that goes down, the last two PRs linked above are the ones to roll back.
