### ISSUE TITLE
Switch from environment variables to system settings for the CAST_VOTE_RECORD_OPTIMIZATION_EXCLUDE_REDUNDANT_METADATA and CAST_VOTE_RECORD_OPTIMIZATION_EXCLUDE_ORIGINAL_SNAPSHOTS feature flags

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4234]
https://github.com/usnistgov/CastVoteRecords/issues/45

**Comment by adghayes** [comment]
@arsalansufi, if this is just to mean that we no longer use extensions, then this can be closed due to:

- #4450 
- #4447 
- #4430 

There are no longer any custom fields in our CVR spec.

**Comment by arsalansufi** [comment]
Thanks for checking on this! This is actually for the following, documented in the [roadmap issue](https://github.com/votingworks/roadmap/issues/190):

> Switch from an environment variable to a system setting for the [REACT_APP_VX_CAST_VOTE_RECORD_OPTIMIZATION_EXCLUDE_REDUNDANT_METADATA feature flag](https://github.com/votingworks/vxsuite/blob/31e23bc76e7f5905efed4c462299499b206ee880/libs/utils/src/environment_variable.ts#L41-L43), which is technically necessary for strict CDF compliance. (See https://github.com/usnistgov/CastVoteRecords/issues/45.)

**Comment by arsalansufi** [comment]
@adghayes Thanks for checking on this! I recall the above PRs - I'm just keeping this open for the following, documented in the [roadmap issue](https://github.com/votingworks/roadmap/issues/190):

> Switch from an environment variable to a system setting for the [REACT_APP_VX_CAST_VOTE_RECORD_OPTIMIZATION_EXCLUDE_REDUNDANT_METADATA feature flag](https://github.com/votingworks/vxsuite/blob/31e23bc76e7f5905efed4c462299499b206ee880/libs/utils/src/environment_variable.ts#L41-L43), which is technically necessary for strict CDF compliance. (See https://github.com/usnistgov/CastVoteRecords/issues/45.)

**Comment by arsalansufi** [comment]
The thinking being that we can't give SLI two VxScan images, one with the flag enabled for most testing and one with the flag disabled for checking CDF compliance. We're going to give them one image and use a system setting to toggle behavior for different tests. (Same for VxCentralScan.)

**Comment by arsalansufi** [comment]
Renamed the issue accordingly for clarity

**Comment by arsalansufi** [comment]
Also worth moving CAST_VOTE_RECORD_OPTIMIZATION_EXCLUDE_ORIGINAL_SNAPSHOTS to a system setting while we're at it. Will update the issue title
