### ISSUE TITLE
VxCentralSystem: New lenovo thinkpads flickering after initial boot

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#4298]
https://votingworks.slack.com/archives/C060FEVB2L8/p1701271238008359?thread_ts=1701222488.376589&cid=C060FEVB2L8

**Comment by amcmanus** [comment]
Secure Boot broke the solution. Investigating.

**Comment by amcmanus** [comment]
This is now fixed under both non-secure and secure boot.
