### ISSUE TITLE
VxCentral: boot screen error

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4411]
This issue refers to the Xorg errors about a screen not being found.

**Comment by amcmanus** [comment]
This is tentatively fixed. There is an additional bluetooth firmware error message that would be nice to eliminate. I have not investigated that yet.

**Comment by amcmanus** [comment]
Fix for the screen error has been merged to main in complete-system. The bluetooth firmware error has not been addressed.

**Comment by carolinemodic** [comment]
Bluetooth firmware also now addressed.
