### ISSUE TITLE
Tabulation reports should include number of seats for each contest

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#442]

**Comment by eventualbuddha** [comment]
Where do we put it on the report? @beausmith

**Comment by beausmith** [comment]
@arsalansufi - Here is my guidance…

- [ ] Logic: when a Candidate Contest has more than 1 seat, append the number of seats to the contest title using: `<Text as="span" small noWrap>({contest.seats} seats)</Text>`
- [ ] Ensure there is a space between the end of the contest title and the span.

The finished result should look like this:

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/28444/160925881-c455a8e1-a044-42db-85a0-6cbed1725d29.png">

My goals here:
- use typographic solution for simplicity.
- attempt to not cause the content to wrap (hence not placing # seats in the "ballots/overvotes/undervotes" line.
- associate the seats value with the title of the contest.

**Comment by arsalansufi** [comment]
Thanks Beau!
