### ISSUE TITLE
VxCentralScan: adjudication screen should be clarified

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#443]
Right now, our screen tries to be aligned with the Ms process, but because that process isn't consistent, it's not helpful. Instead, we should have the text describe the exact action that the *scanner* is taking, not the ones that the adjudication board will take. Specifically, using the term "duplicate ballot" is confusing.

So, the text should read:

----

## Overvote

The last ballot was not tabulated.

[Send to resolution board]

or

[Tabulate as is]

----

Instead of an upper-right-hand corner confirmation, clicking either button should pop up a modal.

In the case of send to resolution board, the modal should read:

----

You have chosen to send this ballot to the resolution board.

Please remove this ballot from the stack.

[Cancel] [I've removed the ballot]

----

In the case of "Tabulate as Is":

----

You have chosen to tabulate this ballot as is.

[Cancel] [Tabulate as is]

----

**Comment by mattroe** [comment]
@beausmith this got closed out at one point, but assigning back to you to:
1. Review copy of current implementation
2. Fix the padding on the left side of the screen that got lost in this update for the nh-demo

**Comment by beausmith** [comment]
I wanna fix this, but I can't get to the right screen. 😭
