### ISSUE TITLE
vxdesign: ballot style readiness reports

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4510]
1.1.2-J – Ballot style readiness reports
The voting system must provide the capability to produce pre-election reports that include:
1. the allowable number of votes in each contest;
2. the tabulation method for each contest;
3. the inclusion or exclusion of contests as the result of precinct splits; and
4. samples of all final ballot styles.

No VVSG testing assertions defined.

**Comment by adghayes** [comment]
Adding some context from synchronous discussion with @mattroe:

We'd like to, and plan to, implement this as an export from VxDesign. That makes the most product sense and requires the least amount of work (exporting from VxAdmin would require the election package to contain ballot PDFs). It could simply be a report added within the Ballot PDF export that operates as a manifest and readiness report.
