### ISSUE TITLE
vxscan: improve resiliency against skew

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#4578]
Improve resiliency against crazy skew situations

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/CJU9MSC6S/p1707252500947249

**Comment by carolinemodic** [comment]
Some ideas of guards where we should just reject as unreadable:
- Increase the number of timing marks we have to recognize on each side - does this apply to the top/bottom as well as left/right? If not it should. 
- Reject if the skew is over some percent - shouldn't happen often
- Reject if the top timing marks are way above any of the found left/right timing marks
- Look for the pixels where a bubble should be to be black in the bubble locations and reject if some percent of bubbles aren't above some threshold to avoid looking at bubbles in the middle of text.

**Comment by eventualbuddha** [comment]
> Test set to look at https://votingworks.slack.com/archives/CJU9MSC6S/p1707252693335049?thread_ts=1707252500.947249&cid=CJU9MSC6S

All the test set examples in this batch are now rejected with https://github.com/votingworks/vxsuite/pull/5015.

**Comment by eventualbuddha** [comment]
With #5015 I think we can call this done for now. Let's create specific tickets for issues that come up in future testing.
