### ISSUE TITLE
precinct scanner: new scanning APIs to monitor status and do precinct scanning

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#458]
Need to determine the right APIs from frontend to backend, which component maintains state on where the paper is. Likely the backend is maintaining all state on whether paper has been scanned and needs a decision, so that this abstraction can be used with different scanning components over time.

Likely design of status API call from frontend to backend meant to be polled often:
- no paper loaded
- ballot scanning
- ballot recently accepted
- ballot recently fully rejected (bad election, unreadable, etc.)
- ballot currently rejected awaiting voter decision (tabulate as is or eject.)
- ballot recently ejected by voter.

Likely design of status API calls from frontend to backend for performing scanning:
- perform scan (only works if paper is loaded)
- reject or forcefully accept ballot awaiting decision

**Comment by carolinemodic** [comment]
Update: rather than polling for statuses like "scanning" and the results of a scan, the scanning endpoint can block on scanning and return the result of the scan (overvote, success, bad election, etc.)
