### ISSUE TITLE
vxmarkscan: a11y controls (pause, help, rate) do nothing

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4618]
https://votingworks.slack.com/archives/CEL6D3GAD/p1707179141268099?thread_ts=1707179092.052939&cid=CEL6D3GAD

**Comment by kshen0** [comment]
Tested rate up/down and they work as expected. Not sure what was happening during initial QA. Pause and Help covered in https://github.com/votingworks/vxsuite/pull/4646
