### ISSUE TITLE
vxmarkscan: ATI onboarding / help

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4623]
VxMarkScan provides general on-screen guidance for a visual-touch user and also a guided device-setup flow for a dual-switch/limited-dexterity user. The audio-tactile interface experiences leaves much more to be desired.

The audio interface should initially provide audio instructions for how to use the tactile controller. Specifically it should instruct a user how to:
- Navigate and select contests
- Change volume
- Change rate of audio
- Pause audio
- Repeat content
- Seek more help with the controller

The help button on the controller should be remapped to an optional interactive flow (see below). As discussed, it's acceptable for the means to repeat content to be simply navigating "back" to the contest - as long as the means to do so is communicated. We do not need and explicit "replay" action on the audio tactile controller.

The interactive help feature should prompt the user to touch the controls on the tactile controller to learn their functions. When pressed, the audio track should state their function. A graphic of the controller can be shown on screen during this function. A user can be prompted to exit the help menu by clicking the help button again.

Slack context: https://votingworks.slack.com/archives/CJU9MSC6S/p1709052941623499

**Comment by kshen0** [comment]
Seems like @adghayes handled this in https://github.com/votingworks/vxsuite/pull/4676
