### ISSUE TITLE
Flush controller buffer on daemon startup

### ISSUE THREAD

**Issue by kshen0** [votingworks/vxsuite#4634]
If buttons on the controller have been pressed prior to the daemon starting up, all that data is flushed to the controller daemon when it tries to read the echo command. This causes the echo command to fail and exit the daemon.

We should instead on daemon startup read all data over serialport, then issue the echo command.

**Comment by arsalansufi** [comment]
The user impact of this change is that, if a user tries clicking the accessible controller too quickly after boot, the clicks themselves will delay the functioning of the controller even further.

**Comment by kshen0** [comment]
It's possible that pressing enough buttons before the daemon starts up will result in total failure to start up. This is because we only attempt restart `n` times, and each restart will flush `m` bytes from the in-buffer, so if more than `n * m` bytes are enqueued the startup will fail.

**Comment by arsalansufi** [comment]
Closing this since https://github.com/votingworks/vxsuite/pull/4916 is merged

Also just noting that we may have to revisit the controller integration as a whole if we switch to the 150
