### ISSUE TITLE
vxadmin: clicking save as when saving a tally report to usb hangs for a long time and then fails

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4682]
https://votingworks.slack.com/archives/C06NQFPGUDU/p1710295672002449

Issue automatically created from Slack feedback reported by arsalan: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1710438122245729

Copying from Slack:

> This was when we saved the full election tally report as pdf
> Not sure if the csv version or other reports would repro

**Comment by adghayes** [comment]
needs repro
