### ISSUE TITLE
Investigate report that "Logs Saved" modal is appearing before logs have finished exporting to the USB drive

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4685]
Full email from SLI:

> Hi all,
>
> This is a low priority observation and is not tied to any requirement failure
>
> I noticed that when using the “Save Log File” feature, the “Logs Saved” popup displays immediately after pressing “Save”. In a few instances now, I have selected “Close” and removed the USB drive from the device, and the logs were missing from the USB.
>
> I have tested this on the VxScan, Admin, and CentralScan, and it appears that if the USB is removed too quickly after selecting “Close”, the logs are not saved to the USB. I believe that the “Logs Saved” popup may be appearing before the logs are fully saved to the USB drive. I have not narrowed down a timing, but have noticed that if I remove the USB one to three seconds after selecting “Close” from the “Logs Saved” popup, the logs are not on the USB drive. Waiting longer than five seconds after selecting close, though, the logs are consistently saved to the USB as expected.
>
> Thanks!

https://votingworks.slack.com/archives/CJU9MSC6S/p1709652583628519

**Comment by adghayes** [comment]
@arsalansufi, as I'm going through issues I saw this one which seems like an easy fix, added you to review #4770.
