### ISSUE TITLE
Validate that HDMI output works on central system HP laptop

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4708]
After a few minutes of projecting from vxadmin, the projector stays on, but the laptop screen turns off. Must have done something wrong with X11 settings.

Issue automatically created from Slack feedback reported by ben: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1707183540728839

---

Update: The above was reported with respect to our Lenovos. We should start by just checking that HDMI output works with our new HPs. So long as that's the case, and if we can't easily repro what Ben has flagged, I'm okay to close this out

**Comment by amcmanus** [comment]
I have been unable to replicate this behavior on an HP vxadmin. Closing for now.
