### ISSUE TITLE
vxmarkscan: allow exporting diagnostics report to USB

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#4721]
Allow VxMarkScan readiness report to be saved to an attached USB. I think this will be easier than involving the print flow.

**Comment by mattroe** [comment]
Agreed. I also think we should just standardize this across all components so it's the same experience? No need for admin to be the lone print instead of PDF export component.

**Comment by adghayes** [comment]
I agree, that's a good standardization. I think we should add export to PDF to VxAdmin (will create a ticket) but I think I'd actually just  leave the print option up to save folks a step, and since it's already there.

**Comment by adghayes** [comment]
https://github.com/votingworks/vxsuite/issues/4726
