### ISSUE TITLE
Identify a path for rotating VSAP Secure Boot keys

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4791]

**Comment by arsalansufi** [comment]
@amcmanus has gotten this to work on VSAPs from LA! https://votingworks.slack.com/archives/C03Q42V9MJ5/p1730230000409399

There's been one notable gotcha around having to manually fix boot order, which we'll eventually update vx-iso to handle more automatically. But for now, a manual runbook will suffice. Will wait until we have that (can just be a Google doc) before we close this out

**Comment by amcmanus** [comment]
[Resetting/rotating keys](https://docs.google.com/document/d/1ii4eQd82LPDNp1aXrlEZAXrIMjh90PbfJ-1DPARoYlY/edit?tab=t.0#heading=h.352jhubuvjwv)

**Comment by arsalansufi** [comment]
Awesome, thank you @amcmanus! Reading through your Slack post, there were two other items that caught my attention and might require documentation for Bellingham:

> The TPM configuration only had SHA-1 available for the PCR Banks. I went ahead and enabled SHA-256.

> The biggest issue in my mind is the behavior of efibootmgr. It is not updating the boot order correctly, and it can get you in a failure state that requires manual intervention to edit the boot order. In a locked down system, that means using a vx-iso console session. We can resolve this by forcibly setting the boot order during the image flash via vx-iso.

Would be nice to have docs for those as well. I realize I'm shoehorning those into this ticket about Secure Boot keys when really I'm now thinking about VSAP imaging more broadly.

We can repurpose the above doc as a VSAP imaging guide, if that makes sense to you

**Comment by amcmanus** [comment]
[Correcting VSAP 150 Boot Order](https://docs.google.com/document/d/1orBOqIlHVHgUFqi4zg-XjIneGEs55VyBSzUjhlOGBQU/edit?tab=t.0)
