### ISSUE TITLE
VxMark: Play screen reader audio only via headphones (not speaker)

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4824]

**Comment by kshen0** [comment]
https://github.com/votingworks/vxsuite-complete-system/commit/b514de259db27dd655bd3d62682a6843ff7c4727#diff-12a1a1452af1c3622bdd7f5274165beaab0eeacc126cba22d4669687ab8f6e26R6 seems like a stable solution but needs to be productionized

**Comment by kofi-q** [comment]
> [votingworks/vxsuite-complete-system@b514de2#diff-12a1a1452af1c3622bdd7f5274165beaab0eeacc126cba22d4669687ab8f6e26R6](https://github.com/votingworks/vxsuite-complete-system/commit/b514de259db27dd655bd3d62682a6843ff7c4727#diff-12a1a1452af1c3622bdd7f5274165beaab0eeacc126cba22d4669687ab8f6e26R6) seems like a stable solution but needs to be productionized

+1 - thinking we'll also have to supplement this with an in-app enable/disable for the screen reader, so that audio starts from the beginning whenever headphones are plugged in

**Comment by arsalansufi** [comment]
https://github.com/votingworks/vxsuite-complete-system/pull/382
