### ISSUE TITLE
Replace cursor (visible on tap) with a circle on VxMark and VxScan

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4860]
See https://github.com/votingworks/vxsuite-complete-system/pull/372

**Comment by kofi-q** [comment]
Assuming we're ok with removing the cursor completely, but checking to make sure, in case we'd actually prefer the circle as visual touch feed back, vs no cursor at all - if we could hide it, is that preferable?

We can assign a `cursor: none;` to the whole screen in CSS, which would avoid having to run the unclutter command. Thinking maybe throw that behind a flag, so we don't lose the cursor in dev

**Comment by arsalansufi** [comment]
Yes totally okay to just remove the cursor completely, on VxMark and VxScan, if that's easier! Agree that we should keep the cursor in dev

That said, some searching does suggest that we may still need the `unclutter` command: https://stackoverflow.com/questions/41242383/hide-mouse-pointer-on-chromium-kiosk

The above also makes me wonder whether CSS will even work at all

**Comment by kofi-q** [comment]
Thanks for the heads-up! Sounds like we'll need both things in place for this to work right from startup. Tested the CSS change on the prod 155 and it successfully hides the cursor both at rest and on tap, but I'm guessing without `unclutter`, it would show up on initial load maybe until the first tap

**Comment by kofi-q** [comment]
Noting that this will require enabling the `REACT_APP_VX_HIDE_CURSOR` flag when building a prod image (is there somewhere else I should capture that, BTW? - I've always wondered where we track which flags to flip)

**Comment by arsalansufi** [comment]
Yes I've flagged this for myself!

> I've always wondered where we track which flags to flip

It has thus far just been my memory 🙈 I do document which flags I edit on build branches, e.g., https://github.com/votingworks/vxsuite/compare/main...2024-10-08-v4-qa

I do have this ticket open: https://github.com/votingworks/vxsuite/issues/5559

And think we could probably use a .env.production file to set certain flags for prod only
