### ISSUE TITLE
VxDesign: Properly account for HTML in propositions when generating translations and audio

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4896]

**Comment by jonahkagan** [comment]
Mostly addressed this in #5359 (for audio). The translation API [docs](https://cloud.google.com/translate/docs/basic/translating-text) claim that HTML tags should be preserved. However, I've noticed that sometimes it strips HTML tags. This is likely just a bug in the API, so I'm not sure what we can do to fix it.

**Comment by arsalansufi** [comment]
Consensus during discussion with @mattroe and @adghayes: We'll solve this with our eventual support of user-entered translation overrides
