### ISSUE TITLE
VxMark: Try reproing app crash when language is changed during ballot accept/removal

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4898]
We saw this while testing VxMarkScan for the LA demo but haven't been able to reliably repro. There does appear to be something wrong though.

Let's start by trying to repro. If we can't easily do so, we can table this.

**Comment by carolinemodic** [comment]
did a bit of trying to repro this today and could not

**Comment by arsalansufi** [comment]
I'm going to close this issue out given that 1) a lot of code has changed since we ran into this and 2) we weren't able to repro in our most recent repro attempts
