### ISSUE TITLE
Separate election hash and ballot hash

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4912]
[Product spec](https://docs.google.com/document/d/1FVAOWReHFzd75C5bqdgrh5gl22MFpPyGephc3TqWgIQ/edit)

**Comment by mattroe** [comment]
Thinking on packages: https://votingworks.slack.com/archives/CEL6D3GAD/p1715398497176849?thread_ts=1705526372.720269&cid=CEL6D3GAD
