### ISSUE TITLE
VxScan: Validate corner timing mark identification

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#4913]
When testing scanning ballots without the bottom row of timing marks, we realized that in some cases, this caused the interpreter to incorrectly identify the corner timing marks. Details here: https://votingworks.slack.com/archives/C073KBS0G91/p1717102793424839

We should improve the robustness of the interpreter by validating that the corner timing marks match the end of both the top/bottom rows and the left/right columns.

Also relevant is false positive scans of ballots with the corner folded: https://votingworks.slack.com/archives/C070FAWK71P/p1721062576578069

**Comment by arsalansufi** [comment]
@eventualbuddha Is this issue still relevant given the other interpretation updates that we've made?
