### ISSUE TITLE
VxMark: Card-reader only hw mod

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4918]

**Comment by arsalansufi** [comment]
@mattroe Can we close this out? I believe we do need the card reader + USB drive mod on the 150, as the 150 doesn't have the back USB drive that the 155 does

**Comment by mattroe** [comment]
No, let's leave this open, but we can change the milestone to cert. 

JD did a quick hack to support the card reader requiring us to kill the back port. The front port is nearly non-functional given the poor UX and I want to remove the front port to only use the back one.

**Comment by arsalansufi** [comment]
Got it! Makes sense
