### ISSUE TITLE
VxMark: Support paper with notch to ensure that thermal paper is oriented correctly

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4925]
We should also add a graphic for the insert paper screen, with notch oriented correctly

**Comment by kshen0** [comment]
Notched paper is now supported but we still need a graphic

**Comment by arsalansufi** [comment]
Marking this ticket done and opening a separate ticket for the graphic: https://github.com/votingworks/vxsuite/issues/5108
