### ISSUE TITLE
vxmarkscan: support 150

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4937]
https://votingworks.slack.com/archives/C03Q42V9MJ5/p1717192499360279

**Comment by arsalansufi** [comment]
Broke this into sub-issues:
- https://github.com/votingworks/vxsuite/issues/4960
- https://github.com/votingworks/vxsuite/issues/4961
- https://github.com/votingworks/vxsuite/issues/4962
- https://github.com/votingworks/vxsuite/issues/4963
- https://github.com/votingworks/vxsuite/issues/4965
- https://github.com/votingworks/vxsuite/issues/4966
