### ISSUE TITLE
Remove HMPB translations from election package to reduce size

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#4945]
To get multi-language HMPBs up and running quickly, I added a number of strings to `appStrings` in order to generate translations. However, these strings are only used for HMPB production, which happens in VxDesign, so they don't need to be included in the election package (and don't need audio generated). Making this change will help reduce the size of the election package.

**Comment by adghayes** [comment]
@jonahkagan I think that these translations got moved to the election definition in https://github.com/votingworks/vxsuite/pull/4995 so this is done.
