### ISSUE TITLE
VxMark: Don't reset voter settings after poll worker reloads paper that was incorrectly loaded

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4947]
Slack thread: https://votingworks.slack.com/archives/C03Q42V9MJ5/p1717783760439829

<video src='https://github.com/votingworks/vxsuite/assets/12616928/6df4a5e6-f7ab-42bd-80ff-5a2d1eeeed97' />

**Comment by kshen0** [comment]
This might be a race condition. I've been able to reproduce but unreliably. Adding console logs seems to increase the chance that `useSessionSettingsManager` is able to restore settings after the poll worker card is removed.
