### ISSUE TITLE
VxScan: Investigate PDI ejection failure issue

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#4956]
https://votingworks.slack.com/archives/C070FAWK71P/p1719878129956169

https://votingworks.slack.com/archives/CEL6D3GAD/p1716517550599449

**Comment by arsalansufi** [comment]
Related: https://github.com/votingworks/vxsuite/issues/5051

**Comment by arsalansufi** [comment]
Consolidating this issue and https://github.com/votingworks/vxsuite/issues/5051 and closing https://github.com/votingworks/vxsuite/issues/5051
