### ISSUE TITLE
VxScan: Adjust ballot scanned count screen location for non-multi-lingual definitions

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#4964]
The Voter facing language/accessibility settings button makes the screen broken based on ballot count placement

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1718220434398769?thread_ts=1718220434.398769&cid=CJU9MSC6S

**Comment by mattroe** [comment]
Bumping this up because I can't stand seeing this anymore

**Comment by arsalansufi** [comment]
This one is ultimately not critical for UAT as we'll be using a multi-language definition for UAT

**Comment by arsalansufi** [comment]
@kofi-q I'm going to move this ticket back out of the UAT milestone as we're using a multi-language election package for UAT, and some of the new finds from QA are higher priority for UAT
