### ISSUE TITLE
BMD: allow BMD to be configured for all precincts

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#498]
This should NOT be the default, an election admin should explicitly choose this as an option in the UI during configuration.

In mark+print mode, that means that the poll-worker screen needs to first prompt for precinct, then prompt for ballot style.

**Comment by eventualbuddha** [comment]
What do we do with reports? Do we continue printing a single report but with "All Precincts" in the title, or do we print one per precinct? cc @mcchilders @carolinemodic
