### ISSUE TITLE
VxScan: Printing a test page in production crashes the app

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5004]
Printing a test page in production crashes the app

Issue automatically created from Slack feedback reported by arsalan: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1719612688094639

You can access the "Print Test Page" button on the election manager screen under the "Printer" tab

**Comment by carolinemodic** [comment]
repros in VxDev because it can't find the test page pdf, I assume its the same issue in prod but it might be a little different how it should work there
