### ISSUE TITLE
vxscan: do not make timing marks worse after interpolation

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#5016]
Sometimes there's enough stretching (typically near the top of the ballot) that an interpolated timing mark could fit between two real timing marks. When this happens, we will infer a timing mark in that position. However, in situations where we've already found all the timing marks on a particular side and don't need to interpolate this actually makes things worse. We end up shifting all the timing marks up by one and the real bottom corner is left out. This should not happen. Note that this may be much less likely to happen after #5015.

| Partial | Complete (with inferred) |
|-|-|
| ![Image](https://github.com/votingworks/vxsuite/assets/1938/402efbae-bab1-4032-a50e-1491d7b3aae8) | ![Image](https://github.com/votingworks/vxsuite/assets/1938/4d0459d8-c748-4a9f-9b6f-81377f43385b) |

**Comment by adghayes** [comment]
@eventualbuddha is this still relevant?

**Comment by eventualbuddha** [comment]
This shouldn't be an issue anymore now that we reject ballots with unusual timing mark spacing.
