### ISSUE TITLE
Update top-level docs repo README to point to source code repos, as VxSuite landing page

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5028]
We should pick one of our repos (likely one of https://github.com/votingworks/vxsuite-complete-system or https://github.com/votingworks/vxsuite-build-system) and update it to reference all relevant VxSuite code, including https://github.com/votingworks/vx-iso, whether via mentions in the README or submodules.

This repo and its README should function as a home page / starting point for VxSuite code, not just for us internally, but for external viewers, too.

**Comment by mattroe** [comment]
We're also going to want to link to the TDP repo

**Comment by arsalansufi** [comment]
READMEs are updated and we're going to sort out the homepage question as part of TDP docs writing, the likely home page being: https://github.com/votingworks/docs-vxsuite-v4

**Comment by arsalansufi** [comment]
Actually, let me keep this issue open until we update the https://github.com/votingworks/docs-vxsuite-v4 README to point to the other repos

**Comment by arsalansufi** [comment]
https://github.com/votingworks/docs-vxsuite-v4/pull/7
