### ISSUE TITLE
VxMark: Language picker usability improvements

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#5033]
From https://votingworks.slack.com/archives/C03Q42V9MJ5/p1720209700026399:
- Language icon should be changed to a globe
- When the language button is focused, the audio should say "Would you like to change the language? Current language English"

From https://votingworks.slack.com/archives/C03Q42V9MJ5/p1720209700026399:
- Make sure touch screen clicks properly focus language options so that they're read out

**Comment by carolinemodic** [comment]
On the last point in the description, i just tested a bit and looked at the code and we do read out "Selected: Language" on each language when you select it. It seems like there can be a race condition where it gets cut off sometimes if it starts to read the button before it renders with the "selected: " prefix added? I'm not entirely sure if thats what is happening but that is my guess, although we don't seem to have any problem when doing the same thing for candidate buttons on a candidate contest page
