### ISSUE TITLE
VxMark: Unmuting audio after muting should not reset audio settings

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#5034]
When toggling audio only mode, the audio settings should not be reset to default

https://votingworks.slack.com/archives/C03Q42V9MJ5/p1719595328014329

**Comment by kofi-q** [comment]
Audio settings are persisted when going into audio-only mode. Guessing that the feedback came from someone who tried disabling audio first and then re-enabling via the "enable audio-only mode" button - updating this capture persisting settings across audio disable/enable states.
