### ISSUE TITLE
Support creation of QA prod images vs. final prod images

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5063]
Exact terminology for these two types of images TBD, but we often create production images for QA that we know are not final.

When creating a QA prod image, we want to:
- Grant vx-admin sudo privileges
- Set the vx-admin password to insecure
- Set the jurisdiction to vx.test on VxAdmin
- Not lock the image down
- Allow screencapturing
- Allow access to TTY2 (relevant once we remove access to TTY2 from locked-down images)
- More?

We can build this distinction into the image building process.

**Comment by mattroe** [comment]
Other needs:
* 000 pins
* skip certifier

**Comment by arsalansufi** [comment]
The core of this is done. Opened a new issue to capture the additions that we want to make: https://github.com/votingworks/vxsuite/issues/5166
