### ISSUE TITLE
EM: number of copies data entry is buggy

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#509]
Sometimes the digits get concatenated instead of scrolling up / down.

**Comment by beausmith** [comment]
![image.png](https://zube.io/files/votingworks/9203881dda0231e9d5702fe0413af104-image.png)

**Comment by eventualbuddha** [comment]
Any hints on how to reproduce this?

**Comment by carolinemodic** [comment]
@beau I'm not sure I'm understanding the bug here, is it that when there are more then 4 digits the number gets cutoff in the textarea box, or that pressing the up and down arrows makes the number grow 1 -> 11 -> 111 instead of 1-> 2 -> 3?

**Comment by eventualbuddha** [comment]
Maybe cap copies at 99? 999?

**Comment by adghayes** [comment]
no more ballot printing, no more copies input :)
