### ISSUE TITLE
VxMark: Use notched paper graphic

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5108]

**Comment by kofi-q** [comment]
BTW, is this referring to this screen in VxMark?

![Screenshot 2024-10-28 at 16 32 55](https://github.com/user-attachments/assets/3766aad9-afc0-4ee5-94d4-ff2291078d58)

**Comment by arsalansufi** [comment]
@adghayes That's correct! We're referring to the "Load Ballot Sheet" screen
