### ISSUE TITLE
Logging: Make sure that log export doesn't preemptively tell you that it's safe to remove the USB drive when data is still being written

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5118]
This is a known issue on v3.1. Let's make sure it isn't still an issue on v4.

https://votingworks.slack.com/archives/CEL6D3GAD/p1721757523376479?thread_ts=1721756895.611569&cid=CEL6D3GAD

**Comment by kshen0** [comment]
I'm unable to repro this issue on a VM. Added my notes in Slack.

**Comment by kshen0** [comment]
Likely duplicate of https://github.com/votingworks/vxsuite/issues/4685 solved by https://github.com/votingworks/vxsuite/pull/4770
