### ISSUE TITLE
VxScan: Missing USB drive should not block all screens

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#5128]
* when a user inserts a card, they should be able to access the PW/EM/SA menus even if a USB drive is not inserted
* after polls closed, the USB warning should not supersede the polls closed screen as removing the USB at this point is expected behavior

**Comment by arsalansufi** [comment]
This task should likely be done in conjunction with https://github.com/votingworks/vxsuite/issues/5146
