### ISSUE TITLE
Comprehensive copy pass

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5141]
Let's review all VxSuite UIs holistically and make sure that 1) we, especially electioneers, are happy with copy, and 2) copy is consistent across all VxSuite machines.

Below are some pieces of copy feedback that have already come up. This list is by no means comprehensive:

- [x] https://votingworks.slack.com/archives/CJU9MSC6S/p1721244662879669
- [x] https://votingworks.slack.com/archives/CJU9MSC6S/p1722033920495529
- [x] https://votingworks.slack.com/archives/CJU9MSC6S/p1722273958990799
- [x] https://github.com/votingworks/vxsuite/issues/2339

**Comment by mattroe** [comment]
- "speed" instead of "rate"
- chinese HMPB feedback #5358

**Comment by adghayes** [comment]
@mattroe closing this as I've worked through or punted on all items in our review: https://docs.google.com/document/d/1eFLG6XzmWx3lKzEtpnG9Wf0Wx2GDYhS7kBAXlr2ld_s/edit?tab=t.0#heading=h.ga0mgmslkw3z. 

The only remaining copy action item is to mock out an alternate VxScan PW screen.
