### ISSUE TITLE
VxAdmin: Check that we handle long contest names in WIA sidebar and main WIA table

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5145]
Sidebar: https://votingworks.slack.com/archives/CJU9MSC6S/p1721685269634539
Main table: https://votingworks.slack.com/archives/CJU9MSC6S/p1721685426245199

**Comment by jonahkagan** [comment]
Yep, fixed in https://github.com/votingworks/vxsuite/pull/5289#pullrequestreview-2251428292
