### ISSUE TITLE
Central system: Automate laptop BIOS config

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5161]
https://votingworks.slack.com/archives/CJU9MSC6S/p1722294876225339

**Comment by adghayes** [comment]
I want to give this a spin on Lenovo: [Think BIOS Config Tool](https://www.lenovo.com/us/en/software/think-bios-config-tool?mbtab_segment=work)

**Comment by adghayes** [comment]
On Lenovo, we don’t have any options to configure the BIOS from a file. Lenovo provides a BIOS Configuration Utility (BCU) and a Lenovo Advanced Settings Utility (ASU). The BCU is a Windows app with a GUI. It can successfully update BIOS settings from a configuration file on a Thinkpad, given that the Thinkpad is running Windows. It can also update BIOS settings on a remote computer, but the remote computer must be on the same network, turned on, and running Windows. Either way, a computer needs to be running Windows to use the tool. Procedurally, we’d have to buy laptops with Windows just for this purpose, connect those computers to a network, and do the update from a master computer running the BCU. The Advanced Settings Utility (ASU) is outdated software that is intended for servers and doesn’t support Debian or latest versions of Windows.

HP does have a feature called “Replicated Setup” available right from the BIOS. It allows us to export or import a configuration file, just as we need. It has some limitations - it doesn’t allow you to set a password or change certain secure boot settings. But it should allow us to set most settings. The flow would be:

- Boot into BIOS
  - Set password
  - Load configuration file
  - Turn off “Sure Start Secure Boot Keys Protection”
- Boot into BIOS
  - Turn on secure boot
  - Clear secure boot keys
- Continue with flashing, configuration, etc.

This does save us some time, but considering we're leaning Lenovo, we have to consider whether it's worth it. 

If we proceeded down this route with HP, the next step would be to get @amcmanus to refine the process.

**Comment by adghayes** [comment]
Closing this in favor of #5303. The initial scoping is done, just need to work out the exact flow on the HP, which is tracked in the other ticket.
