### ISSUE TITLE
VxMark: State machine bugs, potentially involving PAT states interfering with other states

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5170]
We've seen some VxMark state machine bugs in QA and current theory is that they have something to do with the PAT states interfering with other states. Below are some likely related finds:

- [ ] https://votingworks.slack.com/archives/CJU9MSC6S/p1722447687551929
- [ ] https://votingworks.slack.com/archives/CJU9MSC6S/p1722454095301839
- [ ] Also potentially related is https://github.com/votingworks/vxsuite/issues/5153

**Comment by kshen0** [comment]
I wasn't able to reproduce the first 2 issues but https://github.com/votingworks/vxsuite/pull/5195 should fix. Feel free to reopen if someone with hardware can repro.
