### ISSUE TITLE
VxMark: The “casting ballot” text is too small compared to the other full screen messages

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5180]
VxMark: The “casting ballot” text is too small compared to the other full screen messages. Update its size to match the other full screen messages.

Issue automatically created from Slack feedback reported by jonah: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722448382953579

**Comment by adghayes** [comment]
https://github.com/user-attachments/assets/43120d62-1724-409d-98e6-c133c9b7c994

**Comment by adghayes** [comment]
Closed by #5519
