### ISSUE TITLE
VxMark: Party text on review screen is hard to read

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5181]
The pipes separating the candidate name and party name feel unnecessary since they already have different styling. It makes it a bit harder to read. Also the party text is quite fine - maybe a bit too fine

Issue automatically created from Slack feedback reported by jonah: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722449376855749?thread_ts=1722449376.855749&cid=CJU9MSC6S

**Comment by adghayes** [comment]
![Image](https://github.com/user-attachments/assets/7c64c9dd-8976-4d1d-8532-3350f19a8969)
