### ISSUE TITLE
VxSuite: Review text alignment consistency

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5182]
VxMark: left align text on this screen to match with the rest of the app

Issue automatically created from Slack feedback reported by jonah: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722448951989649?thread_ts=1722448951.989649&cid=CJU9MSC6S

**Comment by mattroe** [comment]
We should just review this holistically as we are probably inconsistent in other places
