### ISSUE TITLE
VxSuite: Review ballot style lists and only expose parent/english ballot style

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5183]
VxAdmin: I find it slightly confusing in the manual tally flow how you have to select a ballot style but we have different ballot styles for each language. I know why we made those choices independently, but together it strikes me as odd as I'm guessing when people are entering manual tallies in general they are not trying to record the distinction of which tallies came from which languages?

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722451195735169?thread_ts=1722451195.735169&cid=CJU9MSC6S

**Comment by adghayes** [comment]
- [ ] Manual Tally Creation
- [ ] VxAdmin Report Generation
- [ ] VxMark Ballot Style Selection
