### ISSUE TITLE
VxScan: Change styling of election title/date on polls reports

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5187]
VxScan: the polls opened/closed reports style the election title as a label with a colon, followed by the date and location. This doesn’t really make sense, as it’s not a label

Issue automatically created from Slack feedback reported by jonah: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722533340896439?thread_ts=1722533340.896439&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Related #5204
