### ISSUE TITLE
precinct-scanner: friendlier / simpler overvote and blank screens

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#519]
Overvote is the technical term, can we find something simpler like "Too many bubbles filled in" or something like that.

Same for blank

**Comment by mattroe** [comment]
Just a note that for MS we'll also need this to be a friendlier undervote screen too

**Comment by eventualbuddha** [comment]
Also: what happens if there's both an undervote and an overvote?

**Comment by benadida** [comment]
to @eventualbuddha's question: uggh, that's a painful edge case. I think for now we show the overvote warning only. Later we can think about how to show both, if necessary.

**Comment by carolinemodic** [comment]
@eventualbuddha Assigning this to you since I believe it is covered by https://github.com/votingworks/vxsuite/pull/735
