### ISSUE TITLE
VxMark: Change poll worker facing copy post-spoil so continuing the voting session is primary action

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5191]
VxMark: as a poll worker, after spoiling an incorrect ballot and inserting a new blank paper, I hit this screen, which is confusing. I almost hit reset ballot right away. I think it would be clearer to have the headline be: “Remove card to continue voting session” and remove the reset ballot button

Issue automatically created from Slack feedback reported by roe: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722550231628579?thread_ts=1722550231.628579&cid=CJU9MSC6S

**Comment by adghayes** [comment]
not sure when exactly but this screen has already been changed and is somewhat clearer, so closing ![Image](https://github.com/user-attachments/assets/05b952fb-5c28-4347-b092-3dcbcbf079a1)
