### ISSUE TITLE
Revisit logging requirements and document/ticket what remains to be done

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5199]
We have this old longstanding issue for VVSG2 logging requirements: https://github.com/votingworks/vxsuite/issues/1244

Let's revisit that issue and confirm what all actually remains to be done, beyond the given "add missing logs for X, Y, Z events"

**Comment by carolinemodic** [comment]
Added remaining tasks to https://github.com/votingworks/vxsuite/issues/1244
