### ISSUE TITLE
VxAdmin: Inadequate error message when using SA card with wrong jurisdiction

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5200]
on vxadmin, when putting in a sysadmin card with wrong jurisdiction, the error message starts out correct, but then ends with "use a sysadmin card" ... but I did, it's just the wrong one. Tweak that error message

Issue automatically created from Slack feedback reported by ben: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722551122706799

**Comment by adghayes** [comment]
Closed by #5544
