### ISSUE TITLE
VxScan/VxAdmin: Add Election ID to reports

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#5204]
We need to add the election ID onto all reports. Currently we have the election title but not the election ID.

**Comment by adghayes** [comment]
There's a question of whether to do the ballot hash, the election package hash, or both.

**Comment by adghayes** [comment]
@benadida we discussed this in our triage meeting and don't see the benefit of putting an election ID on the polls reports. What is the use case, in particular to someone other than us?

**Comment by benadida** [comment]
It's an integrity check that I've heard requested from folks in NH. How do we know what election this printout is for if not for the election ID? Could be a different election with the same name. Given that we've split this up into election ID and ballot hash, I do think there's a good argument to be made that it should be the ballot hash, but either way, something with a stronger unique identity about the election than just the name.

I've also heard requests for the software version to be printed on the report. Basically everything that's on the screen, too.

I do think there's a lot of auditing value here. All evidence that things went well.
