### ISSUE TITLE
VxMark: Nit: Done" button on the settings/language picker is where the "my ballot is correct" button is on the ballot review screen its easy to accidently cast your ballot when just changing the settings

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5209]
Nit: Since the "Done" button on the settings/language picker is where the "my ballot is correct" button is on the ballot review screen its easy to accidently cast your ballot when just changing the settings

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722456164702979

**Comment by adghayes** [comment]
This difficult user flow is very unlikely as someone likely won't be changing their settings at this point.
