### ISSUE TITLE
VxMark: Does not check blank pages are actually blank

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5213]
VxMark: Machine accepts an HMPB as a "blank page." What are the security implications of this? Should we be checking the page is blank?

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722455194903769?thread_ts=1722455194.903769&cid=CJU9MSC6S

**Comment by adghayes** [comment]
We are OK with accepting non-blank pages here - not a meaningful malicious path and a regular user can just insert new paper.
