### ISSUE TITLE
VxMark: Audio choppiness on the 150 in production

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5222]

**Comment by kofi-q** [comment]
Verified that https://github.com/votingworks/vxsuite/pull/5227 definitely reduces the stuttering in the audio. I can consistently reproduce the stuttering with code prior to that PR, by reducing my VM CPU resources - had a hard time producing any stuttering with the same configuration on post-fix builds (but there were still one or two blips when I pushed the system pretty hard).

We can close for now and re-open if it's still a noticeable issue on the 150, but definitely worth addressing our UI thread performance in the long run.

**Comment by arsalansufi** [comment]
Nice, great to hear! (Pun intended)
