### ISSUE TITLE
VxScan: Polls open hangs after reconfiguring without power cycling

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#5229]
https://votingworks.slack.com/archives/CJU9MSC6S/p1723036803172419

**Comment by arsalansufi** [comment]
We'd recently been unable to repro but @mattroe is noting that he is repro-ing this again. Going to have him write down his exact repro flow.

**Comment by mattroe** [comment]
There may be alternative means of reproducing this issue, but I just tried to reproduce and was able to on the first attempt in the following steps:

- Configure VxScan for UAT election all precincts in official mode
- Scan ballots
- Unconfigure as EM
- Reconfigure VxScan for UAT QA election all precincts in test mode
- Click open polls and bug will reproduce

I don't think the package, mode, nor role used for unconfiguration matters, but documenting exactly what I did because people don't believe me that this is a bug!

**Comment by carolinemodic** [comment]
taking notes when I see this here: https://docs.google.com/document/d/1M7pbJlH0ZNrQm5mALFDgAnH8qQLEa6oL_OMn6sYUVxQ/edit

**Comment by arsalansufi** [comment]
My current hunch is that completing https://github.com/votingworks/vxsuite/issues/5260 will resolve this

**Comment by arsalansufi** [comment]
Closing this out for now, though we'll keep an eye on it
