### ISSUE TITLE
VxAdmin: Lock Machine Button can wrap on certain pages

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5237]
VxAdmin: Voting Method Ballot Count Report - Lock Machine button size is different than other report screens. 

![Image](https://github.com/user-attachments/assets/41041cd7-ccdb-4fd9-a96d-e9f52463aa45)

Issue automatically created from Slack feedback reported by adam: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722893318021589?thread_ts=1722893318.021589&cid=CJU9MSC6S

**Comment by adghayes** [comment]
We're just gonna make the button text "Lock"
