### ISSUE TITLE
VxAdmin: Copy incorrect in “Possible Double Vote Detected” warning

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5239]
VxAdmin: If you try to adjudicate a write-in for a candidate that already has a vote, you see the “Possible Double Vote Detected” warning. It suggests selecting “Mark Write-in Invalid,” which isn’t one of the options.

(I think we changed that button to “Mark write-in as undervote,” but that also doesn’t apply here)

Issue automatically created from Slack feedback reported by jonah: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1723072465437969?thread_ts=1723072465.437969&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Just change the button title!
