### ISSUE TITLE
Fix apps/mark-scan flaky tests

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#5248]
Here are some examples:
- https://app.circleci.com/pipelines/github/votingworks/vxsuite/16559/workflows/e6aad8e2-6f9c-4a6f-866c-0047570cee6d/jobs/641873
- https://app.circleci.com/pipelines/github/votingworks/vxsuite/16552/workflows/2fd35777-31dc-43db-99b6-57c3cd3273e8/jobs/641422
- https://app.circleci.com/pipelines/github/votingworks/vxsuite/16559/workflows/6089c025-2517-488e-b214-f44be06cb33d/jobs/641822
- https://app.circleci.com/pipelines/github/votingworks/vxsuite/16552/workflows/2fd35777-31dc-43db-99b6-57c3cd3273e8/jobs/641422
- https://app.circleci.com/pipelines/github/votingworks/vxsuite/16511/workflows/e77d6859-5267-409f-8bda-72ecde8508e4/jobs/638917
- https://app.circleci.com/pipelines/github/votingworks/vxsuite/16536/workflows/31758626-de05-4732-9ff2-d2efbfe4b162/jobs/640409

**Comment by kshen0** [comment]
https://github.com/votingworks/vxsuite/pull/5261
