### ISSUE TITLE
Fix flaky libs/cvr-fixture-generator tests

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#5249]
https://app.circleci.com/pipelines/github/votingworks/vxsuite/16511/workflows/86d58f33-3c50-4345-970e-2efd24c8d9e3/jobs/638903

**Comment by eventualbuddha** [comment]
Considering this closed now that the success rate for the last 7 days is 100%:
<img width="258" alt="image" src="https://github.com/user-attachments/assets/d5308f00-c475-4190-a59e-ac8fd2ef811d">
