### ISSUE TITLE
VxScan: Scanner crashes on polls open for accuracy test definition

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5263]
:bug: VxScan: Something went wrong upon opening polls for all bubble ballot (haven’t tried a different election since bumping to rc1) 

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722975768922219?thread_ts=1722975768.922219&cid=CJU9MSC6S

**Comment by carolinemodic** [comment]
does not repro when using a mock printer in dev
