### ISSUE TITLE
Central system: Something went wrong after leaving idle

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5264]
Our RC2 VxAdmin was showing something went wrong when I came in this morning after left overnight. Working fine after a ctrl r 

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1723566676272509?thread_ts=1723566676.272509&cid=CJU9MSC6S

**Comment by mattroe** [comment]
@arsalansufi to try to repro

**Comment by arsalansufi** [comment]
I've not been able to repro this leaving my machine idle up until the point of the timeout. And others have made it to the point of timeout fine as well. I'm going to close this out, but if we do ever see this again, we should look at the logs to understand what the exact error is.
