### ISSUE TITLE
VxScan: Footer election info not updating properly

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5265]
Not sure if this is a bubble ballot election bug or more widespread but I noticed the following behavior on VxScan UAT-RC2

Machine was previously configured for Sample Primary Election. Unconfigured as Election Manager and reconfigured with a new election package for all bubble ballot. Noticed the footer still had the old election so I thought I saved the wrong election package. Re-did this flow a few times with resaving the package and saw the same thing. Eventually realized that it was strange my bubble ballot-election manager card was even working if that wasn't the election so I opened the polls. This crashed (known problem reported elsewhere) and upon reboot the footer now properly reflected the bubble ballot election.

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1723567650346349?thread_ts=1723567650.346349&cid=CJU9MSC6S

**Comment by carolinemodic** [comment]
Repros in Dev switching between BubbleElection and MaximumElection

**Comment by carolinemodic** [comment]
Struggling to debug whats happening it seems like the election title values are getting refreshed properly when console logging but the html is still showing the wrong thing

**Comment by carolinemodic** [comment]
@kofi-q I was able to repro this consistently in dev when unconfiguring and reconfiguring between Jonah's maximum election and the all bubble election. The eelction title would not update but the election hash would.
