### ISSUE TITLE
VxMark: “Your ballot was cast" audio is sometimes repeated

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5293]
[VxMark] Sometimes, after casting a ballot and being returned to the “Insert Card” screen, the last bit of audio gets repeated (“Your ballot was cast. Thank you for voting.“)

Doesn’t happen consistently, but it’s only started happening recently. We did have a similar bug a while back though, so this might be a regression related to the other reset logic fixes,

Issue automatically created from Slack feedback reported by kofi: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1723572937186159

**Comment by adghayes** [comment]
Needs confirmed repro.

**Comment by mattroe** [comment]
Did not see during QA
