### ISSUE TITLE
VxAdmin: Manual results, prompt to enter number of votes for write-in candidate after adding

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5295]
When a write-in is added to the manual tallies, it would be helpful if there was a prompt to enter the number of votes for that write-in candidate. It defaults to zero now and New Durham missed entering the count a few times. It wouldn’t have been caught if they didn’t use the total number of ballots in each race box. 

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1723993921236839

**Comment by adghayes** [comment]
Closing as a nit.

**Comment by jonahkagan** [comment]
> Closing as a non-issue due to later manual results changes.

@adghayes I'm curious what changes you're referencing

**Comment by jonahkagan** [comment]
Gonna see if I can tackle this in my polish of manual tally entry
