### ISSUE TITLE
Tally Reports: Could include "moderator" and "clerk" under the appropriate signature line

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5296]
Jonathan in Londonderry asked if the printed reports could include "moderator" and "clerk" under the appropriate signature line.

Issue automatically created from Slack feedback reported by lectusconsulting: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1724165313799839

**Comment by adghayes** [comment]
We would like to avoid a New Hampshire specific feature that's not highly necessary.
