### ISSUE TITLE
Validate HP Elitebook 840 G11 for VxAdmin & VxCentralScan

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#5303]
We intend to use the HP Elitebook 640 G11 for VxAdmin and VxCentralScan for v4. We're already done some [preliminary investigations](https://docs.google.com/document/d/1KOcfMqQAySjr-SfSScNpGPd9vIYl7VRpnomsCvTWrCQ/edit) to scope the work and confirm feasibility. The work will be roughly:

- [ ] Audit BIOS settings and recommend choices for production
- [ ] Draft our BIOS / secure boot / install process, with order of operations
- [ ] As part of the above, generate the BIOS config file, with proper settings
- [ ] Explore how to get trackpad and wi-fi card working. In theory there should be a way, because they work on Ubuntu with a later kernel versions (24.04, kernel 6.8) but not on Debian 12.2 or Debian 12.6
- [ ] Maybe a change to support the card reader ([change for the built-in ThinkPad card reader for reference](https://github.com/votingworks/vxsuite/pull/4174))
- [ ] Preliminary end-to-end test, with production images, for both VxAdmin & VxCentralScan.

**Comment by arsalansufi** [comment]
Chatted with @amcmanus re the last checklist item

> Preliminary end-to-end test, with production images, for both VxAdmin & VxCentralScan.

And noted that, for his purposes, we really just want to confirm that all the relevant peripherals work with a prod image, e.g., card reader, USB drives, Fujitsu scanner, HP printer. He doesn't need to do a full QA checklist style pass.

**Comment by adghayes** [comment]
@mattroe and I will be doing the full QA style pass and @amcmanus doesn't have to, considering all the other things on @amcmanus's plate, but I still think it would be valuable. 

Due to the pivot from Lenovo, we are certifying on hardware we've never field tested and the more time we spend with it the better. We can check in about this at next software weekly?
