### ISSUE TITLE
Figure out how to handle (if at all) an error/unknown state from the getStatus endpoint in precinct-scanner

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#531]

**Comment by benadida** [comment]
can you say more about this, I'm not sure I understand the ticket.

**Comment by carolinemodic** [comment]
See the code here: https://github.com/votingworks/vxsuite/blob/main/frontends/precinct-scanner/src/app_root.tsx#L550

There are status's that module-scan returns for the scanner state that we currently just ignore and don't handle in the frontend of precinct-scanner. I initially showed an error screen when these would appear but then they would sometimes show up briefly during scanning so I stopped doing that. Although I think we have changed parts of the backend since then so idk if thats still true.
