### ISSUE TITLE
VxAdmin: Expose election package export button in sys admin UI

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5320]
We have three key user roles in VxSuite, aside from voters: system administrators, election managers, and poll workers. Sys admins have the highest privileges. They configure the election definition on VxAdmin, which is then used to configure VxCentralScan, VxMark, and VxScan. Sys admins' smart cards are accordingly election-agnostic. Election managers and poll workers, on the other hand, have election-specific smart cards and perform operations within the context of an election.

With that context in mind, VxSuite configuration currently looks like this:
- System administrator unlocks VxAdmin with their smart card and configures VxAdmin with an election package
- System administrator locks the machine
- Election manager unlocks VxAdmin with their smart card and re-exports a signed version of the election package to a USB drive
- That USB drive is then used to configure the other VxSuite machines

In practice, system administrators and election managers are often the same person. We had to separate the two roles and their corresponding smart cards to meet certain VVSG2 requirements.

Since the two are often the same person, and system administrators have higher privileges than election managers, let's give system administrators the same ability to re-export a signed version of the election package that we give to election managers.

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1724786491850729?thread_ts=1724786491.850729&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Note:
- not creating ticket for automatically signing package at this time, as it could create complications and confusion
- not creating ticket for SA to switch fully into EM role
