### ISSUE TITLE
VxAdmin: add rapid fire card programming mode

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5328]
To make programming large numbers of cards a little easier, make a card programming mode where the card is programmed as soon it is inserted.

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1724792239237069?thread_ts=1724792239.237069&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Not planned for now, but may be an idea for later.
