### ISSUE TITLE
Review and finalize logging related documentation for TDP

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#5337]

**Comment by arsalansufi** [comment]
Closing this out for now as we'll be tracking this as part of TDP tracking

Relevant documents include:
- https://docs.google.com/spreadsheets/d/1a27bQZYn35NRq9p_lyTkd7eQ8i8FyOuGsvz1EbuCOUE/edit?usp=sharing
- https://docs.google.com/spreadsheets/d/1iZIjlF3ccL0_YukwoTTqfK_-nVsMmbJT_E-GdORPZ-s/edit?usp=sharing
