### ISSUE TITLE
precinct-scanner: faster intake

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#535]
Consider calling `scan` repeatedly instead of `status` repeatedly and then `scan`. Decision to scan is still on the client side, but cuts back on ~150ms of status check + scan request, may feel a good bit snappier in paper uptake.

**Comment by benadida** [comment]
dupe of #975

**Comment by adghayes** [comment]
I don't think this is relevant any longer given the new scanner, but please re-open if I am wrong.
