### ISSUE TITLE
Fix ERR CDF to pass NIST CDF Validator

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#5368]
In checking other CDF files I noticed I was getting errors running the NIST CDF validator against the ERR CDF. I generated my ERR CDF by importing a election definition (in cdf format as I was also testing that) and exporting the cdf of results, with no data actually loaded (not sure if that matters to my errors). 

Attached my sample ERR file and the output from the nist tool. 
Nist tool github: https://github.com/usnistgov/cdf-test-method?tab=readme-ov-file (download from releases tab) 
Usage instructions (you have to do sudo bash ./testcdf): https://pages.nist.gov/cdf-test-method/USAGE.html 

You can just `cat` the report file to see all of the metadata.

  
[Sample ERR File](https://github.com/user-attachments/files/16936847/err.json)

[Sample output in slack (can't upload html to github) ](https://votingworks.slack.com/files/U01DC19BN6N/F07M0MUL533/vx-err-report.output.html)

**Comment by carolinemodic** [comment]
@adghayes @kshen0

**Comment by adghayes** [comment]
@kshen0 can this be closed?
