### ISSUE TITLE
Given a few voters writing in the same person in every contest, having a "go look up names from other contests" feature would be a big timesaver

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5383]
Given a few voters writing in the same person in every contest, having a "go look up names from other contests" feature would be a big timesaver.

Issue automatically created from Slack feedback reported by ben: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1726019723279359?thread_ts=1726019723.279359&cid=CJU9MSC6S

**Comment by adghayes** [comment]
duplicate of #4713
