### ISSUE TITLE
Add ability to unconfigure a machine to vendor card UI

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5385]
Open question whether this should involve a button in the app UI or a menu item in the terminal UI

Issue automatically created from Slack feedback reported by ben: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1725722783102409

**Comment by adghayes** [comment]
@arsalansufi didn't you already introduce `*` vendor cards?

**Comment by adghayes** [comment]
@arsalansufi never mind, we don't have unconfiguring in the vendor menu :)

**Comment by arsalansufi** [comment]
@adghayes Yup exactly! Renaming this issue for clarity - I see why you parsed it as you did haha
