### ISSUE TITLE
VxScan: Better direction on ballot orientation

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#5391]
Voters are confused about the required orientation of ballots (there is no required orientation) and the graphic on-screen might be confusing.

**Comment by jonahkagan** [comment]
I think it will be a bit difficult to know what to change without user testing some ideas. One idea I have is to have the main prompt be: "Insert Your Ballot Any Side Up"

![Image](https://github.com/user-attachments/assets/b81e3d58-48bf-436e-af9a-3051a229704e)

Not the most elegant but maybe will help?

**Comment by adghayes** [comment]
Maybe that would help, but I can't help but hate it.

The experience I had in NH was a poll worker explaining to the other poll workers at the beginning of the day that the ballots had to be inserted front side up, "the diagram even shows you!" Then in another jurisdiction, I watched as someone put their ballot in upside down, belatedly see the animation, then sharply react and try to flip their ballot right side up.

My conclusion is that the ballot in the animation is giving the impression of a certain ballot orientation to many. I wonder if we just make it less detailed somehow (no title?) it might be less confusing.

**Comment by jonahkagan** [comment]
Oh that's a good insight that the animation was a big part of it. Maybe the animation could alternate between all the various orientations of ballot? Or just a blank page?

**Comment by adghayes** [comment]
Closing as not planned until further feedback.
