### ISSUE TITLE
Make minimal/safe improvements to manual tally entry UI

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5399]
Let's consider some minimal/safe improvements to the manual tally entry UI for November. Maybe a simple version of https://github.com/votingworks/vxsuite/issues/5390. We've discussed auto-saving before, too, but that's more involved/risky (for a November patch that is).

**Comment by arsalansufi** [comment]
Update: No longer planning to make any updates for November / v3, but do want to make updates for v4. Changing the milestone accordingly

**Comment by jonahkagan** [comment]
Closing this issue in favor of more specific issues
