### ISSUE TITLE
Inspect and potentially replace Jackson's soft-side ballot box, and consider whether any others need replacement, too

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5402]
- https://votingworks.slack.com/archives/C07LBG41B3M/p1725999984625949
- https://votingworks.slack.com/archives/C07LBG41B3M/p1726001245839009

**Comment by benadida** [comment]
I've pinged Karen in Jackson to start the process of exchanging her ballot box.

**Comment by benadida** [comment]
I've inspected a new ballot box and made sure it's in good working order and am shipping it to Karen in Jackson today, along with return slip to ship to Bellingham the damaged box.
