### ISSUE TITLE
Deliver additional VxScans

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5405]
Deliver:
- [ ] 2 more for Londonderry
- [x] 1 more for Conway
- [x] 1 more for Moultonborough

For Londonderry, if we have to provide a soft-side ballot box, let's see if we can find a lock to seal it instead of a seal. The rest of their ballot boxes are ES ballot boxes and they're using the ES ballot box's built-in lock. They also empty their ballot boxes a lot throughout the day, so a padlock is more convenient than unsealing and resealing.

**Comment by adghayes** [comment]
Is the plan here to take from backup stock, and continue using v3.1.0 for backups? That would seem reasonable to me, as we probably don't need the degree of backup coverage as we had for the primary.

**Comment by arsalansufi** [comment]
That's correct @adghayes!
