### ISSUE TITLE
Customer mentioned that for manual tally input, it would be nice to have a "ballots cast - apply to all" type choice so that for each race we don't have to input the # of ballots, if we so choose

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5407]
Customer mentioned that for manual tally input, it would be nice to have a "ballots cast - apply to all" type choice so that for each race we don't have to input the # of ballots, if we so choose

Issue automatically created from Slack feedback reported by janine: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1726248143702439

**Comment by jonahkagan** [comment]
Cases when ballot counts can be different across contests:
- Military ballots that don't have all of the contests (https://votingworks.slack.com/archives/CEL6D3GAD/p1726175073135319)
- Different numbers of ballot sheets were returned for some reason

**Comment by arsalansufi** [comment]
Update: No longer planning to make any updates for November / v3, but do want to make updates for v4. Changing the milestone accordingly
