### ISSUE TITLE
Run code through SLI pen-test utility

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5423]

**Comment by benadida** [comment]
looks like I had written lightweight docs for this, which I think are enough to get started, and @amcmanus I can fill in the blanks when you get this running.

https://docs.google.com/document/d/15mn08hefHW4oxvcmO3dwnxoDO8CU0Q5jN9oNJdHa_Yc/edit?tab=t.0#heading=h.oxohus7we3ss

**Comment by arsalansufi** [comment]
https://votingworks.slack.com/archives/C071GGPA25D/p1732656280005939
