### ISSUE TITLE
For VxAdmin and VxCS - diagnostics are called "hardware diagostics" and VxScan and VxMark are "system diagnostic

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5432]
For VxAdmin and VxCS - diagnostics are called "hardware diagostics" and VxScan and VxMark are "system diagnostic." I know a copy review is occurring soon and that the diagnostics screens that I have are maybe not the latest and greatest.

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1726767074963449

**Comment by adghayes** [comment]
Closed by various copy PRs
