### ISSUE TITLE
Ballot interpretation does not handle stretching well

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#5437]
In a ballot with significant stretching that does not result in skew–because it's roughly even on both sides of the paper–the interpreter may misidentify the timing mark grid and subsequently look for bubbles in the wrong place. See this partial example:

![image](https://github.com/user-attachments/assets/f35729c1-cf99-4230-9313-b95c0fd3c4cd)

For a more complete example, see [this Slack thread](https://votingworks.slack.com/archives/C06H2PBP0MU/p1727297844666109?thread_ts=1727290684.004959&cid=C06H2PBP0MU). Note that I'm not posting the full images here because they are from ballots for an upcoming election.

**Comment by adghayes** [comment]
@arsalansufi should we be prioritizing now since as it's an interpretation change?

**Comment by arsalansufi** [comment]
I believe @nbhatia823 was actively trying to diabolical skew when he generated this image, so it's highly unlikely that this will come up in real usage. My current thinking has accordingly been that it's okay to punt on this until v4.1

Let me tag with `triage` for us to discuss, though
