### ISSUE TITLE
Crash and log unexpected errors during interpretation (rather than rejecting the ballot as unreadable) (potentially with safeguards to prevent crashing during election day)

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5459]
Additionally, let's:

- [ ] Audit VxSuite for other places where unexpected errors are turned into user-facing errors rather than crashing
- [ ] Consider writing some easily identifiable record to the file system or connected USB drive when this happens to make debugging extra easy, especially for external contract manufacturers when that time comes

**Comment by jonahkagan** [comment]
> Consider writing some easily identifiable record to the file system or connected USB drive when this happens to make debugging extra easy, especially for external contract manufacturers when that time comes

Using existing logging to meet this requirement

**Comment by jonahkagan** [comment]
> Audit VxSuite for other places where unexpected errors are turned into user-facing errors rather than crashing

I audited the ballot interpretation path, but not anything else for now
