### ISSUE TITLE
The system admin screen is inaccessible in VxMark when the “Internal Connection Problem” screen is showing

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5523]
The system admin screen is inaccessible in VxMark when the “Internal Connection Problem” screen is showing. I think we could use some reworking of screen precedence like @caroline did for VxScan.

Issue automatically created from Slack feedback reported by drew: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1728934500514529

**Comment by adghayes** [comment]
@mattroe the vendor screen is also accessible in this state, so I think this is a must-do. looks easy though

**Comment by mattroe** [comment]
did you already fix this?

**Comment by adghayes** [comment]
up for review #5535
