### ISSUE TITLE
I closed the top of the VxAdmin laptop and left it for well over 30 minutes and it didn’t time out

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5532]
I closed the top of the VxAdmin laptop and left it for well over 30 minutes and it didn’t time out

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1728324213823199?thread_ts=1728324213.823199&cid=CJU9MSC6S

**Comment by mattroe** [comment]
@arsalansufi to try to repro

**Comment by arsalansufi** [comment]
Documenting that react-idle-timer (and our version of it) should handle when a computer goes to sleep: https://idletimer.dev/docs/about/changelog#550

**Comment by arsalansufi** [comment]
I've been able to repro this and am not yet sure of how to best fix

**Comment by mattroe** [comment]
I just tested this on the HP laptop and wasn't able to reproduce the issue that I could previously on the Lenovo. The device also properly goes to sleep on close, which I haven't seen on the Lenovos previously.
