### ISSUE TITLE
Vertical Streak Detection Controls

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#5538]
We'd like to land two improvements for vertical streak detection for v4.0:

First, we'd like to add an ability to turn off the feature. Add a system setting, `disableVerticalStreakDetection`, that turns the feature off in both scanners. 

Second, we need to somehow surface the warning in VxCentralScan rather than simply failing. Ideally, it's treated as an unreadable ballot with a special message. For example, in this screen: 
![image](https://github.com/user-attachments/assets/0fae8341-3129-4b84-a619-263838994122)
Copy suggestion:
Ballot Not Counted
Streak Detected
The last scanned ballot was not tabulated because the scanner needs to be cleaned.
Clean the scanner before continuing to scan ballots.

**Comment by mattroe** [comment]
I think this could also be a system setting as you should catch this in L&A
