### ISSUE TITLE
VxScan boot screen is wrong resolution/stretched, and VxMark boot screen is rotated

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5625]
Got lost in the shuffle of #milestone-v4-trr - Matt is reminding me that, on latest software + hardware, the VxScan boot screen is the wrong resolution/stretched, and the VxMark boot screen is rotated.

Issue automatically created from Slack feedback reported by arsalan: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1732049884115199

**Comment by amcmanus** [comment]
Noting that we can resolve the VxScan boot screen with the same Plymouth theme used on VxAdmin and VxCentralScan. The VxMark is not a straightforward resolution due to rotation requirements. Looking into options here.

**Comment by adghayes** [comment]
Closed by https://github.com/votingworks/vxsuite-complete-system/pull/426
