### ISSUE TITLE
I had a jam on the VSAP earlier and landed on this page which is weird to me in two ways:
• It seems to instruct me to clear the jam but if I do, I immediately get hit with the cover alarm because this is not an authenticated state
• I’m able to deactivate the voting session even though it’s not an authenticated state, but we normally only expose that option to poll workers

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5658]
I had a jam on the VSAP earlier and landed on this page which is weird to me in two ways:
• It seems to instruct me to clear the jam but if I do, I immediately get hit with the cover alarm because this is not an authenticated state
• I’m able to deactivate the voting session even though it’s not an authenticated state, but we normally only expose that option to poll workers

Issue automatically created from Slack feedback reported by drew: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1731653148482709

**Comment by adghayes** [comment]
Closing in favor of consolidated #5657.
