### ISSUE TITLE
[MarkScan] We seem to show the pollworker a screen saying the ballot page is blank when it just can't interpret the sheet but it is not blank

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5659]
[MarkScan] We seem to show the pollworker a screen saying the ballot page is blank when it just can't interpret the sheet but it is not blank

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1731616260010729

**Comment by adghayes** [comment]
Closing in favor of conslidated #5657
