### ISSUE TITLE
It’s weird that when a ballot is being shown in the front input tray, if you connect a PAT device, it will slightly retract and then re-extend the ballot

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5662]
It’s weird that when a ballot is being shown in the front input tray, if you connect a PAT device, it will slightly retract and then re-extend the ballot

Issue automatically created from Slack feedback reported by drew: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1731284422698899

**Comment by adghayes** [comment]
Closed in favor of consolidated #5657.
