### ISSUE TITLE
documenting an edge case - strange sequence of events on VxMark
• Insert Pre-Printed Ballot
• Return Pre-Printed Ballot
• As the ballot has just exited or is about to exit, the screen shows a “jam clear” situation

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5663]
documenting an edge case - strange sequence of events on VxMark
• Insert Pre-Printed Ballot
• Return Pre-Printed Ballot
• As the ballot has just exited or is about to exit, the screen shows a “jam clear” situation. There was never any paper to remove, it must have briefly detected a jam and then detected it’s resolution
• As a result, prompted me to insert a blank sheet to continue voting, even though I had just ended the current voting session
• Insert sheet, which is immediately spat back out front and everything normal

Issue automatically created from Slack feedback reported by drew: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1731280926883269?thread_ts=1731280926.883269&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Closed in favor of consolidated #5657.
