### ISSUE TITLE
VxMark deep cut: If you choose to insert a preprinted ballot, and indicate that it's incorrect at the review step, after ballot removal, you're taken back to the load paper screen and the machine is still expecting a preprinted ballot, which it's highly unlikely you'll have having just rejected the one that you previously inserted

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5665]
VxMark deep cut: If you choose to insert a preprinted ballot, and indicate that it's incorrect at the review step, after ballot removal, you're taken back to the load paper screen and the machine is still expecting a preprinted ballot, which it's highly unlikely you'll have having just rejected the one that you previously inserted. It probably makes more sense to take you back to the very initial screen so the poll worker can select a ballot style and insert a blank sheet for you. You can of course just click back from the load paper screen so not a big deal.

Taking you back to the load paper screen makes more sense when you mark a ballot as incorrect after having started from a blank sheet. A ballot style has already been selected and you presumably want to just try again.

This is very v4.1-y, not v4.0, just documenting hah

Issue automatically created from Slack feedback reported by arsalan: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1731279512644189?thread_ts=1731279512.644189&cid=CJU9MSC6S

**Comment by adghayes** [comment]
Closed in favor of consolidated #5657.
