### ISSUE TITLE
BS/EM: review how batches / batch counts work

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#567]
- add batch name/id to CVRs
- provide batch tally reporting
- make it possible to label batches appropriately and in a human-readable way

could use help from @mcchilders on this

**Comment by carolinemodic** [comment]
https://docs.google.com/document/d/1As1-GIAzpCxB_ChIL928TdRU3KDyo8Kkk8HJk841ajQ/edit#heading=h.h4mor6j27ykj
