### ISSUE TITLE
add some warning to vxsuite-complete-system when not all submodules are up to date

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#602]
Add explicit confirmation on build if out of date, i.e. maybe as part of `make build` it'll check that `kiosk-browser`, `vxsuite`, and `module-converter-sems` are up-to-date. If not, confirm with the user that that's intentional.

cc @benadida for thoughts on this plan

**Comment by adghayes** [comment]
Note that I'd like to close this once we kill `kiosk-browser` (because that seems to be where we're headed) and can simplify `vxsuite-complete-system` submodule architecture. But that could take a while, so leaving this open unless it is not relevant for some other reason.
