### ISSUE TITLE
Share `tsconfig.json` settings across projects

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#604]
We need to investigate how best to do this. Likely we can have a `tsconfig.shared.json` at the root that the projects extend. On top of that, though, we probably want the `libs` to have both a `tsconfig.build.json` and a `tsconfig.json` that extends the build config. The `apps` probably should have just a `tsconfig.json`.

**Comment by adghayes** [comment]
@eventualbuddha is this done?

**Comment by eventualbuddha** [comment]
Done enough that there's no good reason to keep this open. If we were to completely close this out we'd have almost nothing in most of the `compilerOptions` section of any given `tsconfig` file, instead just inheriting from the shared one.
