### ISSUE TITLE
Better factories for `InterpretedPage`

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#616]
We need fixtures for `InterpretedPage` objects a lot in `module-scan`, `bsd`, and `precinct-scanner`. Creating them is tedious and error-prone. Having factories that can help build them would be great. Probably move the types/schemas into `/types` and the factories in `/test-utils`.

**Comment by carolinemodic** [comment]
@eventualbuddha is this still relevant?

**Comment by eventualbuddha** [comment]
Probably not so much that we should keep it open. @jonahkagan is redoing a lot of this, I think.
