### ISSUE TITLE
central scanning: determine needs for labeling batches

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#649]
This may be needed for ballot custody, or possibly for things like "curbside"

I am a little worried about this feature being abused in ways that violate voter privacy, so let's keep that in mind. That said, we do want to make sure our scanner can be exemplary at assisting good ballot custody practices.

**Comment by carolinemodic** [comment]
https://docs.google.com/document/d/1As1-GIAzpCxB_ChIL928TdRU3KDyo8Kkk8HJk841ajQ/edit#heading=h.h4mor6j27ykj
