### ISSUE TITLE
plustek: try new driver to prevent rare double-feeding

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#669]

**Comment by eventualbuddha** [comment]
New driver appears to correctly fail operations (accept/reject/etc) when both sides have paper, and there's a new error status called `PLKSS_ERRCODE_VTM_BOTH_SIDE_HAVE_PAPER` that is returned by operations and when getting paper status.

Our existing `precinct-scanner` logic does not properly handle this and so gets into an unrecoverable scanner error, at least until the paper is removed and the tablet restarted.
