### ISSUE TITLE
bmd: what do we do when inserting the "wrong" admin card?

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#707]
We likely want to allow unconfiguring, but currently we don't check the election hash matches before allowing you to change settings. This means all admin cards are effectively the same for purposes of "authentication". Should we make it so all you can do when putting in an admin card that doesn't match is unconfigure?

**Comment by benadida** [comment]
this will be solved by the new authentication approach, where admin cards for a diff election have no power, and superadmin can unconfigure.
