### ISSUE TITLE
try fujitsu fi-7600

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#73]
now that we know more about how to get the right image size from scanner

**Comment by eventualbuddha** [comment]
That machine is a beast. Who gets it?

**Comment by benadida** [comment]
I've got one here, I was playing with it over the last 2 months in case we needed it. I'm happy to do more experimenting or happy to get it over to you. (It's $3500 and large, so don't think it makes sense for all of us to have one.)

**Comment by eventualbuddha** [comment]
Tried this, it's fast as long as you do JPEG format. Also can do landscape if you specify the width/height, results in a rotated/landscape page image.
