### ISSUE TITLE
ps: don't reject when requiring review

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#740]
When we _can_ accept a ballot but we want confirmation first due to overvote or whatever, don't eject the paper back to the voter. Just present a message on screen and give them options for returning the ballot or accepting it as-is.

**Comment by eventualbuddha** [comment]
Do we still want to do this? It might increase walk-away concerns. @ginvdr was concerned that the current setup isn't very private. Needs discussion?

**Comment by benadida** [comment]
assigning to @mcchilders for consideration of what we should do here. Configurable? Or just change our behavior to ballot inside scanner?
