### ISSUE TITLE
Investigate possible broken setup in vxsuite-complete-system

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#775]
From Caroline:
"fyi I think the setup for module-converter-sems and module-smartcards might be broken in vxsuite-complete-system right now, I'm seeing errors in the logs about the virtualenv not being able to be created and they don't seem to be working at all but I haven't looked into it extensively."

More details can be found in the thread here: https://votingworks.slack.com/archives/CEL6D3GAD/p1630018667008900

**Comment by eventualbuddha** [comment]
I think the virtualenv is not being carried over to the new location. See [this caveat](https://pipenv-fork.readthedocs.io/en/latest/install.html#virtualenv-mapping-caveat).

**Comment by eventualbuddha** [comment]
Pretty sure this is due to a missing `PIPENV_VENV_IN_PROJECT=1` in the new build setup. Testing now.
