### ISSUE TITLE
can we print 17" on HP m404dn?

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#791]

**Comment by benadida** [comment]
not succeeding at this so far. Will keep trying.

**Comment by benadida** [comment]
pretty sure the answer is no.

**Comment by eventualbuddha** [comment]
Might need https://www.amazon.com/HP-LaserJet-5200N-11X17-Printer/dp/B0055MVF1G.

**Comment by benadida** [comment]
@eventualbuddha yeah and those are no longer being produced, I think it's refurbished only.
