### ISSUE TITLE
order seals

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#797]

**Comment by eventualbuddha** [comment]
Per @umbernhard: https://www.lhsassociates.com/shop/es/

**Comment by adghayes** [comment]
- Ordered small quantities of 5 different types of seals from LHS, but they need to contact me before they approve my order
- Ordered packs of Spring Lock and Mini Seals from PrintElect
- Already have McMaster Pull-Tite seals. Other seals available from McMaster on short notice, if needed

**Comment by umbernhard** [comment]
@adghayes I would really like to chat about this before we make more purchases. The standard pull seals are not great and I think we can do better.

**Comment by benadida** [comment]
I suggest two tracks:
- let's get seals we can use right now so we're not without seals (sounds like @adghayes is doing just that).
- let's make sure our production choice for seals is using @umbernhard's expertise to make sure we've got the very best.
