### ISSUE TITLE
Improve experience of trying to print precinct-scanner tally report on VxMark bmd

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#830]
If bmd is in VxMark mode but a printer is connected right now the bmd will act like you can print a precinct scanner report and let you do so but will only print a blank page of paper. We should make it either work regardless of app mode or not show the prompt to print a precinct-scanner report if it is not in print mode.

**Comment by benadida** [comment]
We should not have it do anything related to printing if it's in `vxmark` mode.

**Comment by mattroe** [comment]
done
