### ISSUE TITLE
printer: still seeing cases where it's not detected until unplug/replug

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#865]
notable in precinct scanner which defaults to writing to card if it can't find the printer.

have not yet figured out a consistent way to repro, though it does seem like an initialization issue in some cases.

**Comment by benadida** [comment]
@eventualbuddha I think this is done with your new hooks-dependencies review?

**Comment by eventualbuddha** [comment]
Maybe. I was never really able to reproduce this, so I'm not sure it's fixed.

**Comment by eventualbuddha** [comment]
Assigned back to you, @benadida, to try to reproduce this.

**Comment by benadida** [comment]
at first glance this is looking fixed... I'll keep testing, but I haven't seen this come up yet.

**Comment by benadida** [comment]
yeah, this looks fixed. Nice work.
