### ISSUE TITLE
Improve encoding cards workflows

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#888]
Add errors when they happen. Make override write protection more integrated.

**Comment by carolinemodic** [comment]
from @beau 

If you improve the card programming flow, to handle the "override write protection" thing, this is what I had been thinking we might do when a user clicks "Create Admin Card"…
If card has write protection on, display a modal confirming that the user wishes to wipe the content on this card.
This modal can also show some of the election config data from the card to help the user determine if they really want to overwrite this card.
The buttons available should be "Cancel" and the button to continue should be danger/red and have a label like "Overwrite Card".

**Comment by mattroe** [comment]
auth project fixed!
