### ISSUE TITLE
Abstract locked/unlocked screens into shared components/hooks

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#893]
Maybe also a shared custom hook for userCurrentUserSession?

**Comment by adghayes** [comment]
Jotting down some eventual implementation thoughts from working on #1910... The Locked, Invalid Card, Keypad, Remove Card, and if desirable, also the Setup Card Reader page could all be abstracted individually and then into a single, full auth flow component in `libs/ui`. Would help remove 3 screens from each app, remove duplication of things like `ElectionInfoBar` in so many places, and deduplicate auth flow testing.

**Comment by carolinemodic** [comment]
This is done
