### ISSUE TITLE
VxCentralScan: when expecting legal/17" ballots, BMD ballots will not scan if QR code is oriented up

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#911]
This is because it's not looking for the QR code in the right place in the image, since it's expecting a taller image. It will work if the QR code is facing down.

**Comment by eventualbuddha** [comment]
I'm trying to reproduce this by creating legal-size images that have a letter-size BMD ballot. I haven't been able to do so. Here's the ones I made:

||Right-side up|Upside down|
|-|-|-|
|**Top aligned**|![sample-batch-1-ballot-1-legal-rightside-up-top-aligned](https://user-images.githubusercontent.com/1938/178353958-ada32370-f219-4efd-822a-9ba8a6bcfc9e.png)|![sample-batch-1-ballot-1-legal-upside-down-top-aligned](https://user-images.githubusercontent.com/1938/178354004-231dfa77-cb11-4340-90a4-50928c9f3d31.png)|
|**Bottom aligned**|![sample-batch-1-ballot-1-legal-rightside-up-bottom-aligned](https://user-images.githubusercontent.com/1938/178354161-e469e480-bd9d-4959-a06b-9ec6b4c03da5.png)|![sample-batch-1-ballot-1-legal-upside-down-bottom-aligned](https://user-images.githubusercontent.com/1938/178354259-26dd3627-3b03-4f0f-b6a9-e6819e1bcb61.png)|

And of course the letter-size ones:
|Right-side up|Upside down|
|-|-|
|![sample-batch-1-ballot-1-letter-rightside-up](https://user-images.githubusercontent.com/1938/178354460-416b24d8-a33b-4abf-961b-b9f4d4692414.png)|![sample-batch-1-ballot-1-letter-upside-down](https://user-images.githubusercontent.com/1938/178354518-b84f8630-4dae-442a-b373-68f1491a3bcd.png)|

@mattroe or @benadida, do you have any images that had this problem?

**Comment by eventualbuddha** [comment]
I think I was able to reproduce this with 8.5x17" ballots:

```
sample-ballot-images/sample-batch-1-ballot-1-17in-rightside-up-bottom-aligned.png: no QR code detected
sample-ballot-images/sample-batch-1-ballot-1-17in-rightside-up-top-aligned.png: @top via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA

sample-ballot-images/sample-batch-1-ballot-1-17in-upside-down-bottom-aligned.png: @bottom via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA

sample-ballot-images/sample-batch-1-ballot-1-17in-upside-down-top-aligned.png: no QR code detected
sample-ballot-images/sample-batch-1-ballot-1-legal-rightside-up-bottom-aligned.png: @top via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA

sample-ballot-images/sample-batch-1-ballot-1-legal-rightside-up-top-aligned.png: @top via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA

sample-ballot-images/sample-batch-1-ballot-1-legal-upside-down-bottom-aligned.png: @bottom via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA

sample-ballot-images/sample-batch-1-ballot-1-legal-upside-down-top-aligned.png: @bottom via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA

sample-ballot-images/sample-batch-1-ballot-1-letter-rightside-up.png: @top via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA

sample-ballot-images/sample-batch-1-ballot-1-letter-upside-down.png: @bottom via qrdetect
VlgCtS6fRyi7NOf/SAMDFgggAAEA
```

**Comment by benadida** [comment]
@eventualbuddha try scanning a 8.5x11 BMD ballot on a fujitsu configured to scan an 8.5x14. One orientation will yield 3" of crud on before the QR code.
