### ISSUE TITLE
election-manager: review flow of multiple print buttons for test deck

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#913]
You click print, then you choose precinct, then you click print again.

Maybe the first button shouldn't say "print"?

**Comment by eventualbuddha** [comment]
@adghayes to link to context.

**Comment by adghayes** [comment]
@eventualbuddha I was confusing this with another piece of machine-feedback: https://votingworks.slack.com/archives/CJU9MSC6S/p1635344205019600. We should open up a separate ticket for that if we're going to put it on the board. I can write up an idea of how that feature might work / change.

**Comment by benadida** [comment]
being done as part of VxAdmin revamp
