### ISSUE TITLE
[auth] invalid card warning copy is a little odd

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#927]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/1938/134089686-c248ef37-2091-4c4f-afce-87d95b616552.png">

We should come up with something that reads more naturally. Maybe something like this:

> This card cannot unlock this machine. Please insert a valid admin card.

**Comment by mattroe** [comment]
This screen was changed in the auth flows project.
