### ISSUE TITLE
bmd: choose-precinct for ballot activate shows weird split of dotted outline of precinct buttons

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#944]
- the dotted outlines on those buttons, meant for accessibility, likely doesn't belong on this poll worker screen.
- if we keep it, we need the outlines properly boxing the buttons.
- for some reason they're showing up on hover sometimes... probably not an issue on a touch screen, but.. interesting

I would suggest taking this outline off altogether.

**Comment by adghayes** [comment]
UI has been entirely revamped, no longer relevant.
