### ISSUE TITLE
precinct-scanner: improve eject USB screen

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#959]
It's a bit confusing after you request ejection what you're supposed to do, since it's still prompting you to eject even if you've done it.

**Comment by eventualbuddha** [comment]
From [Slack discussion](https://votingworks.slack.com/archives/CEL6D3GAD/p1633386040028200):

![image.png](https://zube.io/files/votingworks/d24a14886946ac09d6d39c5b7aa7bd12-image.png)

> ben: maybe it should say "you may now unplug the USB drive" or something
