### ISSUE TITLE
Write a test for up/down arrows of accessible controller

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#988]
We had a bug in the past where after a specific modal was opened the aria focus would get broken and stay focused on a destroyed modal instead of refocusing on the rest of the screen. This causes navigation with arrows on the accessible controller to not work as that relies on the focus elements. Writing a test to catch this may be tricky as to be most effective you would need to test the use of the arrows AFTER opening and closing every modal in the app to make sure none are causing problems.

**Comment by carolinemodic** [comment]
The fix to the modal, and the reset accessible controller button are both in main. Do we still need the reset button?

**Comment by benadida** [comment]
@carolinemodic Let's leave the reset button, just in case there is a new issue that comes up where a reload will help.
